### ISSUE TITLE
Error in generated SCSS (from css)

### ISSUE THREAD

**Issue by seantanly** [tenex/rails-assets#102]
I'm trying to precompile 

https://github.com/jackmoore/colorbox/blob/master/example1/colorbox.css

but encounters the following

```
Invalid CSS after "...round image-url": expected "{", was "("jquery-colorb..."
```

Upon checking the generated scss in from the gem rails-assets-jquery-colorbox, I noticed the generated background statements are missing a colon.

Original CSS

```
#cboxOverlay{background:url(images/overlay.png) repeat 0 0;}
```

Generated SCSS

```
#cboxOverlay{background image-url("jquery-colorbox/example1/images/overlay.png") repeat 0 0;}
```

The correct SCSS should be

```
#cboxOverlay{background: image-url("jquery-colorbox/example1/images/overlay.png") repeat 0 0;}
```

Fixing this in the gem file allows me to precompile successfully.

**Comment by sheerun** [comment]
Thanks for reporting this! Will fix soon.

**Comment by seantanly** [comment]
@sheerun Referencing https://github.com/rails-assets/rails-assets/pull/100, does https://github.com/elado/rails-assets/commit/5f12e187b22fb63857fecd08d941ed59631b172a fixes this issue?

**Comment by ai** [comment]
Same issue in fonts URL helper

```
src: url(…)
```

was translated to:

```
src font-url(…)
```

**Comment by sheerun** [comment]
Fixed. If you still encounter error:

If you still encounter error:

```
gem list | grep rails-assets | cut -d ' ' -f 1 | xargs gem uninstall -aIx
bundle install
```
