### ISSUE TITLE
jquery.inputmask is available to bower but not to rails-assets.org

### ISSUE THREAD

**Issue by rosenfeld** [tenex/rails-assets#104]
I get this from bundler:

Could not find gem 'rails-assets-jquery.inputmask (>= 0) ruby' in the gems available on this machine.

Should I change the name of the gem somehow if it contains a dot in the name?

**Comment by sheerun** [comment]
For new gems you need to wait few minutes for reindex. 

We had to turn off on-fly reindex because rubygems is f*ing slow :( Please try now if it works.

**Comment by rosenfeld** [comment]
Thank you, it worked now. It would be good to explain about this in the main web page.

**Comment by sheerun** [comment]
Yeah, we mentioned it in components list & new component pages. We could do it on main too. @porada ?

**Comment by rosenfeld** [comment]
Ah, I just noticed the component list link :) I was previously searching the bower index only since I didn't notice that link in the main page :)
