### ISSUE TITLE
Unsure how to migrate component to new fork

### ISSUE THREAD

**Issue by lawso017** [tenex/rails-assets#105]
Hi there -- would like to include bootstrap3-wysihtml5-bower via rails-assets, however the package:
https://rails-assets.org/#/components/bootstrap3-wysihtml5-bower

references an obsolete fork:
https://github.com/Waxolunist/bootstrap3-wysihtml5-bower

Is there a way to redirect rails-assets to the currently maintained fork here?
https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg

Thanks!

**Comment by hut8** [comment]
Indeed there is! Simply adding the namespaced fork (i.e., `bootstrap-wysiwyg/bootstrap3-wysiwyg`) *should* work, however I just tried that and am encountering an unexpected error. I'll keep you updated as I debug this.

**Comment by hut8** [comment]
There's a bug in [bootstrap3-wysiwyg's documentation](https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg#installation). They say to install `bootstrap3-wysihtml5-bower` from Bower, but clearly on [the bower package repository](http://bower.io/search/?q=bootstrap3-wysihtml5-bower), that links to the old fork.

After [incompletely typing the search](http://bower.io/search/?q=bootstrap3-wysiwyg), it looks like Bower already has that fork packaged by the name `bootstrap3-wysiwyg`. Not sure what's going on there; looks like pull requests aren't being merged as is promised in the README: https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg/pull/141


https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg

**Comment by hut8** [comment]
@lawso017 I'll be closing this tomorrow unless you have further questions.

**Comment by lawso017** [comment]
Thanks, Liam. That makes sense and appreciate your followup. Thanks for
your efforts in supporting this tremendously useful platform.

On Sun, May 15, 2016 at 3:05 PM, Liam <notifications@github.com> wrote:

> @lawso017 <https://github.com/lawso017> I'll be closing this tomorrow
> unless you have further questions.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/tenex/rails-assets/issues/105#issuecomment-219304157>
>



-- 
William (B.J.) Lawson, MD
919.335.3107 (direct)
