### ISSUE TITLE
rails-assets says jquery.layout has no versions but it seems to have

### ISSUE THREAD

**Issue by rosenfeld** [tenex/rails-assets#105]
"jquery.layout has no versions defined. Please create an issue in component's repository."

https://github.com/jlbfalcao/jquery.layout/blob/master/bower.json#L3

I don't quite understand the issue, would you mind to further explain it?

**Comment by sheerun** [comment]
Bower reads versions from tags on GitHub. Version in bower.json actually doesn't much matter.

https://github.com/jlbfalcao/jquery.layout/releases

The only release in jquery.layout is non-semver one, and bower doesn't accept such versions.

Is it clear now?

**Comment by rosenfeld** [comment]
Sure, thank you!

**Comment by rosenfeld** [comment]
Just to be sure: http://semver.org/spec/v2.0.0.html
Is the problem the fact that it's not a proper hyphen in the version? I mean, would the version below be valid?

"1.3.0-rc30.79"

I'd like to know what exactly to ask to the repo maintainer...

**Comment by sheerun** [comment]
Hmm. Actually this is correct semver, but prerelease one. Rails Assets doesn't accept prerelease versions. The issue with jquery.layout is each version should have corresponding semver tag on GitHub (x.y.z)

**Comment by rosenfeld** [comment]
But this is a problem in the case of jQuery layout as it seems it won't release any non-pre release for a long time and the last stable release is not compatible with newer jQuery... Could this requirement be changed on the rails-assets side?

**Comment by rosenfeld** [comment]
http://layout.jquery-dev.net/downloads.cfm

"Despite being a 'release candidate', the 1.3.0 RC version is more bug-free and robust than 1.2.0. Plus it has many new options and features."

This message has been there forever... Unfortunately there's no official repository for this useful plugin and the repo above is just an attempt to integrate it to bower. It would be very helpful for us to be able to use it through bower without having to create fake official non-pre releases...

**Comment by sheerun** [comment]
@rosenfeld From www we allow for compiling even prerelease versions: https://rails-assets.org/components/new You just need to specify component name and existing bower version.

Observe that bower returns no versions for this component:

```
bower info jquery.layout
bower jquery.layout#*           cached git://github.com/jlbfalcao/jquery.layout.git#ab39ea2748
bower jquery.layout#*         validate ab39ea2748 against git://github.com/jlbfalcao/jquery.layout.git#*

{
  name: 'jquery.layout',
  authors: [
    'Fabrizio Balliano',
    'Kevin Dalman'
  ],
  main: [
    'dist/jquery.layout-latest.js',
    'dist/layout-default-latest.css'
  ],
  description: 'UI Layout – The Ultimate Page Layout Manager',
  license: 'GPL and MIT',
  homepage: 'http://layout.jquery-dev.net/index.cfm',
  dependencies: {
    'jquery-ui': '*',
    jquery: '*'
  },
  ignore: [
    'README.md'
  ]
}

No versions available.
```

It's probably bower issue it doesn't accept this git tag.

In general we allow for compilation of any version returned from `bower info <component>`, so if you'll find a way to make `1.3.0–rc30.79` be listed there, Rails Assets should just work.

I think you should hit bower with this version issue or create fork with proper version tag by yourself.

**Comment by rosenfeld** [comment]
Thank you. I'll investigate if this is just a character issue with the hyphen and see what we can do.
