### ISSUE TITLE
components.json not being updated on production

### ISSUE THREAD

**Issue by hut8** [tenex/rails-assets#106]
Not sure why, but the components.json file isn't being deleted as it should be via the `PageCacheManager.expire_page` call. This causes old versions to be displayed as the "latest" on the frontend.

**Comment by hut8** [comment]
I just realized why; `expire_page` just ends up deleting the symlink, and the original file stays intact :-1:

**Comment by joshjordan** [comment]
Can we use a hardlink here?

**Comment by hut8** [comment]
When you delete a hardlink, it just decrements the hardlink count of that inode. It's not until it hits zero that it actually removes the file. I'm almost done with a PR, I just have to make sure that the worker doesn't try to precompile the assets during deployment.
