### ISSUE TITLE
Any reasons why jQuery 1.11.0 is not converted to a gem?

### ISSUE THREAD

**Issue by rosenfeld** [tenex/rails-assets#106]
Also, Rails comes with the jquery-rails gem by default, which provides jquery-ujs.

When I add some bower gem that depends on jquery, is there any way I could tell sprockets to use jquery from the jquery-rails gem instead of the rails-assets-jquery gem that is installed automatically as a dependency?

I need to support IE8 but latest version of jQuery (branch 2.x) does not support it and it's installed by default when you ask for another bower gem that depends on jQuery. Is there anyway I could ignore it and use the version from jquery-rails gem?

**Comment by seantanly** [comment]
Seems like rails-assets-jquery 1.11.0 is not the only gem affected.

I'm having similar issues on rails-assets not picking up the latest version of angular, version 1.2.10.

**Comment by sheerun** [comment]
Hi guys,

I scheduled rebuild of all failed builds and those components + around 50 other versions are now available.

I'm hoping this issue to be solved by #108 and better policy about re-builds.
