### ISSUE TITLE
Any reasons why placeholder-shim is not converted to a gem?

### ISSUE THREAD

**Issue by rosenfeld** [tenex/rails-assets#107]
The UI says a gem was converted and will be available soon but it isn't after a long time waiting. It would be great if the UI would tell us if there are any issues with the conversion instead of issuing a false statement.

bower info placeholder-shim
bower not-cached    git://github.com/peteboere/placeholder-shim.git#*
bower resolve       git://github.com/peteboere/placeholder-shim.git#*
bower download      https://github.com/peteboere/placeholder-shim/archive/v0.6.0.tar.gz
bower extract       placeholder-shim#\* archive.tar.gz
bower resolved      git://github.com/peteboere/placeholder-shim.git#0.6.0

{
  version: '0.6.0',
  name: 'placeholder-shim',
  description: 'Lightweight HTML5 placeholder shim',
  license: 'MIT',
  authors: [
    'Pete Boere pete@the-echoplex.net'
  ],
  dependencies: {
    jquery: '>= 1.5'
  },
  homepage: 'https://github.com/peteboere/placeholder-shim'
}

Available versions:
- 0.6.0
- 0.5.1
- 0.5.0

So, it seems the versions are recognized by bower. Do rails-assets require the tags in GitHub to follow semver? I'm asking because the tags in GH for this project is like "vX.Y.Z" (notice the prepended "v").

I'm not sure about the rules for the conversion to be successful so I don't know exactly what kind of action to request to the library maintainers...

Could you please help me describing what exactly does a repository need to have so that the integration with bower and rails-assets will succeed?

**Comment by rosenfeld** [comment]
Nevermind, it's now listed in the components list... I just never know when it will complete successfully or not...

**Comment by sheerun** [comment]
You're absolutely right. We need "pending builds" and "failed builds" pages.
