### ISSUE TITLE
Add pending builds and failed builds page

### ISSUE THREAD

**Issue by sheerun** [tenex/rails-assets#108]
Currently it's hard to know if build succeeded #107

**Comment by sheerun** [comment]
https://rails-assets.org/status ping @rosenfeld @seantan

**Comment by rosenfeld** [comment]
Great! Thank you, Adam! Good job! :+1:

**Comment by seantanly** [comment]
@sheerun Thanks, I'm picking up the latest versions for jquery and angular now. :)
