### ISSUE TITLE
Fails to use Git tags with prerelease names (eg, 1.2.3.alpha)

### ISSUE THREAD

**Issue by Peeja** [tenex/rails-assets#110]
I have a fork I'd like to use, with a tagged version: https://github.com/Peeja/bower-angular-mocks/tree/v1.2.5.hotfix

I put this in my Gemfile:

``` ruby
gem 'rails-assets-Peeja--bower-angular-mocks', '1.2.5.hotfix'
```

That appears to have triggered a build of `Peeja--bower-angular-mocks 1.2.5`. I tried pulling down the resulting gem, and found it had in fact used the `v1.2.5` tag from the repo.

I tried forcing a build at https://rails-assets.org/components/new, giving it `Peeja--bower-angular-mocks` and `v1.2.5.hotfix`. It told me "Peeja/bower-angular-mocks has no versions defined. Please create an issue in component's repository." I'm not sure what that means. [It looks like it has a version to me](https://github.com/Peeja/bower-angular-mocks/blob/v1.2.5.hotfix/bower.json).

**Comment by Peeja** [comment]
Looks like using `v1.2.5.2` has the same issues.

**Comment by sheerun** [comment]
`v1.2.5.hotfix` is not a semver. `v1.2.5-hotfix` would be probably ok.

**Comment by sheerun** [comment]
`1.2.5.2` is not a semver too. Please always check if your version is accounted in `bower info`

**Comment by Peeja** [comment]
That's news to me. [Rubygems' documentation describes prerelease versions as being in the form `1.2.5.hotfix`](http://guides.rubygems.org/patterns/#prerelease_gems).

But you're right, [according to semver.org](http://semver.org/):

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version.

All that said, we had the same trouble getting `v1.2.5-hotfix` to work as well. I'll see if I can reproduce it.
