### ISSUE TITLE
Problems with tpl.min.js extensions in angular-strap

### ISSUE THREAD

**Issue by chaizhenhua** [tenex/rails-assets#113]
Hello, I got this error when use `rails-assets-angular-strap` gem. it seems that rails can not process tpl.js file. 

```
ActionView::Template::Error (angular-strap/angular-strap.tpl.min is 'application/vnd.groove-tool-template', not 'application/javascript'
  (in .rvm/gems/ruby-2.0.0-p247/gems/rails-assets-angular-strap-2.0.0.rc.1/vendor/assets/javascripts/angular-strap.js:2)):
     9: 
    10:     div[ng-view]
    11:     = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    12:     = javascript_include_tag "application", "data-turbolinks-track" => true
    13:     = csrf_meta_tags
  app/views/layouts/application.html.slim:12:in `_app_views_layouts_application_html_slim__1233721764101893297_70299223006000'
```

**Comment by sheerun** [comment]
This is either sprockets or angular-strap issue.

In sprockets if file is names `foo.js.coffee` it means it's `js` type.

The same way for sprockets `angular-strap.tpl.min.js` is of `tpl` type, not `js`.

Have you resolved it in some way?

**Comment by chaizhenhua** [comment]
No. I havent solve it. I just split angular js part to another project use yeoman and bower.

**Comment by asgeo1** [comment]
Having same issue. Although I'm loading the `angular-strap` repo via `bower-rails` gem.

Is there a way to tell sprockets no to process the `.tpl` part?  I.e. in the same way it knows not to process the ".min" part of a filename.

As a workaround for now, I just copied the `angular-strap.tpl.js` file into my assets directory and renamed it to `angular-strap-tpl.js`

**Comment by mike-park** [comment]
You could create an initializer to override the default mime type for .tpl. This fixes the problem.

config/initializers/angular_strap.rb

``` ruby
# rails-assets-angular-strap references angular-strap/angular-strap.tpl.min 
# which is interpreted as a .tpl file by sprockets. 
# Ensure .tpl has the expected mime-type
Rack::Mime::MIME_TYPES.merge!(".tpl" => "application/javascript")
```

**Comment by sheerun** [comment]
Temporary solution:

```
#= require angular-strap/angular-strap.js
#= require angular-strap/angular-strap.tpl.js
```

**Comment by sheerun** [comment]
I think we can use full paths in manifest to prevent such issues.

**Comment by aj0strow** [comment]
@mike-park thank you

**Comment by sheerun** [comment]
It should be fixed. You need to wait for deploy and rebuild. I'll notify about that on our twitter account.
