### ISSUE TITLE
Is rails-assets fully automated?

### ISSUE THREAD

**Issue by ssaunier** [tenex/rails-assets#116]
Hello,

First of all, thanks for this project! I have a hard time figuring out which bower packages are available through rails-assets (is it all of them?).

I am trying to use https://github.com/clementoriol/MetroDNA which installs correctly with `bower install MetroDNA` but fails with each try:

``` ruby
gem "rails-assets-MetroDNA"
gem "rails-assets-metrodna"
gem "rails-assets-metro-dna"
gem "rails-assets-metro_dna"
```

Am I missing something? Thanks!

**Comment by sheerun** [comment]
MetroDNA has no releases: https://github.com/clementoriol/MetroDNA/releases

RailsAssets compiles only versions available from bower info MetroDNA, and bower uses git tags for retrieveing release versions.

Please open PR on MetroDNA to add new version tags.

You can find all failed builds and reasons behind them on: http://rails-assets.org/status

**Comment by ssaunier** [comment]
Hi @sheerun,

Thanks for the quick reply. I was not aware of this git tag workflow. I will bug @clementoriol

**Comment by ssaunier** [comment]
Hi @sheerun,

@clementoriol has created a release: https://github.com/clementoriol/MetroDNA/releases, is there something else to do? `gem install rails-assets-metrodna` still yields:

```
ERROR:  Could not find a valid gem 'rails-assets-metrodna' (>= 0) in any repository
```

**Comment by sheerun** [comment]
1.0 is not a semver. Bower accepts only semver. @clementoriol needs to add 1.0.0 version.

In general as soon `bower info MetroDNA` returns something else than "No versions available" you should be good.

**Comment by sheerun** [comment]
Also it would be nice to update bower.json with version other than 0.0.0

**Comment by clementoriol** [comment]
Done. :)

**Comment by sheerun** [comment]
Thanks. @clementoriol just fyi usually you add unminified files to "main" entry in bower.json. Build tool like Sprockets or Grunt handles minification.

**Comment by clementoriol** [comment]
Thanks Adam, I'll change this. Have a nice day !

**Comment by ssaunier** [comment]
`gem "rails-assets-MetroDNA"` is now working, thanks guys! :+1:
