### ISSUE TITLE
Extremely LONG "Fetching source index"

### ISSUE THREAD

**Issue by dmilith** [tenex/rails-assets#117]
Yesterday I tried, after 27 minutes (sic!) it finally did that fetch.

It's all invoked from heroku buildpacks and looks standard like this:
http://s.verknowsys.com/ca5f051a95a9cebb5a19c80b5aa969a9c2889998.png

I'm still waiting (since 13:42:20) while writing this issue..

**Comment by dmilith** [comment]
After ~2 hours I accidentally turn on my vpn network..
I did parallel run, of same app and it lasted ~7-8 minutes.

**Comment by sheerun** [comment]
That's probably because we don't use CDN so if server is un USA, each request takes around 150ms. I cannot do anything about it now. Does it still happen?

**Comment by justinko** [comment]
Can't do anything? I cannot use rails-assets if it takes this long :(

Surely you can find a "sponsor"?

**Comment by sheerun** [comment]
I'm not even sure what's the problem. Server seems responding very quickly.

**Comment by sheerun** [comment]
Longest pings are 150ms from USA (300ms from Australia), which should be acceptable:

http://cloudmonitor.ca.com/en/ping.php?vtt=1397652539&varghost=rails-assets.org&vhost=_&vaction=ping&ping=start

**Comment by justinko** [comment]
Temporary workaround: `bundle package` & `bundle install --local`

**Comment by justinko** [comment]
btw this project is awesome, thank you!

**Comment by justinko** [comment]
Maybe https://packagecloud.io could sponsor?

**Comment by sheerun** [comment]
Thanks! I'll talk to them.

**Comment by jamesgolick** [comment]
@sheerun we'd love to help - what's the issue that needs solving here?
