### ISSUE TITLE
Does rails-assets support local and git based packages?

### ISSUE THREAD

**Issue by chrisnicola** [tenex/rails-assets#118]
Do all assets have to be indexed via rails-assets.org? Can you specify an asset using `github: 'Username/Repo', branch: 'branch-name'` options?

Alternatively can you specify a local file using `file: 'path'` syntax?

**Comment by sheerun** [comment]
Yes, they need to be indexed. `branch`, and `file` are not possible. I'm open for solutions.

**Comment by sheerun** [comment]
We're working on new solution (#121) that is going to support `branch` and `path`
