### ISSUE TITLE
jquery-popupwindow has main in it's bower.json

### ISSUE THREAD

**Issue by hadees** [tenex/rails-assets#120]
The bower package [`jquery-popupwindow`](https://github.com/mkdynamic/jquery-popupwindow) has `"main": "jquery.popupwindow.js"` in it's [bower.json](https://github.com/mkdynamic/jquery-popupwindow/blob/master/bower.json) file yet I still go the error `This component doesn't define main assets in bower.json`.  Is it not defined correctly? I'm not sure whats going on here.

**Comment by sheerun** [comment]
There was no release since `bower.json` has been added.

Here is how 1.0.0 looks like:
https://github.com/mkdynamic/jquery-popupwindow/tree/6461b613cd76d1fc60f572d5941aa2487e6459bb
