### ISSUE TITLE
Handle versions with ^

### ISSUE THREAD

**Issue by aaronchi** [tenex/rails-assets#126]
Currently not compiling latest masonry because it has started to use versions with ^

There was a Gem::Requirement::BadRequirementError while loading rails-assets-masonry.gemspec: 
Illformed requirement ["^1.2.0"]

**Comment by sheerun** [comment]
Bower community is really creative :)

**Comment by porada** [comment]
@sheerun, I think this was [originated](https://www.npmjs.org/doc/misc/semver.html) by the Node.js community.

**Comment by sheerun** [comment]
I've added support for this kind of versions 060ea964d

Enjoy
