### ISSUE TITLE
Why not use bower version replace tag release version.

### ISSUE THREAD

**Issue by phuwanart** [tenex/rails-assets#127]
For converting package I guess you use version number from release tag of package repository. Why not use version from bower package because you use bower package name for rails assets gem name.

**Comment by sheerun** [comment]
Bower uses tag names from Git repositories.

We use output of `bower info` command. If you see version there, we compile it (not prereleases).

**Comment by phuwanart** [comment]
OK, I understand. I checked the commend `bower info bootflatv2` it no versions available.

I had issue to owner that repository.

I appreciate your answer. :)
