### ISSUE TITLE
Non-Rails Sprockets support

### ISSUE THREAD

**Issue by ai** [tenex/rails-assets#128]
I use a lot of Rakefile site generators (like for [easings.net](http://easings.net/)) and use Sprockets there. Because this Sprockets is without Rails, nobody add Engine’s path to Sprockets paths. To help me I add `install` method to my gems:

``` ruby
Sprockets::Environment.new(ROOT) do |env|
  EvilBlocks.install(env)
end
```

Install method is very simple, just:

``` ruby
module EvilBlocks
  def self.install(sprockets)
    Pathname(__FILE__).join('../vendor/assets').each_child do |dir|
      sprockets.append_path(dir)
    end
  end

  if defined? ::Rails
    class Engine < ::Rails::Engine
      # Rails -> use vendor directory.
    end
  end
end
```

**Comment by ai** [comment]
@sheerun I can send PR if you agree with this API.

**Comment by sheerun** [comment]
Wouldn't it be better to just always use sprockets.append_path, and skip even .install step?

Also, I need to be very sure it won't break existing installations :(

**Comment by sheerun** [comment]
Just FYI I'm not sprocket's expert :-) If it's necessary to make sprockets instance before appending paths then I guess `.install` method is OK, but I'd like to make it "global".

What I mean, just one `.install` call for all assets in Gemfile.

**Comment by ai** [comment]
> I guess .install method is OK, but I'd like to make it "global".

Nope, every Sprockets env has own load paths array. So `install` will add gem’s assets only to current Sprockets.

**Comment by ai** [comment]
> Wouldn't it be better to just always use sprockets.append_path, and skip even .install step?

It is very difficult to get gem path from app. Or not difficult, but dirty. I use this preset:

``` ruby
def add_gem_assets(env, gem)
  path = Gem::Specification.find_by_name(gem).gem_dir
  path = Pathname(path).join('vendor/assets')
  path.each_child { |path| env.append_path(path) }
end
```

**Comment by sheerun** [comment]
What I mean:

``` ruby
Sprockets::Environment.new(ROOT) do |env|
  RailsAssets.install(env)
end
```

The code above would append all the paths of RailsAssets components specified in Gemfile.

**Comment by ai** [comment]
I mean separated `install` in every gem:

``` ruby
Sprockets::Environment.new(ROOT) do |env|
  Angular.install(env)
end
```

But maybe your way is better.

**Comment by sheerun** [comment]
I think there are two ways to achieve it:
1. Use global array like `$rails_assets_paths` and let each gem append its path when required. `.install` method would iterate this array and append paths to sprockets environment.
2. In `.install` method somehow iterate all gems loaded by bundler (is it possible?), extract those that begin with "rails-assets" and append appropriate paths to `env`.

I'm not sure which is better, or even if they are possible.

**Comment by ai** [comment]
I think this issue can wait. #100 is more important. Let’s it will be like idea, there is dirty solution right now (instead of #100, which block to use a lot of CSS from Bower).

**Comment by sheerun** [comment]
Hmm. OK. I guess #100 is the only serious bug with RailsAssets now, so it's good to fix it first.

**Comment by sheerun** [comment]
@ai If you have any problems with RA development, please join this chat: https://www.hipchat.com/gHM5ann24

**Comment by ai** [comment]
@sheerun thanks, you development process is really helpful :)

**Comment by sheerun** [comment]
@ai Here is my current proposal. Any comments?

```
require "<%= gem.name %>/version"

<% gem.dependencies.each do |dep_name, _| %>
require <%= dep_name.dump %>
<% end %>

module <%= gem.module %>

  def self.gem_path
    Pathname(__FILE__).join('../..')
  end

  def self.gem_spec
    Gem::Specification::load(
      gem_path.join(<%= (gem.name + ".gemspec").dump %>).to_s
    )
  end

  def self.load_paths
    gem_path.join('app/assets').each_child.to_a
  end

  if defined?(Rails)
    class Engine < ::Rails::Engine
      # Rails -> use app/assets directory.
    end
  end

end

class RailsAssets
  @components ||= []

  class << self
    attr_accessor :components

    def load_paths
      components.flat_map(&:load_paths)
    end
  end
end

RailsAssets.components << <%= gem.module %>
```

**Comment by ai** [comment]
Yeap, nice too :-)

**Comment by sheerun** [comment]
I added another method:

```
  def self.dependencies
    [
      <%= gem.dependencies.to_a.map(&:first).map do |dep|
        Build::GemComponent.name_to_module(dep.to_s)
      end.join(",\n      ") %>
    ]
  end
```

I think I'll commit.
