### ISSUE TITLE
Error adding AngularJS-Toaster

### ISSUE THREAD

**Issue by Nitrino** [tenex/rails-assets#131]
I can't add a library [AngularJS-Toaster](https://github.com/jirikavi/AngularJS-Toaster). Error's text: "Our administrator has been notified about this event."

**Comment by sheerun** [comment]
We had this error: http://robots.thoughtbot.com/fight-back-utf-8-invalid-byte-sequences

It should work now.

**Comment by Nitrino** [comment]
Thanks for the quick help.
