### ISSUE TITLE
How to handle assets conflict (bootstrap)

### ISSUE THREAD

**Issue by shir** [tenex/rails-assets#132]
I use `bootstrap-sass` gem because I like to use variable and mixins form it:

``` ruby
gem 'bootstrap-sass'
```

 I've installed `bootstrap-multiselect` library form rails-assets:

``` ruby
gem 'rails-assets-bootstrap-multiselect'`
```

But bootstrap-multiselect depends on `rails-assets-bootstrap` and it has been installed by dependency. Now, when I include bootstrap in my sass file

``` sass
@import "bootstrap";
```

version from `rails-assets-bootstrap` gem is included which is not sass version and doesn't have any variables and mixins.

How can I handle this conflict and load bootstrap version from `bootstrap-sass` gem?

**Comment by sheerun** [comment]
Did you try `@import "bootstrap-sass";` instead `@import "bootstrap";`?

**Comment by shir** [comment]
@sheerun I don't think it will work because both libraries have only file `bootrsrap.scss` (in rails-assets version actually has css version but with `scss` extension)

**Comment by sheerun** [comment]
That's because you mix rails-assets and non-rails-assets components.

Use `rails-assets-bootstrap-sass` and `@import "bootstrap-sass";`

**Comment by shir** [comment]
@sheerun this library doesn't have mixins and variables. Only compiled css file.

**Comment by sheerun** [comment]
Oh. It turns out bower's `bootstrap-sass` points to `jlong/sass-twitter-bootstrap`, not an official repository. You can click on version number on https://rails-assets.org/components to see available files.

You'd need to use one of the following:
- `rails-assets-bootstrap-sass-official` and `require bootstrap-sass-official`
- `rails-assets-twbs--bootstrap-sass` and `require bootstrap-sass`

**Comment by shir** [comment]
@sheerun May be I don't understand something but looks like both of this libraries are not working (may be it's only on rails 4.1?). When I try to use any of this libraries, then I got error that file `bootstrap/affix.js` can't be found. I think it's because in `bootstrap.js` files are required as `bootstrap/affix.js`, but not like `bootstrap-sass-official/bootstrap/affix.js`

**Comment by sheerun** [comment]
This may be a bug. Let me try to make a demo app or fix it.

**Comment by MichaelSp** [comment]
@shir this seems to be a known bug https://github.com/rails-assets/rails-assets/issues/136

**Comment by jdurand** [comment]
It would be nice to have a way to include a Rails Asset without its dependencies.
For instance, I'm using `ember-rails` (from rubygems) which includes the supported versions of `ember.js` and friends. Now I want to use `rails-assets-ember-hammer` without `rails-assets-ember`, `rails-assets-handlebars`, `rails-assets-jquery` and manually add the required `rails-assets-hammerjs`.
This would solve the OPs issue.

I'm, wondering if this is more of a bundler issue though... or if this is an issue at all.

The real issue here is that bundling gems from 2 different source trees can and will create ambiguity.

**Comment by sheerun** [comment]
@shir I answered your issue in #136

**Comment by poteto** [comment]
+1 for having a way to include a `rails-asset` without its dependencies

**Comment by pjanik** [comment]
+1

In my case I have bower package that depends on jQuery. You can imagine that at the same time many other gems also depend on "traditional" jquery-rails gem. Both rail-assets jQuery and jquery-rails library can be included using the same `//= require jquery`. So which one would be included finally?

I think it may be popular scenario. Not sure if package without dependencies is the best solution. Other could to require rails-assets explicitly like `//=require rails-assets-jquery` so there is no conflict.

**Comment by sheerun** [comment]
@pjanik Maybe `gem 'rails-assets-jquery', require: false` will help.

**Comment by rosskevin** [comment]
@sheerun I have the same problem as @pjanik, though I'm trying to bring in `add_dependency 'rails-assets-jquery.easing'` through a gemspec file.  `:require` false, while I've never used it so don't claim familiarity, doesn't work in a gemspec.  I'm not sure which solution is better, but I find that we are gravitating towards bower packages much more than rails gems on the front end (though not totally away from them).

**Comment by sheerun** [comment]
I don't think it's a good idea to use rails-assets in gems.

**Comment by rosskevin** [comment]
@sheerun I'm curious, if it isn't a good idea to use in gems, then why would it be a good idea to use in a rails app?  What is the basis for your comment?

**Comment by sheerun** [comment]
By using Rails Assets in gem you are forcing users of this gem to use Rails Assets, what is not desired by some companies (you need to trust both Ruby Gems and us). Coupling gem with 2 providers isn't fine.

Using Rails Assets in own application is fine because you make a deliberate choice to.

**Comment by rosskevin** [comment]
Thank you.  This happens to be private so there are a number of assumptions in use of it and it isn't an issue.

Even if it were public, I'd argue that it is the choice of the gem author, and if gem users are hung up on it, they can choose something else.

**Comment by sheerun** [comment]
I don't see anything wrong with using RA in private gem.

You can always do:

```
gem 'rails-assets-something', require: false
```

even if the `rails-assets-something` is dependency of your private gem.

Using bower components directly is fine too. Just little harder to setup and deploy properly.

**Comment by vinc** [comment]
I'm using the gem `bootstrap-sass` and I want to use `rails-assets-seiyria-bootstrap-slider` but it depends on `rails-assets-bootstrap` resulting on:

```
Sass::SyntaxError at /
File to import not found or unreadable: bootstrap/less/bootstrap.
```

I tried various things with `rails-assets-bootstrap`, `rails-assets-bootstrap-sass` and `rails-assets-bootstrap-sass-official` without much luck.

**Comment by sheerun** [comment]
please use `bootstrap-sass` gem instead (not `rails-assets-bootstrap`)

**Comment by vinc** [comment]
That's what I'm using, the latter is only required by `rails-assets-seiyria-bootstrap-slider` which is the problem.

**Comment by sheerun** [comment]
then do:

```
gem 'rails-assets-bootstrap', require: false
```

**Comment by vinc** [comment]
But then I end up with:

```
Sprockets::FileNotFound at /
couldn't find file 'seiyria-bootstrap-slider'
```

I switched to using `bower-rails` instead on my project (https://github.com/vinc/cities.vinc.cc/commit/9ee01689b298a8c60d85bfafda1116486c7d1071) but I would prefer to avoid it.

**Comment by sheerun** [comment]
I edited my previous comment.

**Comment by vinc** [comment]
Oh, that I hadn't tried, but I still get the first `Sass::SyntaxError`.

**Comment by sheerun** [comment]
I can't help then.

You need to make sure all bootstrap gems except `bootstrap-sass` have `require: false`

**Comment by vinc** [comment]
Thank you for your time! I'll report back if I find something new about this issue.

**Comment by jb41** [comment]
@vinc you have to add initializer to /app/initializers with:

```
Rails.configuration.assets.paths = Rails.configuration.assets.paths.reject do |path|
  path.to_s.include?('rails-assets-bootstrap')
end
```

and `gem 'rails-assets-bootstrap', require: false` to you Gemfile.

**Comment by bopm** [comment]
:+1:

**Comment by sheerun** [comment]
Actually `gem 'rails-assets-bootstrap', require: false` is not needed. It turns out it will be loaded anyway if it's a dependency of some other module. Initializer is enough. You probably can use `reject!`.

**Comment by skuridin** [comment]
How about `rails-assets-jquery` and `rails-assets-jquery-form`?
reject! `rails-assets-jquery` will reject `rails-assets-jquery-form` too.

I can reject gem by adding version `rails-assets-jquery-2.1.1` but it's so awry.

**Comment by rdsubhas** [comment]
Just ran into the same problem. I wish there would be a way to disable dependency resolution and _prevent_ rails-assets-bootstrap (or any other forms of it) from being installed in the first place. Reasons being:
- Many popular libraries (like jquery, jquery_ujs, bootstrap, foundation, etc) **directly provide** Rails gems which work far better than downloading through bower or rails-assets. But unfortunately when using rails-assets, some obscure bower dependency messes up the built-in jquery or something else (in this case bootstrap).
- Even if these dependencies are automatically resolved and installed by rails-assets, they anyways have to be manually added to `application.css/js`. If we say `*= require xyz` all its dependencies are _not_ automatically loaded. Anyways the developer has to be manually aware of the dependencies and should be including it `application.css/js`. So not a big deal to let the developer add dependencies manually to the Gemfile as well.
- Some bower dependencies are subtly broken. There are multiple variants of the same package (bootstrap vs bootstrap-less vs bootstrap-sass vs bootstrap-sass-official). So if `bootstrap-multiselect` says it depends on `bootstrap >= 3.0`, its wrong. In reality, it depends on whether the developer is using Sass or Less or plain CSS in their project.
- (Minor) all these unnecessary dependencies add more bloat. At least preventing unnecessary dependencies would be better. Hacks like `gem rails-assets-bootstrap, require: false` somehow seem wrong.

I think disabling dependency resolution and letting people pick what they want to install is better. @sheerun what do you think?

EDIT: Another option to prevent rails-assets dependencies from gobbling up the general namespace might be to nest them all under a prefix, like `//= require rails-assets/bootstrap-datepicker/...`

**Comment by sheerun** [comment]
This is a tough decision. Lack of dependencies could break a lot of current installations. For example if one specified:

```
gem 'angular'
gem 'angular-something'
```

And 2 months later angular got updated to 2.0 while angular-something still depends on 1.2, bundle update would break whole application. The only way we could drop dependencies is to make semver specifications in Gemfile mandatory. We can't enforce that. It probably won't happen.

Dropping manifest in global namespace would break all existing installations, so no :(

I planned to release `rails_assets` gem that would bypass https://rails-assets.org entirely (download components directly from github), and use Bowerfile instead Gemfile. We could mandate versions in Bowerfile and optionally show dependency suggestions during installation. I did some plans, but ultimately it never happened (lack of time and money): https://github.com/bowered/bowered/issues

So the answer is: We can't do it for current service. Maybe we can if we release CLI utility. For now you can use following in initializer:

```
Rails.configuration.assets.paths.reject! do |path|
  path.include?('rails-assets-bootstrap')
end
```
