### ISSUE TITLE
Meet an error while converting my build

### ISSUE THREAD

**Issue by fr0m** [tenex/rails-assets#133]
this is the error message below when I tried to convert my build background.js

```
background.js#0.1.3: /usr/local/rvm/rubies/ruby-2.0.0-p451/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
    from /usr/local/rvm/rubies/ruby-2.0.0-p451/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

I just update the version name in v0.1.3, how can I fix it?

**Comment by sheerun** [comment]
It worked for me from www interface https://rails-assets.org/components/new

**Comment by fr0m** [comment]
it's weird, I tried so many times and it didnt work yesterday, but now it works for me too. 
anyway, problem solved, thank u.
