### ISSUE TITLE
Asset dependency with Bootstrap

### ISSUE THREAD

**Issue by dwightwatson** [tenex/rails-assets#135]
Maybe I'm just totally clueless here, but I'm having an issue with using the Bootstrap gem. This is the error I get when trying to include the Bootstrap CSS in my application.

```
Asset depends on 'bootstrap/glyphicons-halflings-regular.eot' to generate properly but has not declared the dependency
Please add: `//= depend_on_asset "bootstrap/glyphicons-halflings-regular.eot"` to '/Users/Dwight/.rvm/gems/ruby-2.0.0-p247/gems/rails-assets-bootstrap-3.1.1/vendor/assets/stylesheets/bootstrap.scss'
```

  (in /Users/Dwight/.rvm/gems/ruby-2.0.0-p247/gems/rails-assets-bootstrap-3.1.1/vendor/assets/stylesheets/bootstrap.scss)

In my Gemfile:

```
gem 'rails-assets-bootstrap', '~> 3.1.1'
```

In my `application.css`:

```
*= require bootstrap
*= require_tree .
*= require_self
```

**Comment by sheerun** [comment]
That's interesting. What rails/sprockets versions are you using?

**Comment by sheerun** [comment]
Do you use "sprockets_better_errors" ?

**Comment by dwightwatson** [comment]
It appears I have Sprockets 2.11.0 and am running Rails 4.1.0 (fresh install). I don't use the better errors gem but I can give it a whirl?

**Comment by sheerun** [comment]
Nope, I was just wondering what causes the issue.

**Comment by dwightwatson** [comment]
Bizarre, after installing `sprockets_better_errors` it started working and once I removed that gem it continued to work. Not sure what happened but at least it's working now! Thanks :smile:
