### ISSUE TITLE
rails-assets-bootstrap-sass-official 3.11, javascript not work

### ISSUE THREAD

**Issue by wafcio** [tenex/rails-assets#136]
when I past

<pre>//= require "bootstrap-sass-official"</pre>

in my application.js file then I get:

<pre>couldn't find file 'bootstrap/affix'</pre>

but it works with

<pre>//= require bootstrap-sass-official/bootstrap/affix
//= require bootstrap-sass-official/bootstrap/alert
//= require bootstrap-sass-official/bootstrap/button
//= require bootstrap-sass-official/bootstrap/carousel
//= require bootstrap-sass-official/bootstrap/collapse
//= require bootstrap-sass-official/bootstrap/dropdown
//= require bootstrap-sass-official/bootstrap/tab
//= require bootstrap-sass-official/bootstrap/transition
//= require bootstrap-sass-official/bootstrap/scrollspy
//= require bootstrap-sass-official/bootstrap/modal
//= require bootstrap-sass-official/bootstrap/tooltip
//= require bootstrap-sass-official/bootstrap/popover</pre>

**Comment by sheerun** [comment]
Which version of bootstrap-sass-official is in your Gemfile.lock ?

**Comment by stefanvermaas** [comment]
I can confirm this. I'm using the latest version of bootstrap-sass-official: 

``` ruby
rails-assets-bootstrap-sass-official (3.1.1)
```

update: The bug is introduced in version 3.0.3.0

**Comment by wafcio** [comment]
I use the latest version

**Comment by MichaelSp** [comment]
same here:
Gemfile
`gem 'rails-assets-bootstrap-sass-official', '3.1.1'`
Gemfile.lock
`rails-assets-bootstrap-sass-official (3.1.1)`

after `bundle update rails-assets-bootstrap-sass-official` and restart
Using rails-assets-bootstrap-sass-official 3.1.1.1 (was 3.1.1)
It seems to work

**Comment by MichaelSp** [comment]
Strange. That version (`rails-assets-bootstrap-sass-official (3.1.1.1)`)  doesn't work any more.
Error: `Undefined variable: "$alert-padding".`

**Comment by pcriv** [comment]
Same error here using bower-rails.

**Comment by sheerun** [comment]
`bootstrap-sass-official` is using custom paths for their dependencies, so this gem is not bower-compatible: https://github.com/twbs/bootstrap-sass/blob/master/lib/bootstrap-sass.rb#L60

This means the only reliable way to use it in rails is:

```
gem 'bootstrap-sass', '~> 3.1.1'
```

I can't fix builds, sorry. Only bootstrap-official can fix this issue by using relative paths (beginning with `./`) in their manifest files:
- https://github.com/twbs/bootstrap-sass/blob/master/vendor/assets/javascripts/bootstrap.js
- https://github.com/twbs/bootstrap-sass/blob/master/vendor/assets/stylesheets/bootstrap.scss
