### ISSUE TITLE
`Could not find gem` error

### ISSUE THREAD

**Issue by frankie-loves-jesus** [tenex/rails-assets#137]
I'm trying to bundle install but am getting:

`Could not find gem 'rails-assets-jquery-mobile (>= 0) ruby' in the gems available on this machine.`

This despite adding `source 'https://rails-assets.org'` and `gem 'rails-assets-jquery-mobile'` to my Gemfile.

Anybody know?

I'm using Rails 4.0.4.

**Comment by sheerun** [comment]
New components are added to build queue at http://rails-assets.org/status

`jquery-mobile` is not available.

**Comment by sheerun** [comment]
not = now

**Comment by frankie-loves-jesus** [comment]
Great. So every time a Rails user attempts to add a new package you guys must first manually add it?

**Comment by sheerun** [comment]
It is added automatically. Build takes some time.

**Comment by frankie-loves-jesus** [comment]
manually = semiautomatically

**Comment by frankie-loves-jesus** [comment]
Ah yeah. Cool.

**Comment by frankie-loves-jesus** [comment]
I have a long list of packages in my Gemfile. When it errors out on the first missing one, it doesn't look like it gets to request that the rest be built as well.

**Comment by sheerun** [comment]
You can add them from www: https://rails-assets.org/components/new

**Comment by frankie-loves-jesus** [comment]
:+1:
