### ISSUE TITLE
Couldn't find file 'jquery-infield-label'

### ISSUE THREAD

**Issue by frankie-loves-jesus** [tenex/rails-assets#138]
I added `gem 'rails-assets-jquery-infield-label'` to my Gemfile and ran `bundle install` with no errors. I then added `//= require jquery-infield-label` to my application.js.

When running Rails, however, I get:

```
ActionView::Template::Error (couldn't find file 'jquery-infield-label'
  (in /home/myapp/app/assets/javascripts/application.js:9)):
    102:
    103:     <%= javascript_include_tag "application" %>
```

Anybody know what to do?

**Comment by sheerun** [comment]
You probably got prominent message during installation that this component doesn't define main file. You can list available files by clicking version name on: https://rails-assets.org/components or just visiting component's github repository.

For this component proper require is probably:

```
//= require jquery-infield-label/src/jquery.infieldlabel.js
```

**Comment by frankie-loves-jesus** [comment]
I can't recall having seen a message. Anyway there's `"main": "./lib/jquery.infieldlabel.js"` in https://github.com/dcneiner/In-Field-Labels-jQuery-Plugin/blob/master/package.json, shouldn't that suffice?

**Comment by sheerun** [comment]
Bower uses bower.json. And we use `bower info`.

**Comment by frankie-loves-jesus** [comment]
I'll ask the author to add one of those. Thanks.

**Comment by frankie-loves-jesus** [comment]
Is it best practice to always specify main file in my JS?

There's one case here where the repo does have a bower.json with the main file specified, yet application.js can't find it unless I specify it manually.

**Comment by sheerun** [comment]
We use `bower info package`. If main file is not listed there, it's bower issue, not ours.

**Comment by sheerun** [comment]
Or more likely package author issue.

**Comment by frankie-loves-jesus** [comment]
Cool. Thanks again!
