### ISSUE TITLE
Snap.svg - can't require through Sprockets

### ISSUE THREAD

**Issue by simonwalsh** [tenex/rails-assets#140]
Hey guys!

I'm using rails-assets to bundle Snap.svg bower component.

In my `gemfile` I've got `gem 'rails-assets-Snap.svg'`. In `application.js`, I've got a `require` call like so `//= require 'Snap.svg'`. As you've guessed it, Rails complains because:

```
Snap.svg is 'image/svg+xml', not 'application/javascript'
```

Is there a way to escape the `.svg` extension or another solution?

**Comment by sheerun** [comment]
I guess you have to manually include main file or hack sprockets some way:

```
//= require Snap.svg/dist/snap.svg-min.js
```

**Comment by sheerun** [comment]
I think this is sprockets issue, you could open issue on their repository.

**Comment by simonwalsh** [comment]
Will do. Thanks!
