### ISSUE TITLE
Problem loading dependencies

### ISSUE THREAD

**Issue by frankie-loves-jesus** [tenex/rails-assets#141]
Hi,

I'm trying to install Packery (http://packery.metafizzy.co/), but it's not going so well.

Gemfile:

```
gem 'rails-assets-packery'
gem 'rails-assets-imagesloaded'
```

application.js:

```
//= require packery
//= require imagesloaded
```

Later I discovered I also had to add these (isn't Rails Assets supposed to handle dependencies automatically?):

```
//= require eventie
//= require doc-ready
//= require eventEmitter
//= require get-style-property
//= require outlayer
```

But still Packery won't function as normal (like it did when I loaded http://packery.metafizzy.co/packery.pkgd.min.js manually). Can anybody tell what's missing? I'm not seeing any errors in my Chrome dev console.

**Comment by sheerun** [comment]
What do you mean it won't function as normal?

**Comment by frankie-loves-jesus** [comment]
None of my Packery items are visible. Hard to tell since there's nothing in the log though.

Should I set up before-and-after demo apps?

**Comment by sheerun** [comment]
Rails Assets doesn't require dependencies automatically.

Here is full dependency tree, maybe you need to require more of them:

```
    rails-assets-classie (1.0.0)
    rails-assets-desandro--doc-ready (1.0.2)
      rails-assets-eventie (>= 1.0.3, < 2.0)
    rails-assets-desandro--get-size (1.1.7)
      rails-assets-desandro--get-style-property (>= 1, < 2)
    rails-assets-desandro--get-style-property (1.0.3)
    rails-assets-desandro--matches-selector (1.0.1)
    rails-assets-eventEmitter (4.2.7)
    rails-assets-eventie (1.0.5)
    rails-assets-jquery-bridget (1.0.1)
    rails-assets-outlayer (1.2.0)
      rails-assets-desandro--doc-ready (>= 1.0.1, < 2.0)
      rails-assets-desandro--get-size (>= 1, < 2)
      rails-assets-desandro--get-style-property (>= 1, < 2)
      rails-assets-desandro--matches-selector (>= 1, < 2)
      rails-assets-eventEmitter (>= 4.2, < 5)
      rails-assets-eventie (>= 1.0.3, < 2.0)
      rails-assets-jquery-bridget (>= 1, < 2)
    rails-assets-packery (1.2.2)
      rails-assets-classie (>= 1, < 2)
      rails-assets-desandro--get-size (>= 1.1, < 2)
      rails-assets-desandro--get-style-property (>= 1, < 2)
      rails-assets-outlayer (>= 1.1.10, < 2)
```

Search for `define(` in http://packery.metafizzy.co/packery.pkgd.js

As for myself, I'd throw packaged version in `vendor/assets/javascripts`.

If you really want this granular, you need to manually figure out requires.

**Comment by frankie-loves-jesus** [comment]
> Rails Assets doesn't require dependencies automatically.

Does Bower? Because if not, I don't understand why the Packery author would add Packery to Bower in the first place.

I tried adding those extra dependencies to `application.js` and whatever packages I could find to the `Gemfile` but still no luck.

> As for myself, I'd throw packaged version in vendor/assets/javascripts.
> 
> If you really want this granular, you need to manually figure out requires.

Maybe it's in these cases one would be better off using Half Pipe (https://github.com/d-i/half-pipe)?

**Comment by frankie-loves-jesus** [comment]
> As for myself, I'd throw packaged version in vendor/assets/javascripts.

I sort of feel this defeats the whole purpose of Rails Assets. There's got to be a better way.

**Comment by sheerun** [comment]
Neither bower does that.

**Comment by frankie-loves-jesus** [comment]
Yeah you're right. Anyhow got some help from the Packery author, managed to solve the problem:

https://github.com/metafizzy/packery/issues/163

Thanks again for all the help.
