### ISSUE TITLE
Unable to install custom jQuery Mobile build

### ISSUE THREAD

**Issue by frankie-loves-jesus** [tenex/rails-assets#143]
Attempting to install a custom jQuery Mobile build (https://github.com/jquery/jquerymobile.com/issues/66):

> If you do `bower install jquery-mobile` you get the repo version of jquery-mobile hence exposing the internal modules. From there you can use only what you need in your project and your build system should pull-in only what's needed of jQuery Mobile.
- Added to Gemfile:

```
gem 'rails-assets-jquery-ui'
gem 'rails-assets-jquery-mobile', '1.4.0'
```
- Went to http://jquerymobile.com/download-builder/ and selected my desired components
- Compared these against https://github.com/jquery/jquery-mobile/tree/master/js
- Added to application.js:

```
//= require jquery-ui
//= require jquery-mobile/js/core
//= require jquery-mobile/js/animationComplete
//= require jquery-mobile/js/data
//= require jquery-mobile/js/defaults
//= require jquery-mobile/js/helpers
//= require jquery-mobile/js/init
//= require jquery-mobile/js/ns
//= require jquery-mobile/js/support
//= require jquery-mobile/js/support/orientation
//= require jquery-mobile/js/support/touch
//= require jquery-mobile/js/vmouse
//= require jquery-mobile/js/widget
//= require jquery-mobile/js/navigation
//= require jquery-mobile/js/events/navigate
//= require jquery-mobile/js/events/orientationchange
//= require jquery-mobile/js/events/throttledresize
//= require jquery-mobile/js/events/touch
//= require jquery-mobile/js/events
//= require jquery-mobile/js/navigation/base
//= require jquery-mobile/js/navigation/history
//= require jquery-mobile/js/navigation/navigator
//= require jquery-mobile/js/navigation/path
//= require jquery-mobile/js/navigation/method
//= require jquery-mobile/js/transitions/transition
//= require jquery-mobile/js/transitions/concurrent
//= require jquery-mobile/js/transitions/handlers
//= require jquery-mobile/js/transitions/serial
//= require jquery-mobile/js/transitions/visual
//= require jquery-mobile/js/transitions/visuals/slide
//= require jquery-mobile/js/media
//= require jquery-mobile/js/zoom
//= require jquery-mobile/js/widget
//= require jquery-mobile/js/widgets/page
//= require jquery-mobile/js/widgets/pagecontainer
//= require jquery-mobile/js/widgets/toolbar
```
- Unfortunately Rails produces the error:

`couldn't find file 'jquery-mobile/js/core'`

I've also run `bundle install` twice as suggested at https://rails-assets.org/components.

Anybody know?

**Comment by sheerun** [comment]
Please use https://github.com/jobrapido/jquery-mobile-bower

You can list files available by clicking on version on
https://rails-assets.org/components

**Comment by frankie-loves-jesus** [comment]
> Please use https://github.com/jobrapido/jquery-mobile-bower

Unfortunately that thing seems pre-built. I'm looking to do a custom build using only the components I need (similar to http://jquerymobile.com/download-builder/).

> You can list files available by clicking on version on https://rails-assets.org/components

Oh cool! I didn't know that!

**Comment by frankie-loves-jesus** [comment]
@sheerun: This whole having to run `bundle install` twice thing, is that likely to be redundant in the future?

**Comment by sheerun** [comment]
At the very beginning there was no need for it. But now the rubygems reindex takes 10 minutes so we can't do it on-the-fly. Double `bundle install` will be always necessary for new components.

**Comment by frankie-loves-jesus** [comment]
Is there anything RubyGems can do to eliminate this problem?

**Comment by sheerun** [comment]
They are already working on new index format that will make reindex tenfold faster.
https://github.com/rubygems/rubygems/issues/454

**Comment by frankie-loves-jesus** [comment]
Cool :)
