### ISSUE TITLE
Can't install ng-ckeditor

### ISSUE THREAD

**Issue by robert-armstrong** [tenex/rails-assets#144]
I'm trying to use ng-ckeditor. But I get the following error:

```
ng-ckeditor has no versions defined. Please create an issue in component's repository.
```

ng-ckeditor appears to have 0.2 defined in github and in the bower config. I'm not sure what's wrong. Is it something simple like a mismatch between 0.2 and 0.2.0?

**Comment by sheerun** [comment]
0.2 is not semver. it should be 0.2.0
