### ISSUE TITLE
Getting 'has no versions defined' even though the app is tagged.

### ISSUE THREAD

**Issue by sbsurf** [tenex/rails-assets#145]
I'm trying to add this component to rails-assets:

https://github.com/gabesmed/ember-leaflet

It has a version:

https://github.com/gabesmed/ember-leaflet/releases

But when I try to add it, I get this:

```
gabesmed/ember-leaflet has no versions defined. Please create an issue in component's repository.
```

Any suggestions?

**Comment by sheerun** [comment]
0.5 is not a semver
