### ISSUE TITLE
bootstrap-formhelpers doesn't work: scss won't include less files!

### ISSUE THREAD

**Issue by jmuheim** [tenex/rails-assets#148]
I tried to add bootstrap-formhelpers asset. But I get the following error:

```
File to import not found or unreadable: bootstrap-formhelpers/bootstrap-formhelpers.
```

It seems that the generated `bootstrap-formhelpers.scss` tries to load `.less` files, but this doesn't seem to work. When renaming the file to a `.less` file itself, it's working.

What to do?

**Comment by sheerun** [comment]
I suggest using files from dist directory: `bootstrap-formhelpers/dist/css/bootstrap-formhelpers`.

You can also ping author to add `main` file entry in bower.json, so it will be fetched instead less version.

I'll leave it open because theoretically if we autodiscover `main` less file, the manifest should be in .less too. Maybe even convert .less to .scss, because .less generally sucks in Rails.

**Comment by jmuheim** [comment]
> I suggest using files from dist directory

How can this be achieved?

> You can also ping author to add main file entry in bower.json

I already have created a PR, but sadly, the maintainer doesn't respond. Is there a way to specify a fork with `rails-assets`?

**Comment by jmuheim** [comment]
https://github.com/winmarkltd/BootstrapFormHelpers/pull/219

**Comment by sheerun** [comment]
Require path I mentioned. rails assets can compile any fork on GitHub from
"add component" tab. You need to create new tag in fork.

**Comment by jmuheim** [comment]
> Require path I mentioned

I don't get it. These files under `dist/` aren't available in my checked out `rails-assets-bootstrap-formhelpers` gem, there's only the `.less` stuff.

**Comment by bhgames** [comment]
Having same issue with bootstrap-select. Only became an issue when upgrading to 4.0.9 from 3.2.18.

**Comment by sheerun** [comment]
In new version of rails-assets, .less files won't be used as main assets. This should prevent your issue. Please wait for deployment, I'll notify about it on our twitter account.
