### ISSUE TITLE
Cannot generate FitText

### ISSUE THREAD

**Issue by manuelmeurer** [tenex/rails-assets#149]
I'm trying to use the FitText library through Rails Assets:
http://bower.io/search/?q=fittext
https://github.com/davatron5000/FitText.js/blob/master/bower.json

When I try to load it via `gem "rails-assets-FitText.js", "1.2.0"` in my Gemfile, it cannot be found. When I add it at https://rails-assets.org/components/new without a version, it says "FitText.js has no versions defined. Please create an issue in component's repository."
Looking at the bower.json it seems like the version is defined properly, no?

**Comment by sheerun** [comment]
Fittext has no semver github releases: https://github.com/davatron5000/FitText.js

This is required both by bower and us.
