### ISSUE TITLE
bootstrap-formhelpers doesn't work: not existing images are replaced with "image-url(".")"

### ISSUE THREAD

**Issue by jmuheim** [tenex/rails-assets#150]
There's an image `../img/eu.png` specified in [bootstrap-formhelpers-flags.less](https://github.com/winmarkltd/BootstrapFormHelpers/blob/master/less/bootstrap-formhelpers-flags.less#L927):

´´´
.bfh-flag-EUR{
  background: url(../img/eu.png) no-repeat;
}

.bfh-flag-XCD{
  background: url(../img/xcd.png) no-repeat;
}
´´´

But this image doesn't exist. Rails-assets now compiles it to the following:

```
.bfh-flag-EUR{
  background: image-url(".") no-repeat;
}

.bfh-flag-XCD{
  background: image-url(".") no-repeat;
}
```

This causes Rails to raise this error:

```
error evaluating function `image-url`: couldn't find file '.'
```

**Comment by jmuheim** [comment]
I know that this is mainly a problem of bootstrap-formhelpers, but replacing missing images with "." doesn't sound very sensible?

**Comment by sheerun** [comment]
We could leave url as is if Image doesn't exist (no image- prefix). Could
you send a PR?

**Comment by jmuheim** [comment]
Sure. Can you give me a hint where the corresponding code is? I forked rails-assets but don't find it.

**Comment by sheerun** [comment]
It's here: https://github.com/rails-assets/rails-assets/blob/master/app/models/build/transformer.rb#L153

A test would be welcome too :) You can stub `.exist?`

**Comment by jmuheim** [comment]
Haha, my texteditor ignored `build` directories in global search...

**Comment by jmuheim** [comment]
Why do you require postgres to be installed for development? I get errors like

```
An error occurred while installing pg (0.16.0), and Bundler cannot continue.
```

when bundling.

**Comment by jmuheim** [comment]
Also, I'm a bit unsure how to correctly address this issue. Should I only check whether the returned path is `"."`?

**Comment by sheerun** [comment]
I cannot help you with installing pg without error message. probably SQLite works too, but I didn't test. Better detect if file exists and return nil instead of .

**Comment by sheerun** [comment]
The bug is fixed. I'll notify about deployment on our twitter account.
