### ISSUE TITLE
Rails 4.x and image assets without digest

### ISSUE THREAD

**Issue by dmitry** [tenex/rails-assets#151]
Any ideas how to include images in Rails 4.x so they can load through the javascript loader?

The issue that sprockets-rails after version >= 4.0 not generating the non-digest version of file, like it was in rails 3.x.
https://github.com/rails/sprockets-rails#changes-from-rails-3x

For example I'm talking about the https://github.com/vperron/leaflet-dist, where the images are loading through the javascript:
https://github.com/vperron/leaflet-dist/blob/master/leaflet-src.js#L3448

Hope there are some possibility to do it through the Rails Engines.

**Comment by sheerun** [comment]
YouTube probably need to overwrite Icon.Default.imagePath with function
that returns proper path. it cannot be done automatically.

On Thursday, May 8, 2014, Dmitry Polushkin
<notifications@github.com<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
wrote:

**Comment by prashantrajan** [comment]
Re: Rails 4, see rails/rails#7968. This pretty much breaks things for packages with images. If things get packaged as `app/assets` instead of `vendor/assets` it may just work out of the box

**Comment by prashantrajan** [comment]
see http://github.com/twbs/bootstrap-sass/blob/master/lib/bootstrap-sass/engine.rb for another way of doing this with engines

**Comment by dmitry** [comment]
Compilation works, but it does an image assets with the digest (postfix) in their name. And in the leaflet image is loaded through javascript, so the naming should be without digest.

**Comment by prashantrajan** [comment]
it does not compile by default since the images are in vendor/assets. this is true as of Rails 4.

**Comment by dmitry** [comment]
It doesn't matter, I can add `precompile` directive by myself to the application config, but it doesn't solve an issue.

**Comment by sheerun** [comment]
I don't think it's easily possible to make such dynamic paths available from javascript.

Maybe use some manually-packed component like: https://github.com/cavis/leaflet-rails/

It has asset_path included in javascript file.
