### ISSUE TITLE
Should support full semver

### ISSUE THREAD

**Issue by samccone** [tenex/rails-assets#156]
Someone brought this to our attention here
https://github.com/marionettejs/backbone.marionette/issues/1368#issuecomment-43895387

while ^X.X.X || ^X.X.X is valid semver your site does not think so.

![](https://api.monosnap.com/image/download?id=6e5sjrbI00NlOK2RRuLfefPPkoYRO4)

Thanks!

**Comment by jamiebuilds** [comment]
I believe the `||` and `^` operators could be converted

``` js
// from
'jquery': '^1.8.0 || ^2.0.0'
// to
gem 'jquery', '~> 1.8.0', '~> 2.0.0'
```

**Comment by sheerun** [comment]
@thejameskyle In ruby this is AND, not OR relation. Your gem example won't match any version.

**Comment by sheerun** [comment]
To support this format we need to advanced version parsing and converthing version constraints with OR to ones with AND and NOT. I don't believe it's possible to do, so I'm closing :)

If someone has an idea how to implement that, a PR would be welcome. Here is rubygems code:

https://github.com/rubygems/rubygems/blob/master/lib/rubygems/requirement.rb

**Comment by sheerun** [comment]
I added an issue on rubygems, but sincerely I doubt such constraint is going to be introduced.
