### ISSUE TITLE
bower.json vs. component.json

### ISSUE THREAD

**Issue by frankie-loves-jesus** [tenex/rails-assets#157]
Trying to add https://github.com/jakiestfu/Snap.js but getting `snapjs has no versions defined. Please create an issue in component's repository.`. I see, however, that the repo has a `component.json` that looks just like a `bower.json`. Any reason why Rails Assets won't recognize this?

Many thanks!

**Comment by sheerun** [comment]
Because bower don't recognize it, and Rails Assets is bower proxy.
