### ISSUE TITLE
Feature Request: RSS Feed

### ISSUE THREAD

**Issue by andyl** [tenex/rails-assets#159]
I find the RSS/subscribe feature on rubygems.org to be really useful.

I just learned that with Github, you can get an RSS notification every time a project tag is updated.  Here's an example feed: https://github.com/twbs/bootstrap/tags.atom

I suspect that rails-assets has all the information it needs to construct this link.  Suggestion: generate an RSS link for every rails-asset package, to make it faster and more convenient for your users to track new releases of their rails-assets packages.

**Comment by sheerun** [comment]
I'm sorry, this won't be implemented in Rails Assets. We are just simple proxy.

You can construct atom GitHub URLs manually or create issue on bower online registry
