### ISSUE TITLE
depend_on_asset broken on fonts due to namespacing

### ISSUE THREAD

**Issue by stouset** [tenex/rails-assets#160]
The packages `twbs-bootstrap-sass`, `bootstrap-sass-twbs`, and `bootstrap-sass-official` are broken because they call

``` scss
//= depend_on_asset "bootstrap/glyphicons-halflings-regular.eot"
//= depend_on_asset "bootstrap/glyphicons-halflings-regular.svg"
//= depend_on_asset "bootstrap/glyphicons-halflings-regular.ttf"
//= depend_on_asset "bootstrap/glyphicons-halflings-regular.woff"
```

These end up being namespaced under the `#{package_name}/` rather than `bootstrap/` or `#{package_name}/bootstrap/`, and so cannot be found.

**Comment by sheerun** [comment]
This is not rails assets issue. Those packages use rails initializers to set custom loading paths.

This means those packages are not correctly packaged for bower.

Please open issue on their repositories, they should use `./bootstrap/something` instead `bootstrap/something` in their javascript and scss manifests like this one:

https://github.com/twbs/bootstrap-sass/blob/master/vendor/assets/javascripts/bootstrap.js

**Comment by sheerun** [comment]
`depend_on_asset` should also has relative path

**Comment by stouset** [comment]
Pardon my ignorance, but all of those projects seem to _actually_ point to the https://github.com/twbs/bootstrap-sass/ repo that you recommend as a good example.

**Comment by sheerun** [comment]
@stouset This component is unusable for consuming in bower.

You can use it as native rails gem though:

```
gem 'bootstrap-sass', '~> 3.1.1'
```

**Comment by stouset** [comment]
Shame. You might want to nuke the several rails-assets gems pointing to it, then.

**Comment by sheerun** [comment]
It's up to developer which dependencies he includes, so we don't need to nuke anything ;)

Dependencies of packages are not automatically required.

**Comment by stouset** [comment]
@sheerun I have to imagine that the SCSS sources for Twitter Bootstrap are a pretty popular use-case for rails-assets. What exactly makes the official sources unusable for consuming with bower, and what steps would be necessary to change that?

They do have a `bower.json`; if it's broken somehow, I'm happy to submit a patch and fix it.

**Comment by sheerun** [comment]
I already said it in https://github.com/rails-assets/rails-assets/issues/160#issuecomment-45290361 :)

It's theirs issue, not ours.
