### ISSUE TITLE
codemirror is missing many assets

### ISSUE THREAD

**Issue by whitehat101** [tenex/rails-assets#163]
The rails-assets version of https://github.com/marijnh/CodeMirror only includes the main css/js file.

The bower package also includes several additional directories that contain optional js/css assets.
- addon
- keymap
- mode
- theme

Is there a way those directories can be added to the pipeline asset path?

**Comment by sheerun** [comment]
Unfortunately there's no way.

These directories would need to be in `lib` directory to be visible.

Rails Assets recognizes `lib` directory as distribution directory, and ignores all other ones.
