### ISSUE TITLE
Speed up components/index.json

### ISSUE THREAD

**Issue by willcosgrove** [tenex/rails-assets#164]
Maybe I'm the only one who uses it, but I end up searching through the components list a lot to look to see what files are included in the gem that I'm going to use.  But the page loads painfully slow because it preloads all the gems.  It sends over about a 100kb JSON payload right now, which isn't too bad, it just takes a while for the server to generate it.

I would be up for submitting a pull request if I could get some feedback on what everyone thinks would be the best way to solve it.  The two best options I can think of are:
1. Cache the preloaded JSON in Redis which could cut that request down to basically just download time.  You would bust the cache on a component create, and if we wanted to prevent slowing that down, we could do that in a background job.  The downsides to this option are:
   1. ~~It would require someone with access to the server to set up Redis, and possibly Sidekiq (if we wanted to background cache busting)~~ Just noticed that Redis and Sidekiq are both already set up, and used in this app.
   2. It still isn't going to scale super well, once this JSON payload gets up to 500KB, 1MB, etc.
2. You could turn this into a more traditional autocomplete where the results are fetched from the server as needed.  This still has the same downside of needing someone with access to the server to setup some kind of search server, like Elasticsearch.  **Edit:** We could also use something like [seatgeek/soulmate](https://github.com/seatgeek/soulmate) if you want to avoid another dependency.

I'd be happy to code either of these solutions up, but I wanted to see 1) if anyone was interested and 2) if either of these options sounds better than the other one.

And thanks for making an awesome tool/service :smile:

**Comment by sheerun** [comment]
Believe or not, but it currently works 10x faster than some time ago ;)

From the network inspection it's clear JSON is generating much longer than sending (20s vs 0.5s).

I want search to be as responsive as now, so I would gladly accept PR for 1. you suggested.

Thanks for getting involved :)

**Comment by willcosgrove** [comment]
Awesome, I'll play around with it this weekend and see what I can come up with!
