### ISSUE TITLE
Cannot resolve package that hasn't bower.json

### ISSUE THREAD

**Issue by suisho** [tenex/rails-assets#166]
I want convert [Polymer/core-elements]() #0.3.3.
But I got error `Polymer--core-drag-drop#0.3.3: No files to convert`.
[Polymer/core-drag-drop]() has not bower.json.

I can install above version's [Polymer/core-element]() when use bower directry.

Can I resolve this probrem on rails-assets?

**Comment by sheerun** [comment]
Unfortunately no. Rails-assets requires bower.json no matter what.

Please open an issue or PR on Polymer/core-drag-drop repository.
