### ISSUE TITLE
jqueryui is missing the root file

### ISSUE THREAD

**Issue by vittorius** [tenex/rails-assets#168]
The jqueryui package mentiones the jqueryui/ui/jquery-ui.js in bower.json, component.json etc. But this file is missing. I had to

```
//= require jqueryui/ui/core
```

in **application.js** to make things work.

**Comment by sheerun** [comment]
It only mentions `jquery-ui.js`:

```
bower info jqueryui
{
  name: 'jquery-ui',
  version: '1.11.0',
  main: [
    'jquery-ui.js'
  ],
  dependencies: {
    jquery: '>=1.6'
  },
  homepage: 'https://github.com/components/jqueryui'
}
```

**Comment by vittorius** [comment]
Well, this is the dump of my bower.json for this gem:

```
{
  "name": "jquery-ui",
  "version": "1.11.0",
  "main": [
    "ui/jquery-ui.js"
  ],
  "dependencies": {
    "jquery": ">=1.6"
  }
}
```

I've installed this gem just by running bundle having `gem 'rails-assets-jquery-ui-slider-pips'` in my Gemfile.

**Comment by vittorius** [comment]
Maybe rails-assets has the obsolete versions of these package manifest files?

**Comment by sheerun** [comment]
This is `jquery-ui` package, not `jqueryui`.

It seems [they force-pushed 1.11.0](https://github.com/components/jqueryui/commit/1e1d15c7d7100294f449bd4730a5d3240da219af) version. You need to `bower cache clean`.

It also seems rails-assets built previous tag, before it was changed to point at different commit.

I need to clean caches on rails-assets and rebuild this version.

Ping @drmonty

**Comment by vittorius** [comment]
Thanks for the assistance. The correct version of `bower.json` is already there, in the `1.11.0` tag of `jqueryui`. With what else must I ping @drmonty?

**Comment by sheerun** [comment]
With nothing. You need to `bower cache clean`.

**Comment by sheerun** [comment]
Rails Assets bundle will be fixed soon.

**Comment by sheerun** [comment]
I'm planning rebuild for today. I'll tweet on our twitter account when it's done.
