### ISSUE TITLE
Missing manifest for retina.js gem

### ISSUE THREAD

**Issue by lsimoneau** [tenex/rails-assets#169]
Gemfile:

``` ruby
gem 'rails-assets-retina.js'
```

application.js.coffee:

``` coffee
#= require retina.js
```

I get this error: `couldn't find file 'retina.js'`

It seems the bundled gem does not have a generated manifest (only a directory containing the bower files):

```
louissimoneau@simoneau: ~/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rails-assets-retina.js-1.3.0/vendor/assets/javascripts
$ ls -al                                                                                                                                                                [9:06:02]
total 0
drwxr-xr-x  3 louissimoneau  staff  102 18 Jul 09:52 .
drwxr-xr-x  4 louissimoneau  staff  136 18 Jul 09:52 ..
drwxr-xr-x  7 louissimoneau  staff  238 18 Jul 09:52 retina.js
```

Maybe the fact that the library name contains a `.` is causing a problem?

**Comment by lsimoneau** [comment]
Looks like this is related to #153, probably the same issue.

**Comment by sheerun** [comment]
It can be an issue, but in case of retina.js, there is no main file because 1.3.0 tag is pointing to bower.json before it was fixed: https://github.com/imulus/retinajs/tree/a70e73639817473bad7bbb33f866b8e060e5f5a7

It contains incorrect path to main files.

**Comment by sheerun** [comment]
I'll track progress in #153
