### ISSUE TITLE
Duplicate script references being generated

### ISSUE THREAD

**Issue by drush** [tenex/rails-assets#170]
This manifest in a Rails 3.1 JS file:

```
//= require jquery
//= require bootstrap
//= require react
//= require react-bootstrap
```

Is generating this resulting script with duplicate file entries.  Some of the duplicates are empty (the second jquery, but other contain different versions of the file (for example the min and non-min versions).

Any ideas on what the root cause of this might be?  

```
<script src="/assets/jquery/jquery.js?body=1" type="text/javascript"></script>
<script src="/assets/jquery.js?body=1" type="text/javascript"></script>
<script src="/assets/bootstrap/bootstrap.js?body=1" type="text/javascript"></script>
<script src="/assets/bootstrap.js?body=1" type="text/javascript"></script>
<script src="/assets/react/react.js?body=1" type="text/javascript"></script>
<script src="/assets/react.js?body=1" type="text/javascript"></script>
<script src="/assets/react-bootstrap/react-bootstrap.min.js?body=1" type="text/javascript"></script>
<script src="/assets/react-bootstrap/index.js?body=1" type="text/javascript"></script>
<script src="/assets/react-bootstrap.js?body=1" type="text/javascript"></script>
```

**Comment by sheerun** [comment]
That's how sprockets work. If JS file consists only of requires, it is rendered as empty one.
Maybe @josh could help here?

I don't see the case of "different versions" in your example.

**Comment by josh** [comment]
>  If JS file consists only of requires, it is rendered as empty one.

Yep.

Is `/assets/jquery.js` just an index file with a require for `/assets/jquery/jquery.js`?

**Comment by sheerun** [comment]
@josh Yup. I just thought you know a way to circumvent showing empty files. 

Why sprockets doesn't recognise the file is empty, and avoid adding it to script tags?

**Comment by drush** [comment]
I actually cropped the one that was generating multiples - it was jquery.countdown:

```
<script src="/assets/jquery.countdown/jquery.countdown.js?body=1" type="text/javascript"></script>
<script src="/assets/jquery.countdown/jquery.countdown.min.js?body=1" type="text/javascript"></script>
<script src="/assets/jquery.countdown.js?body=1" type="text/javascript"></script>
```

**Comment by sheerun** [comment]
@drush It has broken bower.json manifest: https://github.com/hilios/jQuery.countdown/blob/master/bower.json

**Comment by josh** [comment]
> Why sprockets doesn't recognise the file is empty, and avoid adding it to script tags?

Its pretty irrelevant. This is only in file debugging mode anyway.
