### ISSUE TITLE
Support resolutions functionality

### ISSUE THREAD

**Issue by danieldkim** [tenex/rails-assets#172]
We've run into a situation where we need the resolutions functionality in bower to resolve a version conflict.  As of now we're forced to remove one of the modules that is creating the conflict from bower and manage it manually.  It would be nice if there were a way we could handle it through Rails Assets and specify resolutions in some way.

**Comment by sheerun** [comment]
It is pending bundler feature: https://github.com/bundler/bundler-features/issues/20
