### ISSUE TITLE
Doesn't package HTML files (needed for some AngularJS packages)

### ISSUE THREAD

**Issue by idrinkpabst** [tenex/rails-assets#174]
Hey guys, 
Great work and great gem.

I am trying to get the component "angular-utils-pagination", which requires an HTML file

``` javascript
// from bower.json
"main": ["dirPagination.js", "dirPagination.tpl.html"],
```

However, the HTML file is not packaged with the gem.  Using HTML templates in angular is pretty common.  

Any ideas for a solution or workaround?

**Comment by sheerun** [comment]
Currently the only workaround is to include html file manually in repository.

I need to implement packaging arbitrary files.

**Comment by sheerun** [comment]
I'm not sure where to put those html files.

**Comment by sheerun** [comment]
Html documents will be soon packaged in `documents` directory. You need to add them to asset path to be available. Please wait for deployment and rebuild. I'll notify on our twitter.
