### ISSUE TITLE
API status page

### ISSUE THREAD

**Issue by geoffharcourt** [tenex/rails-assets#176]
Not sure if this is the right repo to leave this issue on, happy to repost elsewhere if needed.

At the moment the Rails Assets API is responding to Bundler requests with an invalid response:

```
$ ✔ bundle
Fetching gem metadata from https://rails-assets.org/.Retrying dependency api due to error (2/3): Bundler::MarshalError TypeError: incompatible marshal file format (can't be read)
        format version 4.8 required; 91.123 given
Retrying dependency api due to error (3/3): Bundler::MarshalError TypeError: incompatible marshal file format (can't be read)
        format version 4.8 required; 91.123 given
Fetching gem metadata from https://rubygems.org/........
```

The page has a handy Build Status page to check on the status of component builds, but it would be awesome if there was some way to check and see if the server or API was currently experiencing issues.

Rails Assets has become an indispensable part of my workflow, so thanks.

**Comment by sheerun** [comment]
I'm looking into it.

**Comment by sheerun** [comment]
Changes of #173 are now reverted. Sorry for the trouble.

**Comment by geoffharcourt** [comment]
Thanks for the quick fix!

**Comment by mockdeep** [comment]
I get this error when I request an invalid package. I typed `es5-shims` instead of `es5-shim`. Might be nice to have the error message use the same format.

**Comment by sheerun** [comment]
We can't control the error message.

**Comment by mockdeep** [comment]
You can't change the format to work like rubygems? It seems like the server ought to respond in a way that bundler understands represents a gem not being available, as opposed to something that returns a `MarshallError`.

**Comment by sheerun** [comment]
Hmm. You're right, there's something wrong.

**Comment by sheerun** [comment]
The message should be normal again.

**Comment by mockdeep** [comment]
That did the trick. Thanks!
