### ISSUE TITLE
expose licenses in gems

### ISSUE THREAD

**Issue by grosser** [tenex/rails-assets#177]
Would be nice if the license from the bower package would be visible through the gem so auditing tools like [organization license audit](https://github.com/grosser/organization_license_audit) / [license_finder](https://github.com/pivotal/LicenseFinder) can find them

basically adding spec.license = package.license

**Comment by sheerun** [comment]
Good idea

**Comment by sheerun** [comment]
It's implemented. I'll let you know when packages are rebuilded on our twitter account.
