### ISSUE TITLE
Sprockets::FileNotFound (couldn't find file 'bootstrap')

### ISSUE THREAD

**Issue by danjellesma** [tenex/rails-assets#180]
Having trouble with rails-assets-bootstrap. Bundle updated successfully
Error: http://i.imgur.com/T5ZUL9W.png

Gemfile:
gem 'rails-assets-bootstrap'

application.css:
 *= require_tree .
 *= require_self
 *= require bootstrap

//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require_tree .
//= require bootstrap
//= require.js

"Using rails 4.1.5"
"Using rails-assets-bootstrap 3.2.0"

Processing by WelcomeController#index as HTML
  Rendered welcome/index.html.erb within layouts/application (0.1ms)
Completed 500 Internal Server Error in 173ms

ActionView::Template::Error (couldn't find file 'bootstrap'
  (in /vagrant/app/assets/stylesheets/application.css:15)):
    2: <html>
    3: <head>
    4:   <title>Vmdevdeploy</title>
    5:   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    6:   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    7:   <%= csrf_meta_tags %>
    8: </head>
  app/views/layouts/application.html.erb:5:in `_app_views_layouts_application_html_erb__555197690486104126_39065400'

  Rendered /home.rvm/gems/ruby-2.1.2@vmdev/gems/actionpack-4.1.5/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.2ms)
  Rendered /home.rvm/gems/ruby-2.1.2@vmdev/gems/actionpack-4.1.5/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.3ms)
  Rendered /home.rvm/gems/ruby-2.1.2@vmdev/gems/actionpack-4.1.5/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout (15.4ms)

**Comment by sheerun** [comment]
Did you restart application server?

**Comment by danjellesma** [comment]
I had not and it past that error by that after restarting the app server, thanks.

This is the error I'm getting now after the app server restart. 
http://imgur.com/Q2mByNv
Rails 4.1.5
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]

```
Showing /vagrant/app/views/layouts/application.html.erb where line #5 raised:
File to import not found or unreadable: bootstrap/less/bootstrap.
Load paths:
  /vagrant/app/assets/images
  /vagrant/app/assets/javascripts
  /vagrant/app/assets/stylesheets
  /vagrant/vendor/assets/javascripts
  /vagrant/vendor/assets/stylesheets
  /vagrant/vendor/bundle/ruby/2.1.0/gems/turbolinks-2.3.0/lib/assets/javascripts
  /vagrant/vendor/bundle/ruby/2.1.0/gems/jquery-rails-3.1.2/vendor/assets/javascripts
  /vagrant/vendor/bundle/ruby/2.1.0/gems/coffee-rails-4.0.1/lib/assets/javascripts
  /vagrant/vendor/bundle/ruby/2.1.0/gems/rails-assets-bootstrap-3.2.0/vendor/assets/fonts
  /vagrant/vendor/bundle/ruby/2.1.0/gems/rails-assets-bootstrap-3.2.0/vendor/assets/javascripts
  /vagrant/vendor/bundle/ruby/2.1.0/gems/rails-assets-bootstrap-3.2.0/vendor/assets/stylesheets
  /vagrant/vendor/bundle/ruby/2.1.0/gems/rails-assets-jquery-2.1.1/vendor/assets/javascripts
  (in /vagrant/vendor/bundle/ruby/2.1.0/gems/rails-assets-bootstrap-3.2.0/vendor/assets/stylesheets/bootstrap.scss:1)
```

```
<html>
<head>
<title>Title</title>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>  # this line highlighted
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head> 
```

application.css

```
/*
*= require_self
*= require bootstrap
*= require_tree .
*/
```

```
application.js
//= require jquery
//= require bootstrap
//= require jquery_ujs
//= require turbolinks
//= require_tree .
//= require.js
```

**Comment by Rykian** [comment]
Same issue here ! (rails 4.1.5 & rails-assets-bootstrap 3.2.0 too)

**Comment by sheerun** [comment]
Duplicate of #132
