### ISSUE TITLE
Markdown-js defect

### ISSUE THREAD

**Issue by contradictioned** [tenex/rails-assets#181]
Hi,

when installing markdown-js via Gemfile entry `gem 'rails-assets-markdown-js'` and then including markdown with `//= require markdown-js` in application.js, I get this error in the browser

```
couldn't find file '~/.rvm/gems/ruby-2.1.0@railsassets/gems/rails-assets-markdown-js-0.6.2/vendor/assets/javascripts/markdown-js/src/**/*.js'
(in /home/hoffmann/temp/RailsAssetsExample/app/assets/javascripts/application.js:15)
```

This corresponds to the the entry of markdown-js' bower.json, see https://github.com/Leeft/markdown-js/blob/master/bower.json `"main": "src/**/*.js"`

So a fix of this is to require the files by their path

```
//= require markdown-js/src/core.js
//= require markdown-js/src/markdown_helpers.js
//= require markdown-js/src/markdown.js
//= require markdown-js/src/parser.js
//= require markdown-js/src/render_tree.js
```

But if these files are included, then the browser complains `Uncaught ReferenceError: require is not defined markdown.js?body=1:1(anonymous function) markdown.js?body=1:1`

So the solution to this is to use 

```
//= require markdown-js/dist/markdown.js
```

which is not covered by the **main** entry. I think that this is highly inconvenient.

Is this a problem of the markdown-js project, that the **main** entry of their bower.json is wrong? According to the bower website, this should be String or Array of String, but they don't say something about wildcards.

I guess a simple solution would be a note on https://rails-assets.org/components what to include in the application.js file, if this is possible.

(appologies if this is the wrong project for report :) )

**Comment by sheerun** [comment]
I think globs in main are bad smell (see my comments in https://github.com/bower/bower.json-spec/issues/36). Also bower's spec doesn't explicitly say globs are allowed in main.

I think it's markdown-js's issue (they need to set main to dist/markdown.js).

You can always directly use correct asset in your application.scss:

```
//= require markdown-js/dist/markdown.js
```

**Comment by sheerun** [comment]
Thanks for the question, though :)
