### ISSUE TITLE
Remove version 0.1.14 of ng-token-auth package

### ISSUE THREAD

**Issue by kspe** [tenex/rails-assets#183]
Please remove version `0.1.14` of package `ng-token-auth`.

This version was committed to project repo by author (@lynndylanhurley) by mistake and does not work properly.

Unfortunately the version naming for stable versions is `0.2x` and now always 
version number `0.1.14` is installed by default when using `gem rails-assets-ng-token-auth`.

**Comment by sheerun** [comment]
Removed
