### ISSUE TITLE
Rebuild for angular-motion needed

### ISSUE THREAD

**Issue by bopm** [tenex/rails-assets#184]
Angular motion author [changed dependencies w/o bumping a version](https://github.com/mgcrea/angular-motion/commit/d8976b7c198cb46cce32a8af70d3d04f91e35773#commitcomment-7995422). Using 'add component' page I am not able to force rebuild for that component. Help needed.

**Comment by sheerun** [comment]
Major rebuild is planned. Probably first on new domain (beta.rails-assets.org).

Please stay tuned and subscribe to our twitter account.
