### ISSUE TITLE
Source map support?

### ISSUE THREAD

**Issue by RSO** [tenex/rails-assets#186]
I'm trying to load a bower component in my rails app through Rails Assets, and the component in question comes with a source map for the generated CSS, which seems like an awesome feature to me. However, I can't seem to get the source map to work in combination with Rails Assets.

When I install the gem, the file structure of the gem looks like this:
![screen shot 2014-10-06 at 21 05 42](https://cloud.githubusercontent.com/assets/139663/4537207/42ae9906-4dd7-11e4-89a8-600a0afb604e.png)
And the main SCSS file looks like this:

``` scss
@import 'react-date-picker/react-datepicker.scss';
@import 'react-date-picker/react-datepicker.css.map';
```

My guess is that that last line shouldn't be there, and that the `.css.map` file should actually be referenced in it's updated path, because now, when I visit the website locally, this is what I get:

![screen shot 2014-10-06 at 20 58 58](https://cloud.githubusercontent.com/assets/139663/4537219/8ee01084-4dd7-11e4-8acc-03c4e00138b2.png)

Which seems right, since the `.css.map` file resides in the `react-date-picker` folder, rather then the stylesheet root.

Is it even smart to host `.css.map` files with your bower component? Or should this be something that's handled in the project root (e.g. the Rails app)?

**Comment by sheerun** [comment]
Please don't load source maps in that way. Sprockets automatically generates source maps for your browser. Actually very soon RailsAssets is going to ignore all `.map` files anyway.

**Comment by marclennox** [comment]
I'm using the bootstrap-select bower module through rails-assets, which does not include the source map file, however the included css file references it, so I end up with continual 404 when chrome tries to load the css source map.

Is Rails assets supposed to be stripping out the references to the source map files in generating the gem?

**Comment by sheerun** [comment]
@marclennox See https://github.com/rails-assets/rails-assets/issues/190

PR is welcome

**Comment by marclennox** [comment]
Is there already a model where you do similar scrubbing or is this a completely new step?

**Comment by sheerun** [comment]
It's [process_asset](https://github.com/rails-assets/rails-assets/blob/master/app/models/build/transformer.rb#L159) function. Just please include a test :)
