### ISSUE TITLE
history.js missing javascript assets

### ISSUE THREAD

**Issue by aaronchi** [tenex/rails-assets#187]
I have an old version of rails-assets-history.js-1.8.0 on my computer. It has a bunch of javascript files in vendor/assets/javascripts. The current version of this same gem has no javascript files included in it.

I imagine there was some change that happened in selecting files that blew away the javascript assets after rebuilding the index. It would be great if someone could figure out why the javascript files are now being excluded.

**Comment by aaronchi** [comment]
I see there is a rails-assets-history gem with javascript assets. Is this the preferred version?

**Comment by sheerun** [comment]
Sorry, this was an unexpected change. Mainly because history.js doesn't define "main" file.

Please use rails-assets-history for now, and I'll try to improve automatic main asset detection.

**Comment by gsmetal** [comment]
rails-assets-select2 seems to have same problem, javascript file is blank

**Comment by sheerun** [comment]
Main asset detection won't improve. We're freezing gem changes... People expect gems to not change. See #230
