### ISSUE TITLE
Rails4 Production (Asset Pipeline) CSS Not Included in Minified File

### ISSUE THREAD

**Issue by dougfarre** [tenex/rails-assets#192]
Here is a summary of my issue: http://stackoverflow.com/questions/26693679/rails-asset-pipeline-compressed-minified-css-loaded-but-not-styling-document

Basically when sprockets minifies my application.css file, it doesn't include any of the rails-assets css in the minified file.  Therefore my document is completely un-styled on page load.

My application.css:
 *= require_tree .
 *= require_self
 *= require font-awesome
 *= require vendors
 *= require bootstrap
 *= require sweetalert
 *= require jquery-ui
 */

**Comment by sheerun** [comment]
What is your Rails version?

**Comment by sheerun** [comment]
It seems you had problems with css compression. I can't reproduce this error though.

`rake assets:precompile` works just fine with `rails-assets-bootstrap`

**Comment by dougfarre** [comment]
CSS compression was the issue. I had to switch to YUI compressor.
