### ISSUE TITLE
Best way to bump version of existing package?

### ISSUE THREAD

**Issue by fritzblue** [tenex/rails-assets#193]
Hi, I'm trying to use the lastest (0.17.1) version of angulartics, but only the following versions are currently available:

![image](https://cloud.githubusercontent.com/assets/6473463/4924578/55854dae-6524-11e4-9245-bf2287a1fe06.png)

What's the best way to bump the version to 0.17.1?

**Comment by sheerun** [comment]
You can always check build statuses in https://rails-assets.org/status

In case of angularitics, one of the dependencies doesn't have any tags defined (SHA-1)
