### ISSUE TITLE
rails-assets.org is down

### ISSUE THREAD

**Issue by KrisBraun** [tenex/rails-assets#195]
Amazing service! Currently blocking deploy since service is down.

Not sure if this is the proper contact method, but couldn't find another with the site down.

**Comment by KrisBraun** [comment]
And it's back. :+1:

**Comment by sheerun** [comment]
We experienced temporary downtime (50 minutes), as one of our cloud services crashed.

Everything's OK again, sorry for inconvenience.

**Comment by dmasur** [comment]
is there another downtime since this morning?

**Comment by 0x000000** [comment]
Hey guys! The service is down again!

**Comment by jandudulski** [comment]
There was a restart on the provider side, should work now.

**Comment by 0x000000** [comment]
@jandudulski Thank you!

**Comment by donaldpiret** [comment]
Down again :(

**Comment by v9n** [comment]
Down again but it's intermittent...

**Comment by blaze182** [comment]
+1

**Comment by heridev** [comment]
sadly, down right now

**Comment by hothero** [comment]
+1, does we have another solution for this situation?

**Comment by sheerun** [comment]
Please contact http://monterail.com/ that supports this application

**Comment by jandudulski** [comment]
There were networking issues on hosting platform, we are looking at it.

**Comment by teamon** [comment]
The issue has been currently solved thanks to great ShellyCloud support.
We will investigate further to prevent such issues in the future.

**Comment by miry** [comment]
It is still down

**Comment by teamon** [comment]
We are aware of that, working on it.

**Comment by snow** [comment]
just want to say thank you because it should be 05:50 CET now in Wrocław.

**Comment by teamon** [comment]
@snow Actually, it's 16:15 so it's not that bad ;)

**Comment by snow** [comment]
@teamon it's 23:17 +0800 so I think my mind is slow as Intel Celeron lol

**Comment by asdacap** [comment]
Seems to be down again.

**Comment by lkalwa** [comment]
Hi Guys,

Any chance to get this working by tomorrow?

**Comment by asdacap** [comment]
It actually online for awhile a few hours ago. Now down again.

**Comment by itkin** [comment]
hello, server seems down

**Comment by miry** [comment]
hello, server seems down.

**Comment by deivid-rodriguez** [comment]
Hei! rails-assets.org seems down. Not sure this is the right place to report it, but just wanted to let you know. Thanks for the service, by the way :heart:
