### ISSUE TITLE
Exclude 'samples' directory along with (test/examples/etc...)

### ISSUE THREAD

**Issue by mikeatlas** [tenex/rails-assets#196]
Coming across this in the `angulartics` package, I get a lot of extra assets in my app generated that aren't useful.

See
https://github.com/rails-assets/rails-assets/issues/46 https://github.com/rails-assets/rails-assets/commit/d19e940f5a5106cb473070607a828efa75deaaf5

And in my case,
https://github.com/luisfarzati/angulartics/tree/master/samples

**Comment by sheerun** [comment]
I'll exclude it, but please remind `angularitics` authors to fill "ignore" field in bower.json

**Comment by mikeatlas** [comment]
will do. thanks!
