### ISSUE TITLE
Complains about no version defined when there is one

### ISSUE THREAD

**Issue by AlainPilon** [tenex/rails-assets#197]
I am trying to add the component "metrics-graphics".

Looking at bower.json, we can see that there is a version defined (1.0.0):

https://github.com/mozilla/metrics-graphics/blob/master/bower.json

Yet, when I try to add it, I am getting the error message:

metrics-graphics has no versions defined. Please create an issue in component's repository.

**Comment by sheerun** [comment]
We use `bower info metrics-graphics` output.

Bower displays only semver tags as versions. bower.json does not matter at all.

1.0 tag is not semver.
