### ISSUE TITLE
Incorrect Dependency Resolution

### ISSUE THREAD

**Issue by aarongray** [tenex/rails-assets#198]
I am trying to add [Angular Scroll](https://github.com/oblador/angular-scroll) to a project that uses AngularJS, but I'm getting a dependency failure when I run bundle install.

```
bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rails-assets.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "rails-assets-angular":
  In Gemfile:
    rails-assets-angular-scroll (= 0.6.2) ruby depends on
      rails-assets-angular (~> 1.2.0) ruby

    rails-assets-angular (1.3.3)
```

So it looks like the ~> is not allowing it to work with 1.3.x. Which is kinda strange to me because it looks like angular-scroll's bower.json contains a ^, which should allow angular-scroll to work with anything except 2.0.0.

Bower.json:

```
"dependencies": {
    "angular": "^1.2.16"
}
```

I spoke with the maintainer of angular-scroll, and he updated his Bower.json to this in an attempt to loosen the dependencies.

```
"dependencies": {
  "angular": "<2.0 >1.2"
}
```

But, it is still failing for me when I run bundle install:

```
Bundler could not find compatible versions for gem "rails-assets-angular":
  In Gemfile:
    rails-assets-angular-scroll (>= 0) ruby depends on
      rails-assets-angular (~> 1.2.0.rc.2) ruby

    rails-assets-angular (1.3.3)
```

What should we change the Bower.json file to?

**Comment by aarongray** [comment]
Okay, I think this is a bug with rails-assets.

My previous problem still exists, and I'm seeing the same behavior with a different project (also running Angular 1.3) and a different bower package. This time, my desired package is ngQuickDate.

The bower.json of ngQuickDate:

```
"dependencies": {
    "angular": "~1.2.0"
  }
```

I believe this means that it should be compatible with any version of Angular greater than or equal to 1.2, but before 2.0.

Yet, I am getting a similar error when running bundle install.

```
Bundler could not find compatible versions for gem "rails-assets-angular":
  In Gemfile:
    rails-assets-ngQuickDate (= 1.3.3) ruby depends on
      rails-assets-angular (~> 1.2.0) ruby

    rails-assets-angular (1.3.0)
```

**Comment by aarongray** [comment]
Looks like it is behaving as it should in cases like this:

```
  "dependencies": {
    "angular": ">= 1.0.8"
  }
```

But things like `~1.2.0`, `<2.0 >1.2`, or `^1.2.16` are not correctly resolved, thus preventing installation of packages that use that notation in their bower.json.

**Comment by aarongray** [comment]
Wow, not even an acknowledgement of this issue in almost two weeks? This seems like a pretty bad bug with rails-assets, and hundreds of bower libraries appear to be affected by it. Rather than ask individual repo maintainers to change all those libraries - and compromise on their library support / dependencies policies - I think this issue should be resolved by rails-assets.

Any thoughts?

**Comment by ms-ati** [comment]
+1

**Comment by sheerun** [comment]
From node-semver documentation:

> ~1.2.3 := >=1.2.3 <1.(2+1).0 := >=1.2.3 <1.3.0

And

> ^1.2.3 := >=1.2.3 <2.0.0

So the behavior for `~1.2.0` is [correctly implemented](https://github.com/rails-assets/rails-assets/blob/master/spec/models/build/utils_spec.rb#L43).

The behavior for `^1.2.16` is also [correctly implemented](https://github.com/rails-assets/rails-assets/blob/master/spec/models/build/utils_spec.rb#L167).

If you feel rails-assets semver handling is incorrect, please add failing test in
https://github.com/rails-assets/rails-assets/blob/master/spec/models/build/utils_spec.rb

**Comment by sheerun** [comment]
I checked generating .gem file for `angular-scroll#0.6.2` and it generates correctly:

> spec.add_dependency "rails-assets-angular", ">= 1.2.16", "< 2"

But currently [hosted version](http://rails-assets.org/gems/rails-assets-angular-scroll-0.6.2.gem) has something different:

> spec.add_dependency "rails-assets-angular", "~> 1.2.0"

It means @oblador force-pushed 0.6.2 release, after rails-assets bundled it.

Could you confirm @oblador? 

To fix this he need to change angular dependency back to `^1.2.16` and create new release.

Rails-assets won't automatically rebuild gems after force pushing.

**Comment by oblador** [comment]
@sheerun: The current dependency change has not yet made it into a release since I was waiting on feedback. However if you've implemented the `^` resolution as stated then I don't see why that should matter since they are equal. 

Did not force push the 0.6.2 release.

**Comment by aarongray** [comment]
@sheerun Thanks for the info and for looking into this issue. But I still think something is not matching up. ngQuickDate and Angular Scroll are having issues when running `bundle install` with Angular version 1.3 or later. I don't think @oblador should have had to make a change at all - his dependency file should have worked the first time. The issue can be reproduced using my above examples.

**Comment by sheerun** [comment]
@aarongray ngQuickDate is not compatible with angular 1.3.0, because they specified `~1.2.0` as dependency which means `>=1.2.3 <1.3.0`. Angular Scroll for some reason also built with angular `~1.2.0` as dependency. I can't reproduce this behavior to fix it.

**Comment by aarongray** [comment]
@sheerun Oops, my bad. I made a mistake about the behavior of `~` with ngQuickDate. You are right, that one looks like its behaving as it should be. I'm sorry about that.

So you're saying that the fix for that ngQuickDate would be to change the dependency file from `~1.2.0` to `~1.2.`, and then make a new tagged release?

And you're saying that the issue with Angular Scroll is that for some reason, it compiled with the wrong version of Angular as a dependency. And the fix for Angular Scroll would be for @oblador to change the dependency file for Angular Scroll back to `^1.2.16` and make a new tagged release?

Thanks for your help.

**Comment by sheerun** [comment]
`~1.2` has the same meaning as `~1.2.0`. You're looking for `^1.2.0`

Yes. For some weird reason Rails Assets compiled Angular Scroll with angular ~1.2.0 as dependency.

The fix is to change the dependency file for Angular Scroll back to `^1.2.16` and make a new tagged release.

**Comment by aarongray** [comment]
Okay cool.

Aww man, I am so confused about how `~` works.

Maybe I am mistaken, but I thought that `~1.2` and `~1.2.0` were quite different. See [here](http://stackoverflow.com/questions/5170547/what-does-tilde-greater-than-mean-in-ruby-gem-dependencies).

**Comment by sheerun** [comment]
This is stackoverflow for Bundler's `~>`, not node's `~`.

Read following: https://github.com/npm/node-semver

**Comment by aarongray** [comment]
Ahhh! So they behave differently. Very interesting. ^_^

**Comment by oblador** [comment]
@sheerun Not sure if I follow, [the latest tagged release](https://github.com/oblador/angular-scroll/blob/v0.6.2/bower.json) uses `^1.2.16`.

**Comment by sheerun** [comment]
I know. For some reason Rails Assets compiled it with `~1.2.0` angular dependency.

@aarongray Need to either wait for full reindex of gems (doesn't happen very often), or you need to bump release. If you didn't force pushed latest release or changed latest tag, there's probably bug in Rails Assets that I cannot reproduce for now.

**Comment by sgtpepper43** [comment]
Regardless of what all the bower components say, when different components require different versions of say, angular, bower allows you to choose which one you want to use instead of just failing. For example I'm using angular 1.3.1, and I need a component that requires ~> 1.2.18. If I was just using bower I could add a resolution to just let me use 1.3.1 since it's probably not going to break anything. We need that option in rails assets.

**Comment by sheerun** [comment]
Unfortunately I have no idea how to implement it :(

**Comment by sgtpepper43** [comment]
I think the better solution is to just submit a pull request to the bad package fixing its dependencies anyways, haha
