### ISSUE TITLE
ratchet issue

### ISSUE THREAD

**Issue by meetwudi** [tenex/rails-assets#199]
I tried to use [ratchet](http://goratchet.com/).

```
gem 'rails-assets-ratchet'
```

And it is successfully installed. But when I start rails server, it complains `Could not find rails-assets-ratchet-2.0.2 in any of the sources`. There is no rails-assets-ratchet in gem folder.

However, when I specify version number directly, it works.

```
gem 'rails-assets-ratchet', '2.0.2'
```

Dont know if it is an issue, just post it here :)

**Comment by sheerun** [comment]
Did you restart app after installation?

**Comment by meetwudi** [comment]
Yes, I did. As I said, _there is no rails-assets-ratchet in gem folder_. So no matter whether I restart my app, the gem will always missing.

**Comment by sheerun** [comment]
Works for me. Sorry, I cannot reproduce this.

What `bundle show rails-assets-ratchet` returns?
