### ISSUE TITLE
Setup background periodic update

### ISSUE THREAD

**Issue by teamon** [tenex/rails-assets#2]

**Comment by porada** [comment]
How often do you think the versions should be auto-updated?

**Comment by teamon** [comment]
I'm researching bower registry rss if that's not available we can fallback to checking github for changes, I haven't yet decided how often. I'd also add "check for update" button on homepage if one want's to sync latests changes.

**Comment by teamon** [comment]
Looks like the only way to get updates is to setup periodic sync of all packages :/

**Comment by sheerun** [comment]
What's the status?

**Comment by teamon** [comment]
Sidekiq `Update` job is ready, just need some scheduling.

What I found out, when executing `bower list` it checks for new versions - we should find out what bower registry API it is (I couldn't find any docs) and first check for new packages via API and only then do checkout and gem build.

**Comment by sheerun** [comment]
I already did it.
