### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by jnylen** [tenex/rails-assets#20]
Hi,
I'm not sure if I should move over or not.
Currently this fork is slow towards European servers.

**Comment by joshjordan** [comment]
@jnylen thanks for opening. We're experiencing slowness in all regions right now while we reindex the bower repository. Is it alright if I keep this issue open, and ping you again to test when the process is complete?

**Comment by jnylen** [comment]
Sure!

**Comment by hut8** [comment]
Update: Digital Ocean was generous enough to give us $50, so I'm trying to see the best way to use that. I think it might be best to have two workers, but right now it's the web server process that's building the gems (which is a CPU-bound task).

In any case, we're working on the problem and will have a solution ASAP. Here's a CPU graph:

![pegged-cpu](https://cloud.githubusercontent.com/assets/363720/12532585/aa373bf4-c1e5-11e5-9227-f835eac15fc7.png)

**Comment by jnylen** [comment]
Are these hosted in USA?

**Comment by hut8** [comment]
Currently they are in NYC. What sort of latency and bandwidth are you seeing? Is this just with the site in general, or when serving gems? We're looking at options for CDNs as well for static assets.

**Comment by jnylen** [comment]
Could you put up a 100mb file? and i'll wget it.

**Comment by hut8** [comment]
Sure. https://rails-assets.tenex.tech/assets/100mb

From a different computer, this one being in New Jersey rather than NYC I got:

```
% curl https://rails-assets.tenex.tech/assets/100mb > /dev/null                                                          ⏎ [2016-01-23 23:32:32]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  100M  100  100M    0     0  70.7M      0  0:00:01  0:00:01 --:--:-- 70.7M
```

**Comment by jnylen** [comment]
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  100M  100  100M    0     0  14.6M      0  0:00:06  0:00:06 --:--:-- 14.7M

From france so it should be ok. Guess it is the time that it takes to start a transfer that is long.

**Comment by hut8** [comment]
Yeah, a CDN would help with that. We'll explore all options. I'll leave this open until the importing of packages is done.

**Comment by hut8** [comment]
Hey @jnylen I've suspended processing. Can you check it out now? Looks instant to me.

**Comment by jnylen** [comment]
Yeah, seems fairly faster.
https://rails-assets.tenex.tech/components.json is quite slow though. 3-4s to load. Cloudflare should be able to make it faster.

**Comment by hut8** [comment]
Thanks @jnylen ! Noted. I filed #29 for that, but it's not specific to our mirror.

**Comment by joshjordan** [comment]
I'll take a stab at speeding this way up tonight.

**Comment by hut8** [comment]
@jnylen it should be under 1 second now.
