### ISSUE TITLE
How to target pre-release versions (i.e. ember-data)

### ISSUE THREAD

**Issue by axsuul** [tenex/rails-assets#201]
ember-data is currently at `1.0.0-beta.12` but I'm having trouble targeting it.

``` ruby
gem 'rails-assets-ember-data', '1.0.0-beta.12'
```

returns

```
Could not find gem 'rails-assets-ember-data (= 1.0.0.pre.beta.12) ruby' in the gems available on this
machine.
```

Any suggestions?

**Comment by sheerun** [comment]
Read component list: https://rails-assets.org/components

it's `1.0.0.beta.12`
