### ISSUE TITLE
Unable to access malsup/blockui via rails-assets

### ISSUE THREAD

**Issue by rbloor-mdsol** [tenex/rails-assets#207]
https://github.com/malsup/blockui/

There are [releases](https://github.com/malsup/blockui/releases) available but still can't access the library via rails-assets

![image](https://cloud.githubusercontent.com/assets/2085764/5637205/ffaa3394-95c6-11e4-9d10-9f66152620d4.png)

What needs to be done to fix this?

**Comment by sheerun** [comment]
You need to create issues in component's repository about this. They don't use semver for tags.

**Comment by rbloor-mdsol** [comment]
@sheerun thanks!
