### ISSUE TITLE
Website request: Component permalinks

### ISSUE THREAD

**Issue by mahemoff** [tenex/rails-assets#208]
How about a dedicated page per component? Sometimes useful for linking in docs and code comments.

**Comment by sheerun** [comment]
There's not much to show on such page. Rails Assets is only proxy for bower components.

**Comment by mahemoff** [comment]
Pretty much the same as the search result shows, but on its own page. I don't mean the search result would no longer be expandable show all that, just that there'd be a dedicate page showing the same thing so that it can be bookmarked, linked, fetched by search engines, etc.

**Comment by sheerun** [comment]
It's not that bad idea, but I'm afraid I don't have resources to implement it. PR is welcome though.

**Comment by mahemoff** [comment]
Understand. I got the project running locally but my Angular will be too rusty for a PR, sorry.
