### ISSUE TITLE
Purge diaspora-jsxc package

### ISSUE THREAD

**Issue by ghost** [tenex/rails-assets#210]
I am working for the Diaspora\* project and I was wondering whether
there is a possibility to remove obsolete packages from rails-assets.org? 

We have currently two packages `diaspora_jsxc` and `diaspora-jsxc`.

Could you remove `diaspora-jsxc` from your database?

Cheers

**Comment by sheerun** [comment]
Hey!

What about developers that use those two gems? Are you sure you want to delete them?

Maybe warning or something on installation would be enough?

Adam

**Comment by ghost** [comment]
We are using diaspora_jsxc only. **Do not delete** diaspora_jsxc!!

diaspora-jsxc is obsolete and can be removed safely

**Comment by sheerun** [comment]
I mean that maybe some other people are using `diaspora-jsxc`.

It would be rude to delete this package :)

**Comment by ghost** [comment]
Well,I am pretty sure that no one is using that cause I started the diaspora/jsxc integration and the package was used by the diaspora development version only.

The only possibility is that someone uses a very old dev-version and that is a risk I am willing to accept :)

In the end it doesn't matter, thought. We can also keep the package, no problem with that.

**Comment by sheerun** [comment]
I think I'll be rolling out UI for removing packages. Let's leave `diaspora-jsxc` for now, ok?

**Comment by ghost** [comment]
sure. Could be a nice feature. Removing pkg based on usage statistics or something.
