### ISSUE TITLE
Add support for :git and :branch in Gemfile

### ISSUE THREAD

**Issue by snocorp** [tenex/rails-assets#211]
I tried the following in my Gemfile:

```
gem 'rails-assets-pickadate', :git => 'https://github.com/amsul/pickadate.js.git', :branch => 'master'
```

I got the following error:

```
Could not find gem 'rails-assets-pickadate (>= 0) ruby' in https://github.com/amsul/pickadate.js.git (at master).
Source does not contain any versions of 'rails-assets-pickadate (>= 0) ruby'
```

I suspect that supporting this may not be feasible but if it is it would be very useful when an issue is fixed but not yet released or when testing out a feature branch of a library.

**Comment by sheerun** [comment]
Sorry, it's technically impossible :)

`:git` and `:branch` fetches gems directly from GitHub without consulting Rails Assets
