### ISSUE TITLE
How is possible to rebuild bower package?

### ISSUE THREAD

**Issue by le0pard** [tenex/rails-assets#212]
Hello everyone. I see, you have `bin/rake 'component:destroy[jquery,2.0.3]'`, but no such possibility to do from web. How is possible to rebuild bower package? I just need rebuild marionette-gem, but "Add component" ignore 2.3.1 version.

Maybe possible to add checkbox "Rebuild" on form "Add component", which will remove and build component, if this version already exists?

**Comment by sheerun** [comment]
Yeah, ideally one could request re-build from web interface. Do you want to implement it and send PR?

Rebuild can be issued by setting `rebuild` flag of all `Version`s of `Component` to true and calling `UpdateComponent.perform_async(component.bower_name)`.

**Comment by sheerun** [comment]
We also need to handle Varnish cache refresh..

**Comment by le0pard** [comment]
Yep, I can try to add this by PR. Does this app cat trigger Varnish cache refresh? I couldn't find this in code.

**Comment by sheerun** [comment]
It's not implemented yet at all: https://shellycloud.com/documentation/caching#purge_rpurge_cache

You need to mock it in tests.. Things that need refreshing: `.gem` file, and `.gemspec.rz` file.

**Comment by sheerun** [comment]
Because refreshing needs to be done after building, you probably need to create special worker for it.

**Comment by le0pard** [comment]
@sheerun Ok, thanks. Will look after work.

**Comment by sheerun** [comment]
@le0pard Hey. Did you implement something so far?

**Comment by le0pard** [comment]
Sorry, nothing done. You can close issue - I add todo in my list.

**Comment by sheerun** [comment]
Let's leave it open. Maybe I'll find time to do it.

**Comment by sheerun** [comment]
Rebuilding is now implemented on www.
