### ISSUE TITLE
Dependencies can't be resolved to allow component to be added

### ISSUE THREAD

**Issue by mvastola** [tenex/rails-assets#213]
I am trying to add the component [fontello](https://github.com/fontello/fontello), but when I submit it on the [New component](https://rails-assets.org/components/new) page, I receive the error
`json2 has no versions defined. Please create an issue in the component's repository.`

Looking in the GitHub repo for fontello and seeing its [bower.json](https://github.com/fontello/fontello/blob/master/bower.json#L9) it would seem the issue is on line 9.
`"json2" : "*",`

However this wildcard _should_ be acceptable, as the [spec for bower.json](https://github.com/bower/bower.json-spec#dependencies) states the dependency value must be a valid "version", with version being defined as "a [semantic version](http://semver.org) parseable by [node-semver](https://github.com/isaacs/node-semver)". Following the later link, it's clear that a lone asterisk is such a semantic version.

![fontello_bower json_at_master_ _fontello_fontello_-_2015-01-21_10 11 54](https://cloud.githubusercontent.com/assets/599767/5838801/d0375c4e-a157-11e4-8fdb-10ac59dfac43.png)
![rails_assets_-_2015-01-21_10 11 36](https://cloud.githubusercontent.com/assets/599767/5838802/d038d600-a157-11e4-8aa6-3e589172faa7.png)

**Comment by sheerun** [comment]
fontello uses json2 as dependency and json2 has no semver tags on github.

rails-assets requires properly tagged repositories and properly tagged dependencies.
