### ISSUE TITLE
Build new version of gem ignore new dependencies versions

### ISSUE THREAD

**Issue by le0pard** [tenex/rails-assets#215]
I made fork of http://marionettejs.com/ and fix versions to build rubygems. Right now I trying to use underscore 1.7.0, but I always get such error:

``` bash
In Gemfile:
    rails-assets-marionette-gem (= 2.3.2) ruby depends on
      rails-assets-underscore (<= 1.6.0, >= 1.4.0) ruby

    rails-assets-underscore (1.7.0)
```

But my bower.json and package.json have another dependencies versions: https://github.com/le0pard/backbone.marionette-gem/blob/master/bower.json

Maybe I am doing something wrong? Why it ignore ">= 1.5.0"?

**Comment by sheerun** [comment]
please show me your gemfile (I hope you use `rails-assets-le0pard--backbone.marionette-gem`) and tagged new version of your gem. rails-assets compiles only git tags.

**Comment by le0pard** [comment]
``` ruby
GEM
  remote: https://rubygems.org/
  remote: https://rails-assets.org/
  specs:
    ... huge amount
    rails-assets-backbone (1.1.2)
      rails-assets-underscore (>= 1.5.0)
    rails-assets-backbone.babysitter (0.1.6)
      rails-assets-backbone (>= 1.0.0, < 1.1.3)
      rails-assets-underscore (>= 1.4.0, <= 1.6.0)
    rails-assets-backbone.wreqr (1.3.2)
      rails-assets-backbone (>= 0.9.9, <= 1.1.2)
      rails-assets-underscore (>= 1.3.3, <= 1.7.0)
    rails-assets-card (0.1.4)
      rails-assets-jquery (>= 1.5)
    rails-assets-fastclick (1.0.6)
    rails-assets-highlightjs (8.4.0)
    rails-assets-jquery (2.1.3)
    rails-assets-marionette-gem (2.3.2)
      rails-assets-backbone (>= 1.0.0)
      rails-assets-backbone.babysitter (>= 0.1.0)
      rails-assets-backbone.wreqr (>= 1.0.0)
      rails-assets-jquery (>= 1.8)
      rails-assets-underscore (>= 1.4.0, <= 1.6.0)
```

**Comment by sheerun** [comment]
Please tag your fork `2.3.2.1`, and use `rails-assets-le0pard--backbone.marionette-gem` in your gemfile.

**Comment by sheerun** [comment]
You can add forked version manually from www. I added it this time for you.

**Comment by le0pard** [comment]
Oh. But what the difference? http://monosnap.com/image/E97yKoKwRvveIE6WxSzLulZoD3RjmA I adding this one as "rails-assets-marionette-gem", and now I see "rails-assets-le0pard--backbone.marionette-gem". Seems like duplicates. 

P.S. The same problem:

``` bash
  In Gemfile:
    rails-assets-le0pard--backbone.marionette-gem (= 2.3.2) ruby depends on
      rails-assets-underscore (<= 1.6.0, >= 1.4.0) ruby

    rails-assets-underscore (1.7.0)
```

**Comment by sheerun** [comment]
> I made fork of http://marionettejs.com/ and fix versions to build rubygems. 

You need to create tag for commit fixing those versions, and add this version manually from www.

**Comment by le0pard** [comment]
I did it before: https://github.com/le0pard/backbone.marionette-gem/blob/v2.3.2/bower.json Fixed version inside tag. and even earlier: https://github.com/le0pard/backbone.marionette-gem/blob/v2.3.1/bower.json

**Comment by sheerun** [comment]
I'm not sure what's going on. Maybe you force-pushed v2.3.2 tag. It's safer to add new tag.

Please create new tag and add it manually from www.

**Comment by le0pard** [comment]
I add new tag, but looks like semver should be x.y.z - http://monosnap.com/image/kgzEv4aYtMjUybbQ0saARJXlw5t13j

BTW, I am sure, I am not force to push tags. Maybe it fetch deps from invalid source? Or ignore new deps and use old one by caching?

**Comment by sheerun** [comment]
You should enter `le0pard/backbone.marionette-gem` in name field and `2.3.2.1` in version field.
