### ISSUE TITLE
rails-assets-spinkit in version 1.0.1 does not match the bower package

### ISSUE THREAD

**Issue by pkuczynski** [tenex/rails-assets#217]
Comparing content of rails-assets-spinkit in version 1.0.1 and the bower package pointing to sources at https://github.com/tobiasahlin/SpinKit/tree/1.0.1/scss it looks like the rails-assets-spinkit is somehow outdated.

Could you fix that please? Or how can I fix it myself?

**Comment by sheerun** [comment]
Author probably force-pushed same tag. Rails Assets built old version.

You can always fork this component, tag it appropriately, and add it manually through Rails Assets WWW interface.

**Comment by pkuczynski** [comment]
Can I force Rails Assets to re-build this component? I am not sure how forking would help here?

**Comment by sheerun** [comment]
There's an issue for it: #212

**Comment by pkuczynski** [comment]
Does it mean that if I run

```
bin/rake 'component:destroy[rails-assets-spinkit,1.0.1]'
bin/rake 'component:convert[rails-assets-spinkit,1.0.1]'
```

this component will be re-built and re-uploaded?

**Comment by sheerun** [comment]
No. `component:destroy` / `component:convert` is only useful if you host rails-assets.

We need to implement selective rebuilding as in #212
