### ISSUE TITLE
rails-assets-fontawesome is missing woff2 font

### ISSUE THREAD

**Issue by stefanahman** [tenex/rails-assets#218]
Getting this error:

``` bash
http://localhost:3000/fonts/fontawesome/fonts/fontawesome-webfont.woff2?v=4.3.0
Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by prosanelli** [comment]
rails-assets-bootstrap-sass is also missing the woff2 fonts.
![screen shot 2015-02-11 at 11 23 50 am](https://cloud.githubusercontent.com/assets/2065666/6150952/8100d7f6-b1e0-11e4-914b-dafc0af5b1f5.png)

**Comment by mikelitton** [comment]
@sheerun Thanks for the fix. How do I make it work? I can't see that uninstalling and reinstalling fontawesome solves the problem. Please advice.

**Comment by sheerun** [comment]
@mikelitton Uninstalling and reinstalling should help. If you download http://rails-assets.org/gems/rails-assets-fontawesome-4.3.0.gem manually then you'll see it contains also woff2 font.
