### ISSUE TITLE
bootstrap.css.map 404 (Not Found)

### ISSUE THREAD

**Issue by pedros007** [tenex/rails-assets#224]
When load my page, I get 

```
 GET http://localhost:3000/assets/bootstrap.css.map 404 (Not Found)
```

I followed the instructions from [rails-assets.org](https://rails-assets.org) and:
- added this to my Gemfile:

```
    source 'https://rails-assets.org' do
      gem 'rails-assets-bootstrap'
    end
```
- ran `bundle update` and see `Using rails-assets-bootstrap 3.3.2`.  
- Added `//= require bootstrap` to application.js
- Added `*=require bootstrap` to application.css

Is this a bug or did I do something wrong?

**Comment by sheerun** [comment]
We're in process of rebuilding packages after removing source map references #190

It should take about 1 day to rebuild. Until then you'll get a warning.

I'll let you know when rebuild is done.

**Comment by sheerun** [comment]
By the way, this shound't affect how your application is working. You only get a warning in web console.

**Comment by pedros007** [comment]
Thanks, @sheerun.  I just downgraded to bootstrap-3.2.0 and I no longer see the error.

**Comment by sheerun** [comment]
Actually it seems 3.3.2 is already rebuilt on server.

Maybe you need to `gem uninstall rails-assets-bootstrap` and install it again. Could you check?

**Comment by pedros007** [comment]
Yes, seems to work now.  Thanks!
