### ISSUE TITLE
It seems to modify JSXTransformer.js file when you get rails-assets-react

### ISSUE THREAD

**Issue by Jae** [tenex/rails-assets#227]
It looks like rails-assets-react-0.11.2 includes JSXTransformer.js file that's different from original file from facebook and also rubyracer can't evaluate it... invalid syntax?

any idea?

**Comment by Jae** [comment]
it looks like it's removing this content out of JSXTransformer.js line 170

//# sourceMappingURL=data:application/json;base64,' +

and taking the single quote with it

**Comment by sheerun** [comment]
Sorry about that. I fixed code that removes sourcemaps, and rebuilt all react gems.

They should work again now (you may need to `gem uninstall rails-assets-react`).

**Comment by Jae** [comment]
cool thanks, it looks good now
