### ISSUE TITLE
rails-assets-raven-js does not correctly load raven-js

### ISSUE THREAD

**Issue by pkuczynski** [tenex/rails-assets#228]
In my Gemfile I added `gem 'rails-assets-raven-js'`` and then run bundle install. Despite that it fails to require the library in the application.js:

```
//= require raven-js
```

produce output:

```
throw Error("Sprockets::FileNotFound: couldn't find file 'raven-js'\n  (in /Users/kuczynsk/xyz/app/assets/javascripts/application.js:20)")
```

Thats the first time I hit this issue with rails-assets. Any idea why?

**Comment by sheerun** [comment]
What version of raven? Could you try to uninstall and install it again?

**Comment by pkuczynski** [comment]
OMG I am stupid, I added it to the production group in Gemfile. You can close this issue as invalid :(
