### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by hut8** [tenex/rails-assets#23]
We have a Mixpanel account, and they have an official gem, which is great. Our most important metric is probably measuring downloads of gems. So we need to hook up the Mixpanel gem to `config.ru` (or do something comparable)

**Comment by joshjordan** [comment]
Related to #54 but not completely solved by it (no server side)

**Comment by hut8** [comment]
Now that gems aren't served by passenger at all (hopefully), we need a different solution.

**Comment by hut8** [comment]
Solved well enough by shell scripts for now.
