### ISSUE TITLE
Handle errors

### ISSUE THREAD

**Issue by jandudulski** [tenex/rails-assets#23]
I'm sure we don't wanna show such a thing to the users:

![screenshot from 2013-09-04 10 29 05](https://f.cloud.github.com/assets/153103/1079034/8c9214b4-153c-11e3-97c2-e49483da58a3.png)

**Comment by porada** [comment]
@teamon, has this been improved lately?

**Comment by sheerun** [comment]
Yup, at most rails-assets will output bower json error. It can be improved further, but for now closing.
