### ISSUE TITLE
Rails assets should not be re-releasing new gems with the same version number

### ISSUE THREAD

**Issue by marclennox** [tenex/rails-assets#230]
As a result of this commit

https://github.com/rails-assets/rails-assets/commit/0e9f6a71d61f310b171b751d2f64a680f492f236

we have discovered a larger issue with rails-assets that has caused some serious havoc for us.  When there is a change to the way rails-assets packages gems, all previously released versions of the gem can  no longer be guaranteed to produce the same gem.  This is obviously against good version management.

Even worse is that, because the version number hasn't changed, bundler won't pull the "new" version, unless you don't already have that version pulled locally.  The result is that different people's environments end up with different "versions" of the same version.

I understand why this happens, because rails-assets versions are tied 1-1 with the source bower package.

Is there a way you could add a version suffix that increments (essentially a 4th version number) when the asset generation engine changes?

**Comment by sheerun** [comment]
Maybe that's good idea.. @teamon?

Generally I try to re-generate gems in backward-compatible way. If it didn't happen, I'm sorry.

Could you describe what issues it caused?

**Comment by marclennox** [comment]
Hey @sheerun and @teamon, I'll try to describe the incident that this change resulted in below.  But regardless of this specific incident, I just think that re-building libraries with different results for the same version number is problematic and will lead to confusion.  Rails assets is an awesome project, in case I didn't mention this earlier, but I do think the version numbering needs to have an additional counter in addition to the bower versions.

The issue was specifically around pickadate version 3.5.4.  In our application.scss file, we had the following sass import statements.

``` sass
@import "pickadate/lib/themes/classic";
@import "pickadate/lib/themes/classic.date";
@import "pickadate/lib/themes/classic.time";
```

Before commit https://github.com/rails-assets/rails-assets/commit/0e9f6a71d61f310b171b751d2f64a680f492f236 this worked fine.  After this commit, rails assets was updated to generate both .scss and .css.scss files in the ruby gems it produced, and pickadate version 3.5.4 was rebuilt with this new file.

Because the version number did not change, bundler (in our dev environments) had no idea that the gem had changed, so no complaints and things worked fine in development.

For our production and staging environments, we do clean builds in docker containers, so gems get pulled from rails-assets every time.  After the aforementioned commit, they were now getting the gems with the double css files.  In trying to compile the assets, rails asset pipeline blows up on the sass imports because they are now too ambiguous.

But of course our development environments continued to work fine because bundler thinks it has the latest gem (when in fact it does not).  Confusion and doubt ensue.

Eventually we figured it out, changing the import statements to be more specific, which fixed it.

``` sass
@import "pickadate/lib/themes/classic.scss";
@import "pickadate/lib/themes/classic.date.scss";
@import "pickadate/lib/themes/classic.time.scss";
```

Hope that made sense...

**Comment by sheerun** [comment]
Changing this behavior was a mistake from the very beginning... I'm not sure what to do at this point.

I'd go to previous behavior of generating only `.scss` files...

**Comment by marclennox** [comment]
Yes that seems like the right approach for this issue.  I can't imagine why both files would ever be needed.

But I think the larger issue remains.  

For now perhaps you should have a strict policy that past versions are never regenerated.

I can see this is a tough issue to handle though.

**Comment by ms-ati** [comment]
For what it's worth, I just wanted to "chime in" and say that, once built, I also agree that the gem versions should be immutable.

In the current workflow, all users of Rails Assets face a situation of variant versions over time. That is, the actual bundled asset gem for a given version may change over time, and the only way to ensure you have the latest is to monitor Rails Assets, and uninstall / reinstall those gems. This is not good.

I believe that there is a lot of precedent for re-packagers adding an additional numbering to versions to represent the version of their repackaging. For example, many .deb or .rpm files come with a package version at the end of the version string.

By adopting such a convention, Rails Assets would become a much more dependable option in three ways:
1.  Users could opt to stay on replaced versions of gems, if the re-packaged version actually introduced a problem for them
2.  Repeatable / invariant builds: Specifying a certain version of a Rails Asset gem could be guaranteed to always return that very version
3.  Friendliness to caches: Folks using caches of the gem sources, either internal to their company or via Heroku build packs or Travis CI test caching or other mechanisms, would never face a cache invalidation problem. Versions are simply fix-forwards.

I hope that consideration of these points will show why, like most other serious re-packagers in the open source world, Rails Assets should consider adding a sub-minor version number for their repackaging.

Thanks for all your great work,
-Marc

**Comment by sheerun** [comment]
All gems have been rebuilt to generate only `.scss` files, again..

There are few issues with additional "rails-assets" versions for packages, and immutability:
1. Bundler often updates packages selectively, so many users would end up with inconsistent set of packages
2. We need to maintain every such version
3. It's quite difficult feature to be made and maintain.

I think the goal would be to create `rails_assets` gem that would download sources directly from GitHub instead and deprecate .gem-packaging approach of rails-assets.

For now won't version rails-assets packages, but we also won't introduce incompatible changes in the future.. I hope it all works OK now for you..
