### ISSUE TITLE
Dependency's dependencies are too strict?

### ISSUE THREAD

**Issue by jnfeinstein** [tenex/rails-assets#232]
Trying to install jQuery `~> 2.1.1` (resolves to 2.1.3) with bootstrap `~> 3.2.0` (resolves to 3.2.0):

```
Bundler could not find compatible versions for gem "rails-assets-jquery":
  In Gemfile:
    rails-assets-bootstrap (~> 3.2.0) ruby depends on
      rails-assets-jquery (~> 1.10.2) ruby

    rails-assets-jquery (2.1.3)
```

[This](https://github.com/twbs/bootstrap/blob/v3.2.0/bower.json) was bootstrap's `bower.json` at the time of 3.2.0, and it depended on jQuery `>= 1.9.0`.  bootstrap `3.3.0` works fine, with [this](https://github.com/twbs/bootstrap/blob/v3.3.0/bower.json) bower.json.

Am I `ID10T`ing?

**Comment by sheerun** [comment]
You're not wrong. Something's seriously wrong with builds..

**Comment by jnfeinstein** [comment]
Everything has been working fine for me.  Thanks for the support.

**Comment by sheerun** [comment]
That's because builds were fixed. Now we use `dependencies` from `bower.json` directly, and we don't let bower preprocess them in any way.
