### ISSUE TITLE
Duplicated asset for mithril

### ISSUE THREAD

**Issue by pirj** [tenex/rails-assets#233]
Symthom:

```
<script src="/assets/mithril/mithril.min-0fe546d19f00444da81f7ab3bf279d7e.js?body=1"></script>
<script src="/assets/mithril-0fe546d19f00444da81f7ab3bf279d7e.js?body=1"></script>
```

Gemfile:

```
source 'https://rails-assets.org' do
  gem 'rails-assets-mithril'
end
```

app/assets/javascripts/application.js:

```
//= require mithril
//= require_tree .
```

~/.rvm/gems/ruby-2.1.2/gems/rails-assets-mithril-0.1.30/app/assets/javascripts/mithril.js:

```
//= require mithril/mithril.min.js
```

Additional info:

```
~ $ ls ~/.rvm/gems/ruby-2.1.2/gems/rails-assets-mithril-0.1.30/app/assets/javascripts/mithril
mithril.js  mithril.min.js

$ bower info mithril | grep main
  main: 'mithril.min.js',
```

Replacing in app/assets/javascripts/application.js:

```
//= require mithril/mithril.min.js
```

resolves the issue.

I cannot figure out what is wrong.

**Comment by sheerun** [comment]
Isn't `/assets/mithril-0fe546d19f00444da81f7ab3bf279d7e.js?body=1` an empty file?

This is how sprockets works.

**Comment by pirj** [comment]
Yep, you're right. It just causes confusion when there's just a single item in 'main'.

**Comment by sheerun** [comment]
All complains to Sprockets :)
