### ISSUE TITLE
Support git sources

### ISSUE THREAD

**Issue by jnfeinstein** [tenex/rails-assets#234]
This would be really useful in the case where one wants to make changes to a library, and a lot of the helpers are already present.

It appears that you can feed an url to bower i.e. `bower install -p -F https://github.com/jnfeinstein/foobar`.  The changes would therefore require modifying `install!` in `component.rb` to include a prefix and ignoring the returned version in `bower_component.rb`, since it will be nil or invalid.

As for the bundler API, perhaps using `rails-assets-jnfeinstein/foobar` would work, although that pretty much limits you to only supporting one source.  `rails-assets-github.com/jnfeinstein/foobar` would be another option.  I don't know bundler well enough to have other suggestions, but it looks like `:git`, `:source` and the like are all consumed by bundler, and using `:version` like bower results in bundler errors.

**Comment by jnfeinstein** [comment]
And as soon as I spent hours digging and testing code, it turns out that `rails-assets-jnfeinstein--foobar` works just fine.  Huzzah!

So just documentation of this feature would be wonderful.  :sunglasses:

**Comment by halilim** [comment]
@jnfeinstein How did you list it in your `Gemfile`? I couldn't manage to get it to work using either of:

```
gem 'rails-assets-user--some-repo'
gem 'rails-assets-user--some-repo', github: 'user/some-repo'
```

It ends up with

```
Source does not contain any versions of 'rails-assets-user--some-repo (>= 0) ruby'
```

A caveat is that the repo doesn't have a release (must pull from master).

Also +1 to documenting this, if this is a supported option.

**Comment by sheerun** [comment]
`github` flag doesn't work. You can only use tags as versions. Create new tag on your fork and wait for Rails Assets to build it (ot click "Rebuild" in the interface).

**Comment by halilim** [comment]
@sheerun OK, thanks. What about documenting it something like this:

```
+source 'https://rails-assets.org' do
+  gem 'rails-assets-bootstrap'
...
+  # Github repositories are supported too! E.g. for user/some-repo:
+  gem 'rails-assets-user--some-repo'
+end
```

**Comment by sheerun** [comment]
It's not a feature we want to advertise.

**Comment by halilim** [comment]
Is it because it's non-standard or not recommended? My motivation is that we'd be able to leverage the power of Rails Assets even for assets that are not in Bower (for not including 3rd party code in the codebase, simpler updates etc.).
