### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by uberllama** [tenex/rails-assets#235]
Long overdue, but I've found rails-assetsto be a brilliant solution for modern javascript package management in a Rails app. I just switched over my last x-rails gem to a rails-assets-x gem and it was a beautiful thing. Cheers.

:+1: :+1:

**Comment by sheerun** [comment]
Thank you!

Unfortunately we can't call it modern. Just more modern than putting JS files in repository.

Real modern front-end pipeline uses something like gulp instead of sprockets. It's harder to setup though.

**Comment by uberllama** [comment]
Yes, modernesque. :)
