### ISSUE TITLE
Status: Package node not Found

### ISSUE THREAD

**Issue by BenMorganIO** [tenex/rails-assets#237]
Currently experiencing some issues with Rails Assets. The build status isn't doing so well:

https://rails-assets.org/status

**Comment by BenMorganIO** [comment]
I was running my Rails application on Bundler 1.8.4. After downgrading to 1.7.13 the application started. Are we able to get this application working with Bundler 1.8.4?

**Comment by sheerun** [comment]
Hey. What's your Gemfile?

**Comment by BenMorganIO** [comment]
https://gist.github.com/BenMorganIO/5a768e57873fd5ef0a31

**Comment by sheerun** [comment]
I tried to `bundle install` this Gemfile on 1.8.4 and it succeeded with following Gemfile.lock:

https://gist.github.com/sheerun/80f81190eda3c4115931

Note that there's no "node" or "rails-assets-node" there.

The failed builds on https://rails-assets.org/status are totally legit. We even post reasons of build fails.

What is exactly the error message and backtrace you get?

**Comment by BenMorganIO** [comment]
Sorry, it does succeed bundling, but it fails when starting the web server.

**Comment by sheerun** [comment]
Could you post the error message and full backtrace?

**Comment by BenMorganIO** [comment]
Currently having trouble recreating TBH. Working on it right now.
