### ISSUE TITLE
HTTPS errors (possibly related to certs since OpenSSL announcement?)

### ISSUE THREAD

**Issue by geoffharcourt** [tenex/rails-assets#239]
http://openssl.org/news/secadv_20150319.txt

I'm currently getting bad certificate errors since updating to OpenSSL 1.0.2a. I am able to access Rubygems over HTTPS without any issues, so I think this isn't specific to my development machine.

**Comment by sheerun** [comment]
Could you paste the errors? As verbosely as possible :)

Ping @grk

**Comment by geoffharcourt** [comment]
When I type `bundle update` (excuse the source warnings):

``` shell
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
HTTP GET https://rails-assets.org/api/v1/dependencies
HTTP GET https://bundler.rubygems.org/api/v1/dependencies
HTTP 200 OK
Fetching source index from https://rails-assets.org/
Retrying source fetch due to error (2/3): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rails-assets.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Retrying source fetch due to error (3/3): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rails-assets.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Could not verify the SSL certificate for https://rails-assets.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and
change 'https' to 'http'.
```

I completely deleted my version of Ruby and all of its associated gems and installed from scratch to check against it being some kind of problem with Ruby or gems compiled against the wrong OpenSSL version. When I change the Rails-Assets source to use HTTP (but keep Rubygems as HTTPS), I am able to install all my gems.

**Comment by geoffharcourt** [comment]
I have never needed to do this, but I added an extra CA root bundle, and was able to connect. Apologies for the trouble.

**Comment by jasdeepsingh** [comment]
I'm still experiencing this issue, anything else needs to be done here?

**Comment by geoffharcourt** [comment]
I had to install an extra CA bundle that wasn't included with OpenSSL over Homebrew.

**Comment by jasdeepsingh** [comment]
@geoffharcourt  Was it this: https://github.com/raggi/openssl-osx-ca ?

**Comment by jasdeepsingh** [comment]
```
➜ project git:(staging) ✗ sudo rvm osx-ssl-certs status all
Certificates for /usr/local/etc/openssl/cert.pem: Up to date.
Certificates for /System/Library/OpenSSL/cert.pem: Up to date.
Certificates for /etc/openssl/cert.pem: Up to date.
```

All my certificates seems to be upto date. :crying_cat_face:

**Comment by sheerun** [comment]
@jasdeepsingh We updated our OpenSSL version. Did it help?

**Comment by gitviola** [comment]
Same problem here :(

**Comment by gitviola** [comment]
It's working now!

After a while I found this site https://railsapps.github.io/openssl-certificate-verify-failed.html

**What I did**

``` bash
$ brew update && brew install openssl
$ cd /usr/local/etc/openssl/certs
$ curl -O http://curl.haxx.se/ca/cacert.pem
$ mv cacert.pem cert.pem
$ /usr/local/opt/openssl/bin/c_rehash
```

After that it worked fine for me.

(@jasdeepsingh)

**Comment by jasdeepsingh** [comment]
@sheerun it seems to be working fine for us now. Thanks so much!

**Comment by sheerun** [comment]
I'm leaving this so others can see @schurig solution. Thanks!

**Comment by felixbuenemann** [comment]
@schurig's advice helped me too. I tested with a fresh ca bundle created from my system keychains and it was not sufficient:

``` bash
security find-certificate -a -p /Library/Keychains/System.keychain \
  /System/Library/Keychains/SystemRootCertificates.keychain > cabundle.pem
curl --cacert cabundle.pem -v https://rails-assets.org
* Rebuilt URL to: https://rails-assets.org/
* Hostname was NOT found in DNS cache
*   Trying 178.32.77.8...
* Connected to rails-assets.org (178.32.77.8) port 443 (#0)
* SSL: certificate verification failed (result: 5)
* Closing connection 0
curl: (51) SSL: certificate verification failed (result: 5)
```

Why it works fine then in Safari is beyond me.

**Comment by jasdeepsingh** [comment]
Hey guys, It's still not working for me. I've tried the same debug steps as mentioned by @felixbuenemann and my results are consistent with his and I cannot get it to work over https, the only temporary solution for me was to use http.

What is interesting is that I'm getting the same issue for https://gemfury.com/ as well (which I use to host some private gems)

(@schurig @sheerun @rykov)

**Comment by felixbuenemann** [comment]
@jasdeepsingh Have you tried @schurig's advice? It worked for me.

**Comment by gitviola** [comment]
Could it be that we all have the Yosemite Beta installed?

**Comment by geoffharcourt** [comment]
@schurig, I am on Yosemite Beta. Is that really the cause? Ugh.

**Comment by gitviola** [comment]
@geoffharcourt I have no idea. An other friend of mine also had the problem and uses the Yosemite Beta

**Comment by felixbuenemann** [comment]
Yeah, I'm on 10.3 beta as well.

**Comment by jasdeepsingh** [comment]
I'm on Yosemite Beta as well, I have another OS X machine, which is running previous stable release of OS X, I'm going to try there.

@felixbuenemann you meant 10.10.3 right? not 10.3?

**Comment by acrogenesis** [comment]
I'm having the same problem and have the Yosemite Beta... :sob: 

10.10.3 (14D130a)

**Comment by felixbuenemann** [comment]
@jasdeepsingh Yeah, typo.

**Comment by rykov** [comment]
As an additional datapoint, some @gemfury customers are reporting this error as well with OSX 10.10.3 beta.  Our SSL certificate for **fury.io** is issued by "RapidSSL SHA256 CA - G3" as well.

**Comment by jasdeepsingh** [comment]
I can assert that I'm having this same issue with Gemfury too.

**Comment by lloeki** [comment]
I have a troublingly similar issue, affecting among others some Google sites and apps (including [Google Music via ruby](https://github.com/lloeki/ruby-skyjam) and access to e.g SMTP). The Google Internet Authority G2 intermediate cert has expired, and I had to import a new one downloaded from Google into the system keychain. This fixed my SMTP issue but ruby keeps complaining.

I'm on 14D130a too. Another machine on 10.10.2 of mine seems entirely unaffected (neither ruby nor Mail.app's SMTP to Gmail).

**Comment by acrogenesis** [comment]
Version 10.10.3 (14D131) was released today and the problem is still present :sob:

**Comment by mccraveiro** [comment]
@schurig Solution didn't work for me :/ Also using 10.10.3 beta :sob:

**Comment by mccraveiro** [comment]
Finally got it to work! I did as @schurig said but on `/etc/openssl/`

**Comment by lloeki** [comment]
This is what I have as an easy replication test:

```
ruby -e 'require "net/http"; require "uri"; Net::HTTP.get(URI("https://rubygems.org"))'      #works
ruby -e 'require "net/http"; require "uri"; Net::HTTP.get(URI("https://rails-assets.org"))'  #fails
ruby -e 'require "net/http"; require "uri"; Net::HTTP.get(URI("https://google.com"))'        #fails
ruby -e 'require "net/http"; require "uri"; Net::HTTP.get(URI("https://fury.io"))'           #fails
```

I'm not too keen on putting 1. random stuff from the net 2. downloaded via http sans `s` 3. straight into my system's `/etc` and 4. following a recipe without having a better picture of what's going wrong.

**Comment by gitviola** [comment]
@lloeki is right. I hope this gets fixed soon since Yosemite 10.10.3 is out of beta now. I guess a lot of people will have the same issue after updating in case it is related to the new OS version.

**Comment by lloeki** [comment]
It may be linked to [this](https://github.com/Homebrew/homebrew/pull/28658) and things not working quite the same in 10.10.3, who knows.

My work machine has been updated to 10.10.3 and it works there. It may be related to a non-regenerated cert.pem, or my ruby (from rbenv) being built against another version of OpenSSL. Many moving parts, more investigation needed.

**Comment by lloeki** [comment]
BTW, just to be clear, doing `curl http://curl.haxx.se/ca/cacert.pem > /usr/local/etc/openssl/cert.pem` does make things work.

**Comment by rykov** [comment]
To follow up non @lloeki's success and help narrow down the problem, if you're having this issue, can you please post the following for your Ruby and how it's installed (system, rbenv, rvm, etc):

```
ruby -r openssl -e 'puts RUBY_VERSION; puts OpenSSL::VERSION; puts OpenSSL::OPENSSL_VERSION'
```

I'm still trying to figure out how to dump the default location of SSL certs, but that would be interesting to know too.

**Comment by lloeki** [comment]
[Here's the script](https://github.com/lloeki/toolbelt/blob/master/update-local-certificates) I used to use which does not work anymore either. Well it appears to work but there must be missing stuff. Note that there is a SystemRootCertificates and a SystemCACertificates keychain (but that doesn't help).

I wonder if the export process is the culprit, of if there are missing certificates for some reason.

Also, I wonder if there is a link with [this](https://truesecdev.wordpress.com/2015/04/09/hidden-backdoor-api-to-root-privileges-in-apple-os-x/).

**Comment by lloeki** [comment]
On my work machine:

```
# rbenv + brew (all aforementioned tests pass)
$ ruby -r openssl -e 'puts RUBY_VERSION; puts OpenSSL::VERSION; puts OpenSSL::OPENSSL_VERSION'
2.1.5
1.1.0
OpenSSL 1.0.2 22 Jan 2015
# system (all aforementioned tests pass)
$ /usr/bin/ruby -r openssl -e 'puts RUBY_VERSION; puts OpenSSL::VERSION; puts OpenSSL::OPENSSL_VERSION'
2.0.0
1.1.0
OpenSSL 0.9.8za 5 Jun 2014
# `brew install openssl` generated this, which predates upgrade to 10.3
$ ls -l /usr/local/etc/openssl/cert.pem
-rw-r--r--  1 lloeki  admin  343068 30 Mar 11:54 /usr/local/etc/openssl/cert.pem
```

**Comment by gitviola** [comment]
```
2.2.1
1.1.0
OpenSSL 1.0.2a 19 Mar 2015
```

**Comment by lloeki** [comment]
Merely regenerating cert.pem from the keychain makes things stop working on my work machine: my homebrew-generated `cert.pem` predated my upgrade to 10.3. As soon as an install or upgrade of openssl is done post 10.3 via homebrew, `cert.pem` will be regenerated and things blow up.

I put homebrew in the loop.

**Comment by lloeki** [comment]
So, Apple removed the (widely deemed insecured, should have migrated in 2010) Equifax Secure CA from the Keychain. Same for RapidSSL. Mozilla will proceed with this too. Client-side there's nothing to do except wait as this spring cleanup mandates reissuing of many certificates around the world.

**Comment by rykov** [comment]
Whoever was having this problem with Gemfury's `fury.io` endpoints, please try again.  We've done a certificate update and need to make sure it has fixed the problem.

The problem, as mentioned above, is that the old "GeoTrust Global CA" certificate (serial 12:BB:E6) was incorrectly signed and was reissued.  The errors we are seeing is due to this incorrect certificate being installed in the chain for our and rails-assets SSL servers.  We did this by mistake because adding this cert is still recommended in the RapidSSL knowledgebase:
https://knowledge.rapidssl.com/support/ssl-certificate-support/index?page=content&id=AR1549

The most recent working version of the certificate has the serial 23456 and can be downloaded here.  It is now a correctly signed root certificate, so you may not need to add it to your chain:
https://www.geotrust.com/resources/root-certificates/

_TL;DR To fix this issue, Rails-Assets owner needs to remove the old-busted "GeoTrust Global CA" certificate from their SSL chain and optionally replace it w/ the new-hotness._

Reference:
https://bugreports.qt.io/browse/QTBUG-45487?focusedCommentId=278363&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-278363

**Comment by jasdeepsingh** [comment]
@rykov just attempted a `bundle install` on my Gemfile which contains the fury.io source. 

And I can verify it works fine for me. :+1: thanks so much!

**Comment by rykov** [comment]
Thanks for checking and verifying the fix for Gemfury :beers:

**Comment by sarlv** [comment]
I have still error: 
Could not verify the SSL certificate for https://rails-assets.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA
certificates needed for verification. For information about OpenSSL certificates, see bit.ly/ruby-ssl. To connect
without using SSL, edit your Gemfile sources and change 'https' to 'http'.

**Comment by rykov** [comment]
@sarlv Sorry for hijacking the thread, but we had a similar problem with Gemfury and that's the fix we pushed.  We are not affiliated w/ Rails-Assets service.

**Comment by sheerun** [comment]
@rykov Thank you for providing us possible fix for it.

We'll try to fix this certificate issue on Rails Assets as well. I'll keep you all posted.

**Comment by mrrooijen** [comment]
I had no issues under MRI 2.2.1, but since upgrading to 2.2.2 I'm seeing:

```
Fetching source index from https://rails-assets.org/
Retrying source fetch due to error (2/3): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rails-assets.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Retrying source fetch due to error (3/3): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rails-assets.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Could not verify the SSL certificate for https://rails-assets.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see bit.ly/ruby-ssl. To
connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
```

See: https://www.ruby-lang.org/en/news/2015/04/13/ruby-openssl-hostname-matching-vulnerability/

**Comment by tallica** [comment]
Hello! I've updated "GeoTrust Global CA" certificate. Please let me know if it works now. Cheers!

**Comment by mrrooijen** [comment]
Yep. Appears to bundle correctly now. Thanks!

**Comment by rykov** [comment]
@tallica https://ssltools.geotrust.com/checker/views/certCheck.jsp says it's :ok_hand:, but now that "GeoTrust Global CA" is self-signed, you no longer need to include it in the certificate chain.

**Comment by tallica** [comment]
@rykov Thanks, removed it from the chain: ![](http://s.tallica.pl/f1c7ea24e829468eb7158ec485900d44a174a5ba.png)

**Comment by tallica** [comment]
@meskyanichi Can you please confirm that it still works for you? :)

**Comment by tombruijn** [comment]
@tallica it works on this end on ruby 2.2.2 (I had the same exact issue)

**Comment by tallica** [comment]
Perfect! Thanks for your help! Closing.

**Comment by mrrooijen** [comment]
:+1:

**Comment by sheerun** [comment]
Thank you Michał for handling this!

**Comment by sheerun** [comment]
sheerun@sher.pl sent you an invitation to join MEGA.\n\n";

--- Message from user: ---
Hello, join me on MEGA and get access to encrypted storage and
communication. Get 50 GB free!
---

Please create your free MEGA account by clicking on the following
link:\n\n";
https://mega.nz/#newsignupcmVwbHkrMDAwNDc2MGRjMmZmNTFhNmI0Y2UyZDIxNWYxZDUxZGY5MTQ4NDI4MzdhNWRiYjllOTJjZjAwMDAwMDAxMTE0NGYwODY5MmExNjljZTAzYzJhMWFkQHJlcGx5LmdpdGh1Yi5jb21BmXmag2guhQ

Best regards,

Team MEGA

**Comment by dilizarov** [comment]
Is it back? I'm getting it again.

**Comment by jandudulski** [comment]
> Is it back?

We were making some minor updates, it should be stable now.

**Comment by ghost** [comment]
Same error still with windows....

**Comment by ghost** [comment]
Does anyone have a solution for windows?

**Comment by jtheck** [comment]
For windows here is an explanation and fix:

https://gist.github.com/fnichol/867550

**Comment by allthesignals** [comment]
I don't understand why this keeps happening to me. Same issue, every few days, on different machines. I feel like I should nuke all my Macs just to avoid it from happening over and over.

**Comment by hut8** [comment]
@allthesignals What exactly is the error you're getting? Is it precisely the same as the one above? Please file a new issue if not.

**Comment by tristantao** [comment]
Check out https://github.com/rubygems/rubygems/issues/1758

@allthesignals If you were to nuke something, nuke your RVM. No need to nuke your whole Mac. Nuking the RVM worked for me via:

`rvm implode`

Like I said, check out that thread for more details.

**Comment by murdoch** [comment]
It's back! I'm only seeing it when I push to heroku though:
```
stephen@helloworld:~/Code/charts$ bin/deploy
Counting objects: 234, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (231/231), done.
Writing objects: 100% (234/234), 24.55 KiB | 0 bytes/s, done.
Total 234 (delta 186), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.4.0
remote: -----> Installing dependencies using bundler 1.15.2
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.15.4). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
remote:        Fetching source index from https://rails-assets.org/
remote:        Retrying fetcher due to error (2/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rails-assets.org/.
remote:        There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
remote:        Retrying fetcher due to error (3/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rails-assets.org/.
remote:        There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
remote:        Retrying fetcher due to error (4/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rails-assets.org/.
remote:        There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
remote:        Could not verify the SSL certificate for https://rails-assets.org/.
remote:        There is a chance you are experiencing a man-in-the-middle attack, but most
remote:        likely your system doesn't have the CA certificates needed for verification. For
remote:        information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect
remote:        without using SSL, edit your Gemfile sources and change 'https' to 'http'.
remote:        Bundler Output: Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.15.4). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
remote:        Fetching source index from https://rails-assets.org/
remote:        
remote:        Retrying fetcher due to error (2/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rails-assets.org/.
remote:        There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
remote:        Retrying fetcher due to error (3/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rails-assets.org/.
remote:        There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
remote:        Retrying fetcher due to error (4/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rails-assets.org/.
remote:        There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
remote:        Could not verify the SSL certificate for https://rails-assets.org/.
remote:        There is a chance you are experiencing a man-in-the-middle attack, but most
remote:        likely your system doesn't have the CA certificates needed for verification. For
remote:        information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect
remote:        without using SSL, edit your Gemfile sources and change 'https' to 'http'.
remote:  !
remote:  !     Failed to install gems via Bundler.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy....
```

Like I said, `bundle install` runs fine on my localhost. My gemfile contains the following:

```
source 'https://rails-assets.org' do
  gem 'rails-assets-cookieconsent2'
  gem 'rails-assets-leaflet'
end
 ```

**Comment by murdoch** [comment]
Whoops, I spoke too soon.
I'm now seeing it on my localhost, after deleting my Gemfile.lock and bundling again.
Removing `https` from my Gemfile had no effect.

**Comment by murdoch** [comment]
I think this might explain it!

![rails-assets](https://user-images.githubusercontent.com/56636/33603202-b530b64c-d9a9-11e7-9f4b-12f162a0f4b0.png)

Looks like https://rails-assets.org/ has a certificate problem of some kind.

**Comment by JulienCorb** [comment]
Just got the problem this morning !! the exact same thing as @murdoch

**Comment by rykov** [comment]
Looks like the SSL cert has expired today:
https://www.ssllabs.com/ssltest/analyze.html?d=rails-assets.org&latest

**Comment by felixbuenemann** [comment]
If the Let's Encrypt cron jobs for renewal are installed, it's probably missing a reload hook, so nginx loads the new certificate after a renew.

This line in `/etc/letsencrypt/cli.ini` should fix it:

```
post-hook = /usr/sbin/nginx -s reload
```

**Comment by sunsheeppoplar** [comment]
Seeing the same behavior as @murdoch and @rykov
