### ISSUE TITLE
Package version mismatch with Bower

### ISSUE THREAD

**Issue by davej** [tenex/rails-assets#240]
[Angular Classy](https://github.com/davej/angular-classy) has the following versions listed with rails assets: 0.4.0, 0.4.1, 0.4.2, 1.0.0, 1.0.0.beta.7, 1.0.1, 1.1.0, 1.1.1

The 1.0.1 and 1.1.1 tags/releases were deleted months ago and should not appear as valid versions. For example, if I query the package with bower then I get the following versions:

```
Available versions:
  - 1.1.0
  - 1.0.0
  - 1.0.0-rc.2
  - 1.0.0-rc.1
  - 1.0.0-beta.8
  - 1.0.0-beta.7
  - 1.0.0-beta.7
  - 1.0.0-beta.6
  - 1.0.0-beta.6
  - 1.0.0-beta.5
  - 1.0.0-beta.5
  - 1.0.0-beta.4
  - 1.0.0-beta.3
  - 1.0.0-beta.3
  - 1.0.0-beta.2
  - 1.0.0-beta.2
  - 1.0.0-beta.1
  - 0.4.2
  - 0.4.2
  - 0.4.1
  - 0.4.0
```

I would expect the rails-assets packages to only show valid and currently existing tags/releases. This caused issues when upgrading the angular-classy package with asset pipeline: https://github.com/davej/angular-classy/issues/44.

**Comment by sheerun** [comment]
On other hand other devs expect Rails-Assets' packages to not disappear magically :)

**Comment by davej** [comment]
I don't use Rails-Assets but is it possible for me to remove invalid versions? In my case, I added the 1.0.1 and 1.1.1 tags before the project was even open-sourced, when I open sourced the project I removed those tags and started with 0.x to indicate that the project was pre-release.

This means that when Rails Assets tries to download the latest version, it will download a version of angular classy that was released over a year ago before the project was public.

Any suggestions on how to fix this? I'd prefer not to push a new 1.1.1 release that is exactly the same as the current 1.1.0 release but perhaps that is my only solution?

**Comment by sheerun** [comment]
I think we could try removing removing such packages from index, while leaving them as gems.

This way old installations would work, while new installations would install 0.x packages.

**Comment by davej** [comment]
Is this something I can do or does one of the Rails-Assets team need to do it?

To be clear, v1.0.0 and v1.1.0 are fine. While, v1.0.1 and v1.1.1 are old invalid releases.

**Comment by sheerun** [comment]
Only we can do it.

**Comment by davej** [comment]
Great, do I have to request it somewhere or is this open issue enough?

**Comment by sheerun** [comment]
It's enough. I'll handle it soon.

**Comment by davej** [comment]
Cheers.

**Comment by sheerun** [comment]
Done :)
