### ISSUE TITLE
Another issue with including scss files conflicting with asset pipeline in rails

### ISSUE THREAD

**Issue by pencilcheck** [tenex/rails-assets#241]
I have made a report here https://github.com/rails/sass-rails/issues/320, but in addition to the troubles in my older issues, I felt like we should be given an option to choose between css/scss versions, because with scss there is always the trouble of incompatibility issue with asset pipeline and conflicts with rails native gems and the preprocessor tools used in the library.

In this case it is probably sass's issue, but for a developer it is simply wasting time. Would be nice to hear back from the dev if this make sense or not.

**Comment by sheerun** [comment]
We went back and forth with this feature and my final judgement is that's not worth it.

Implementing this can introduce backward incompatibilities or we'd need to double number of gems hosted.
