### ISSUE TITLE
Support for caret version numbers

### ISSUE THREAD

**Issue by iainbeeston** [tenex/rails-assets#242]
Bower packages can have dependencies specified using a caret in the version, eg `^0.6.2`, which allows the first non-zero digit to change only (details [here](https://github.com/npm/node-semver#caret-ranges-123-025-004)).

At present these aren't converted to rubygems version constraints by rails-assets, and so the build fails:

```
rake aborted!
There was a Gem::Requirement::BadRequirementError while loading rails-assets-textAngular.gemspec: 
Illformed requirement ["~> ^ 1.2.0"] from
  /tmp/d20150219-16574-18415eg/rails-assets-textAngular.gemspec:18:in `block in <main>'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.9/lib/bundler.rb:394:in `rescue in eval_gemspec'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.9/lib/bundler.rb:383:in `eval_gemspec'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.9/lib/bundler.rb:354:in `block in load_gemspec_uncached'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.9/lib/bundler/shared_helpers.rb:44:in `chdir'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.9/lib/bundler/shared_helpers.rb:44:in `block in chdir'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.9/lib/bundler/shared_helpers.rb:43:in `chdir'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.9/lib/bundler.rb:349:in `load_gemspec_uncached'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.9/lib/bundler.rb:339:in `load_gemspec'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.9/lib/bundler/gem_helper.rb:31:in `initialize'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.9/lib/bundler/gem_helper.rb:13:in `new'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.9/lib/bundler/gem_helper.rb:13:in `install_tasks'
/usr/local/rvm/gems/ruby-2.0.0-p598@global/gems/bundler-1.7.9/lib/bundler/gem_tasks.rb:2:in `<top (required)>'
/tmp/d20150219-16574-18415eg/Rakefile:1:in `require'
/tmp/d20150219-16574-18415eg/Rakefile:1:in `<top (required)>'
(See full trace by running task with --trace)
```

It should be straightforward to convert these to rubygems compatible version ranges. The semver readme (linked previously) gives several examples of how to do this.

**Comment by sheerun** [comment]
We should handle it well. What version of `textAngular` are you trying to build?

**Comment by iainbeeston** [comment]
textAngular 1.3.11

**Comment by sheerun** [comment]
Thanks for reporting this issue. It should be fixed now.

**Comment by iainbeeston** [comment]
Excellent, thanks - I'll try it out later today

**Comment by iainbeeston** [comment]
Hey I think there's a bug in this. In textAngular 1.3.11, [package.json](https://github.com/fraywing/textAngular/blob/cb1c7cea5dfc2a72eac2ce90b6fb062404e45e91/bower.json#L25) specifies these dependencies:

``` json
  "browserDependencies": {
    "angular": "^1.2.x",
    "rangy": "^1.3.0",
    "bootstrap": "^3.0.x",
    "font-awesome": "^4.0.x"
  },
```

But the gemspec for textAngular 1.3.11 has this:

``` ruby
  spec.add_dependency "rails-assets-angular", ">= 1.2.0", "< 2"
  spec.add_dependency "rails-assets-bootstrap-css-only", ">= 3.0.0", "< 4"
  spec.add_dependency "rails-assets-font-awesome", ">= 4.0.0", "< 5"
  spec.add_dependency "rails-assets-rangy", ">= 1.2.0", "< 2"
```

Note that for rangy, package.json specifies rangy `^1.3.0` but the gemspec specifies `>= 1.2.0 < 2". By my understanding, the gemspec should instead specify`>= 1.3.0 < 2".

I've tried refreshing the build via the rails-assets website and then reinstalling the gem, but it still has this.

**Comment by sheerun** [comment]
Bower looks into `bower.json`, not `package.json`: https://github.com/fraywing/textAngular/blob/v1.3.11/bower.json
