### ISSUE TITLE
Asset not found

### ISSUE THREAD

**Issue by besi** [tenex/rails-assets#243]
I am using the select2 gem with Rails Assets:

``` ruby
source 'https://rails-assets.org' do
  gem 'rails-assets-select2'
end
```

I did use the `select2-rails` gem beforehand so everything is set up correct already and the component is generally working but the Clear icon "![clear-icon](https://cloud.githubusercontent.com/assets/160412/6843263/9d8eb18a-d3a1-11e4-91d9-baff7cfed0d3.png)" is missing:

![screen shot 2015-03-26 at 10 11 02](https://cloud.githubusercontent.com/assets/160412/6843170/737b8f04-d3a0-11e4-81ee-84c4947398bf.png)

Now my browser tells me that the asset is missing:

> **[Error]** Failed to load resource: the server responded with a status of `404` (Not Found)  
> - `select2-spinner-ac4dd7c66ba3e7ef0cf2795b50582c93.gif`
> - `select2-b4cd0ce12d02a8e3dd2c110a1b364e6e.png`

In the IDE, I can see the images:

![images](https://cloud.githubusercontent.com/assets/160412/6843229/3bae8742-d3a1-11e4-9503-c83e248161fe.png)

**Comment by sheerun** [comment]
Did you precompile assets? Can you post github link to rails application that reproduces this?
