### ISSUE TITLE
How to include a package with a . in the name?

### ISSUE THREAD

**Issue by ProGM** [tenex/rails-assets#244]
I'm trying to include this package:
https://github.com/wysiwygjs/wysiwyg.js

I tried:
So I tried:

``` ruby
source 'https://rails-assets.org' do
    gem "rails-assets-wysiwyg.js"
end
```

And:

``` ruby
source 'https://rails-assets.org' do
   gem "rails-assets-wysiwygjs"
end
```

And also:

``` ruby
source 'https://rails-assets.org' do
    gem "rails-assets-wysiwyg_js"
end
```

**Comment by sheerun** [comment]
This package is not in bower's registry. You need to register it.

**Comment by ProGM** [comment]
@sheerun I opened an issue in their repo. They added a version number to that package.
What's exactly missing?

Here's the package on bower.io:
http://bower.io/search/?q=wysiwyg.js

Here's the bower file:
https://github.com/wysiwygjs/wysiwyg.js/blob/master/bower.json

It seems that the version is defined, but I get:
`wysiwyg.js has no versions defined. Please create an issue in component's repository.`
