### ISSUE TITLE
Refresh textAngular build

### ISSUE THREAD

**Issue by bopm** [tenex/rails-assets#245]
I manage to [fix semver for textAngular](https://github.com/fraywing/textAngular/pull/600#issuecomment-86733686) but build continue to fail due version of textAngular stay the same. Can you manually refresh that?

**Comment by mikeatlas** [comment]
According to semver rules you could just do a patch-numbered release... eg v1.3.12 in your case?

**Comment by bopm** [comment]
My problem that I have nothing to do with textAngular, so I am pretty sure that my PR for version change will be not accepted so easily :trollface:

**Comment by sheerun** [comment]
I implemented refresh button, so you can do it yourself. Let me know if it works.

Remember to remove gems from your machine first, as bundler caches them..

**Comment by iainbeeston** [comment]
textAngular hasn't yet been released with this change - the latest bower release (1.3.11) doesn't have [your changes](https://github.com/fraywing/textAngular/pull/600), so refreshing isn't going to help.

**Comment by bopm** [comment]
My bad. Will ask maintainer for 1.3.12.
