### ISSUE TITLE
Pre-release tagged package fails to build, but has safe semver number?

### ISSUE THREAD

**Issue by mikeatlas** [tenex/rails-assets#246]
Hi,

I'd like to use the [`Leaflet.makercluster#0.4.0-hotfix.1`](https://github.com/Leaflet/Leaflet.markercluster/releases/tag/v0.4.0-hotfix.1) tagged release of this  component thanks to https://github.com/Leaflet/Leaflet.markercluster/issues/394, but it fails to add as a component with the following error:

```
rake aborted!
There was a ArgumentError while loading rails-assets-leaflet.markercluster.gemspec: 
Malformed version number string ~> 0.4.0.hotfix.1 from
  /tmp/d20150327-7368-ighaep/rails-assets-leaflet.markercluster.gemspec:8:in `block in <main>'
```

From gemspec docs I would have thought it would have worked: http://guides.rubygems.org/patterns/#prerelease-gems _Other prerelease version numbers might include 2.0.0.rc1, or 1.5.0.beta.3. It just has to have a letter in it, and you’re set._

Did I miss something, or did the package miss something in it's semantically versioned hotfix pre-release tag? As far as Bower packages go, [the `-` for pre-release tags is supported](https://github.com/bower/bower/issues/782).

Thanks,
Mike

**Comment by mikeatlas** [comment]
Also, per semver.org:

A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

**Comment by sheerun** [comment]
Thank you for noticing this bug! It's now fixed and deployed.

I also built this gem version from web interface.

**Comment by mikeatlas** [comment]
Thank you!
