### ISSUE TITLE
Semver pre-release dashes still treated weirdly?

### ISSUE THREAD

**Issue by mikeatlas** [tenex/rails-assets#247]
Maybe this is ignorance on my part, but per https://github.com/rails-assets/rails-assets/issues/246, I would have thought that my gem file entry:

`gem 'rails-assets-leaflet.markercluster', "0.4.0-hotfix.1"`

would work, but I get this error in on `bundle install`:

```
Could not find gem 'rails-assets-leaflet.markercluster (= 0.4.0.pre.hotfix.1) ruby' in
the gems available on this machine.
```

Where's that extra `.pre.` coming from? I can work around this by using
`gem 'rails-assets-leaflet.markercluster', "0.4.0.hotfix.1"` 
for now, but I suppose if there actually were also a hotfix build labelled `0.4.0-pre.hotfix.1` for the package I wanted, I could end up pulling the incorrect hotfix tagged build as a result. Or maybe it would try to pull `0.4.0.pre.pre.hotfix.1`. I can't tell for sure.

I think, with your regex, ["One or more letters in the gem version"](http://guides.rubygems.org/patterns/#prerelease-gems) should be interpreted as "One or more non-[0-9]\* characters, which includes `.` _and_ `-` afterward. Note that patches could then be any of the following, and be lower-precedence than their side by side counterpart:

`1.0.0-beta.1` `<` `1.0-beta-1` `<` `1.0`
`1.0.0.beta.1` `<` `1.0.beta-1` `<` `1.0`
`1.0.0beta1` `<` `1.0beta1` `<` `1.0`

**Comment by sheerun** [comment]
That's how rubygems work. It replaces `-` with `.pre.`. Just use `0.4.0.hotfix.1`

**Comment by mikeatlas** [comment]
Ok. Good enough for me.
