### ISSUE TITLE
How to ingest NPM packages??

### ISSUE THREAD

**Issue by andyl** [tenex/rails-assets#249]
Some JS utilities only come as NPM packages.  (as far as I can tell...)  Here's an example - Radium https://github.com/FormidableLabs/radium

For NPM packages like this, I have to manually download the JS to vendor/assets/javascripts.  :-(

Couple of questions:
1) why are some JS libs packaged with bower, and some with NPM?
2) for NPM packages like Radium, is there a better solution than manual download??

Thanks in advance, and thanks for RailsAssets!

**Comment by sheerun** [comment]
It's not possible to consume NPM packages. Rails Assets is only rubygems-bower proxy :)

I guess you can use something like: https://github.com/browserify-rails/browserify-rails

**Comment by andyl** [comment]
I did look into browserify-rails.  The config and NPM setup was so complicated I prefer manual download.  Thanks again for RailsAssets - very simple and it just works.
