### ISSUE TITLE
Description field

### ISSUE THREAD

**Issue by sheerun** [tenex/rails-assets#25]
I think:
1. it should be fetched from repository description with fallback to readme
2. if fetched from page body, it should be sanitized

**Comment by sheerun** [comment]
@jandudulski What do you think? Readme only, or repo description with fallback to readme?

**Comment by jandudulski** [comment]
Repo description sounds ok.

**Comment by teamon** [comment]
Repo description sounds like one more github api hit, one more place for error handling, one more place for failure and one more place that slows down whole convert process. Rails Assets is not intended to be bower packages browser, there is one already.

**Comment by sheerun** [comment]
I thought `.git/description` is always in sync with github. This need
reconsidering indeed.

**Comment by sheerun** [comment]
We're now using information from bower registry to fetch description.
