### ISSUE TITLE
Allow linking to rails asset on rails-assets.org

### ISSUE THREAD

**Issue by d4rky-pl** [tenex/rails-assets#250]
Right now rails-assets.org doesn't have either History.js or even simple shebang to allow linking to either search result or certain asset.

The simplest version could be just `#q=foo` which would pre-fill search bar with `foo`.

**Comment by sheerun** [comment]
PR is welcome :)

**Comment by hut8** [comment]
@d4rky-pl check out the work that @joshjordan did which was just deployed :smile:
