### ISSUE TITLE
Problem with bower packages that end in .js

### ISSUE THREAD

**Issue by hadees** [tenex/rails-assets#251]
Recently I've had problems with bower packages that end in `.js` not having their javascript included correctly.  The two examples I have are `spin.js` and `lunr.js`.  It looks like it started happening today.

**Comment by sheerun** [comment]
just use full name `#= require spin.js.js`

**Comment by thetimbanks** [comment]
@sheerun Thanks. This worked great for me. I was trying to require `system.js` and needed to use `system.js.js` instead.

**Comment by snow** [comment]
@sheerun thanks.

this problem happens only with sprocket 3.0+. it was fine to just //= require xx.js back in 2.x

**Comment by brust** [comment]
:+1:
