### ISSUE TITLE
Weird duplicated loading using sprockets 3.x

### ISSUE THREAD

**Issue by allaire** [tenex/rails-assets#252]
When I'm using Sprockets 3.x, I'm getting all sort of javascript errors saying some functions are undefined or other stuff loaded twice. When I revert back to 2.x, everything start to work again magically.

Javascripts loaded using rails-assets are causing the trouble, because on our frontend site, we don't use anything from rails-assets.

Any hints?

Thanks!

**Comment by sheerun** [comment]
I don't know how to reproduce you issue. For gems that end with `.js`, try something like following:

```
//= require uri.js.js
```

**Comment by funwhilelost** [comment]
@sheerun I verified that adding .js.js works for these gems.  I added more detail to the other, referenced issue: https://github.com/sstephenson/sprockets/issues/720
