### ISSUE TITLE
Packages with script in subdirectory return Sprockets::FileNotFound

### ISSUE THREAD

**Issue by Genkilabs** [tenex/rails-assets#254]
I'd really like to use this for RWD-Table-Patterns ( https://github.com/nadangergeo/RWD-Table-Patterns ) but the js and css are nested in subdirectories `/dist/js/rwd-table.js` and `/dist/css/rwd-table.css` respectively.
I have tried a whole variety of paths in my //= require, even including variations of the double .js (rwd-table.js.js) recently recommended in another ticket but no luck. I always come up with the `Sprockets::FileNotFound` error.
Using Ruby 2.2.2. Rails 4.0.13

**Comment by sheerun** [comment]
You can see available files by clicking version of package on our WWW interface.
