### ISSUE TITLE
DH keypair error with JRuby

### ISSUE THREAD

**Issue by krazyjakee** [tenex/rails-assets#255]
I'm seeing a certificate problem in JRuby 1.7.19 (2.0.0p598) when bundler hits
https://gist.github.com/nertzy/ad266b8049d161b8cfbd

See also here: https://github.com/heroku/heroku-buildpack-ruby/issues/365

**Comment by sheerun** [comment]
I think we updated certificates since then. Let me know if it still doesn't work.

**Comment by mrrooijen** [comment]
The issue still persists today.

https://github.com/bundler/bundler/issues/3588

Using `http` works. Using `https` doesn't work and results in `Java::JavaLang::RuntimeException: Could not generate DH keypair`.

/cc @headius

**Comment by ravn** [comment]
It still doesn't work.  Changing from https to http makes it work.

**Comment by hut8** [comment]
@ravn Can  you check to see if it works on the mirror at https://rails-assets.tenex.tech ?

**Comment by ravn** [comment]
It appears to work correctly.  This is with jruby 9.0.5.0.
