### ISSUE TITLE
Emoji One package has incorrect content

### ISSUE THREAD

**Issue by evoL** [tenex/rails-assets#256]
Recently [Emoji One](https://github.com/Ranks/emojione) was updated to 1.4.0. That update added some SCSS sprites, which are not included in the `main` section of `bower.json`. This seems to have caused Rails Assets to include the sprites _instead_ of the main CSS file referenced by `bower.json`. Earlier versions of Emoji One did not have SCSS sprites and the package was working correctly.
It seems that some kind of autodetection is taking over incorrectly.

**Comment by monttda** [comment]
This is an error from Emoji One the reason You can check it at the references issue in their repo
