### ISSUE TITLE
Duplicate component added

### ISSUE THREAD

**Issue by djreyes** [tenex/rails-assets#257]
I forked the  [`laurihy/angular-payments`](https://github.com/laurihy/angular-payments) repo in order to be able to use Rails Assets. In doing so, I originally added `WorkHands--workhands-angular-payments` but then renamed it to `WorkHands--angular-payments`. Now there are two versions in the Rails Assets directory.
1. How can the `WorkHands--workhands-angular-payments` be removed?
2. The `WorkHands--angular-payments` component points to [`laurihy/angular-payments`](https://github.com/laurihy/angular-payments) instead of [`WorkHands/angular-payments`](https://github.com/workhands/angular-payments). Is that expected because it is a forked version or is that also incorrect?

Thanks!

**Comment by sheerun** [comment]
We don't support removing already added components. You can request rebuilding them by clicking "Rebuild" link from www interface.
