### ISSUE TITLE
Question on working with private NPMs

### ISSUE THREAD

**Issue by akshayrawat** [tenex/rails-assets#259]
As I understand this, to work with private NPMs one has to do the following:
1. Clone the rails-assets project.
2. Use `rake 'component:convert[jquery,2.0.3]'` from that project to convert a Bower package into Rubymine.
3. Publish it to their private rubygems registry.

Step 2. could have been simpler if `rails-assets` was available as a gem binary. So one would then install `rails-assets` as a gem and then run `rails-assets convert '[jquery,2.0.3]'` to convert bower packages anywhere in the system.

The other option for users is to run their own private rails-assets.org. However I'm not sure if most folks would undertake that if they just have one or two private NPMs. I'm not aware of a pre hosted private version of rails-assets.org which is available as a service.

Is my understanding correct? I'm just raising this issue to serve as a note for future users who want to do something similar. Thanks in advance.

**Comment by sheerun** [comment]
You probably mean private bower, as rails-assets is a bower proxy.

For private registry you'd need need to run separate instance of rails-assets, but there's no ready solution. `rails_assets` binary would be nice tool. You could download gems directly from github.

**Comment by akshayrawat** [comment]
Thanks for that answer, I'm going to close this issue now.
