### ISSUE TITLE
Development, scss and config.assets.debug = false

### ISSUE THREAD

**Issue by y4ck** [tenex/rails-assets#260]
When using application.css.scss and @import everything works fine, when asset.debug is set to false.
But when it is set to true, the file extension should be removed.
i.e.
sth. like this works when assets.debug is set to false:
*@import "plugins/jquery.mCustomScrollbar.css"; *
but when its set to true css is not included (because it has got extension). It will be ok:
*@import "plugins/jquery.mCustomScrollbar"; *

**Comment by sheerun** [comment]
I'm not sure what you mean. What is the issue with rails-assets? What do you want us to change?

**Comment by hut8** [comment]
Closing due to lack of feedback for nearly one year.
