### ISSUE TITLE
Can not add component that is made up of only depnedancies

### ISSUE THREAD

**Issue by ShadowBan** [tenex/rails-assets#264]
We currently can not load some bower packages into Rails Assets that consist of solely dependencies.  These are convenience packages and would be helpful.  

The issue comes down to an error thrown at:

 https://github.com/rails-assets/rails-assets/blob/45d3514f8d4ac88526e2570c82ba322fabdc28d6/app/models/build/converter.rb#L155 

This checks to see if there are any assets in the asset path but halts if it finds none, and does not check if their are dependencies to put in the package as well. 

Example project that only has dependancies: https://github.com/PolymerElements/paper-elements

I am curious if this is a pattern rails-assets is interested in supporting.

**Comment by sheerun** [comment]
Yes. Please send a PR that fixes that behavior + test for it in `test/builder_spec.rb` :)

**Comment by ShadowBan** [comment]
Thanks I will give this a go.

**Comment by joshjordan** [comment]
@ShadowBan any word on this?

**Comment by ShadowBan** [comment]
I was never really able to get around to this.  We ran into other blockers that made the rails asset pipeline less than ideal when dealing with web components.  We ended up pulling out rails-assets and the rails asset pipeline in general and replacing it with npm / [webpack](https://webpack.github.io/).

**Comment by joshjordan** [comment]
Thanks.

**Comment by joshjordan** [comment]
I realized my thanks might've sounded facetious. Sorry! It is not. Thank you for updating us.

**Comment by ShadowBan** [comment]
No worries @joshjordan!

**Comment by hut8** [comment]
No new development planned, so closing.
