### ISSUE TITLE
Question - disable inclusion of a component's dependencies?

### ISSUE THREAD

**Issue by aeksco** [tenex/rails-assets#267]
**Question:** Is it possible to include a component though Rails-Assets while manually disabling the recursive inclusion of its dependencies?

For example, in my `Gemfile` I currently have:

``` ruby
source 'https://rails-assets.org' do
  gem 'rails-assets-bootstrap-sass'
  gem 'rails-assets-bootstrap-switch'
  ...
end
```

Which is great, but [Bootstrap-Switch](bootstrap-switch.org) has the following dependencies (from [bower.json](https://github.com/nostalgiaz/bootstrap-switch/blob/master/bower.json)):

``` json
  "dependencies": {
    "bootstrap": ">=2.3.2",
    "jquery": ">=1.9.0"
  },
```

Thus my `Gemfile.lock` lists `rails-assets-bootstrap (3.3.5)` as a dependency for **Bootstrap-Switch** - a dependency that is effectively satisfied by the inclusion of [Bootstrap SASS](https://github.com/twbs/bootstrap-sass).

**It would be ideal to have the option to manually disable the inclusion of unwanted dependencies to mitigate `Gemfile.lock` sprawl.**

I would _like_ to do something along the lines of:

``` ruby
source 'https://rails-assets.org' do
  gem 'rails-assets-bootstrap-sass'
  gem 'rails-assets-bootstrap-switch', require_dependencies: false
  ...
end
```

thus affording users the ability to thoughtfully exclude redundant dependencies.

If this is an acceptable use case I would be thrilled to open a PR, though I would rather ask before going to the trouble.

**Comment by sheerun** [comment]
Unfortunately it's not possible. Even if we wanted to. It's more like bundler issue than rails-assets.

You can try to request this feature with them (but I bet someone already did it).
