### ISSUE TITLE
Main assets

### ISSUE THREAD

**Issue by xuorig** [tenex/rails-assets#268]
I get this post-install message when running bundle install
`
This component doesn't define main assets in bower.json.
Please open new pull request in component's repository:
https://github.com/twitter/twitter-text
`

But the bower file: https://github.com/twitter/twitter-text/blob/master/bower.json does define main assets. Anybody knows what is going on here?

**Comment by sheerun** [comment]
Latest release doesn't have bower.json. You need to ask author to release it. https://github.com/twitter/twitter-text/tree/f481c041eceb13245a0aa501c50c6c9c91f5b90d
