### ISSUE TITLE
No include instructions for Autolinker.js

### ISSUE THREAD

**Issue by ghost** [tenex/rails-assets#269]
Something seems off with [Autolinker.js](https://github.com/gregjacobs/Autolinker.js) -- all I see is this `Rebuild` link and despite having rebuilt it I still can't see the include instructions.

Thank you!

**Comment by sheerun** [comment]
I fixed rails-assets so it shows instructions for gems ending with `.js`. Following works for me:

```
//= require Autolinker.js
```

**Comment by ghost** [comment]
Much obliged!

**Comment by ghost** [comment]
Only `//= require Autolinker.js/Autolinker.js` works over here though.
