### ISSUE TITLE
Inconsistent version numbers in assets

### ISSUE THREAD

**Issue by mcavaliere** [tenex/rails-assets#270]
When installing some modules, I'm seeing the correct version number in the generated rails-asset-\* gem folder, but the actualy javascript file itself has the incorrect one. 

Example: 

``` ruby
source 'https://rails-assets.org' do
  # Problem occurs both with and without the version number
  gem 'rails-assets-jasmine-jquery', '2.1.0' 
end
```

The above code will generate a gem folder named "rails-assets-jasmine-jquery-2.1.0" (correct), but within that folder, opening /app/assets/javascripts/jasmine-jquery/jasmine-jquery.js reveals the version "2.0.7" up top in the comments.

**Comment by mcavaliere** [comment]
After deeper inspection, I realized that this is on their side. In their tag for "2.1.0" their actual source file has the version "2.0.7" in the comments. 

To be forward thinking, this might be a good thing to mention on rails-assets.org. I bet there are a number of libs that have this problem, so it'd probably be helpful to keep people aware of it.

**Comment by mcavaliere** [comment]
Do you guys have a suggested workaround?

**Comment by sheerun** [comment]
It's their issue, not ours :) You can fork their repo, add proper tag in your fork, and add it via ww interface.

Or send a PR to their repo
