### ISSUE TITLE
rest api/json format data

### ISSUE THREAD

**Issue by pravi** [tenex/rails-assets#271]
rubygems.org provides a rest api to access gems and has json files for each gem like
http://rubygems.org/api/v1/gems/vegas.json

Can this be provided on rails-assets.org as well? 

http://stackoverflow.com/questions/31801736/can-i-get-gem-details-as-json-on-rails-assets-org-like-in-rubygems-org

**Comment by sheerun** [comment]
If someone implements it, yes :) Currently, no

**Comment by hut8** [comment]
Update: not currently actively working on this. The gemwatch thing is really cool, and I would like to implement it. Removed "pending deploy" because #302 does not actually provide this endpoint.

**Comment by stereodenis** [comment]
@hut8 do you need any help on it?

**Comment by hut8** [comment]
A pull request would be welcome!
