### ISSUE TITLE
no versions defined?

### ISSUE THREAD

**Issue by thomasjachmann** [tenex/rails-assets#273]
I just tried to add https://github.com/nelsoncash/angular-ripple but got the error "angular-ripple has no versions defined". I can't see what's wrong with the component:
- it's available via bower: http://bower.io/search/?q=angular-ripple
- it has a proper bower.json with a version: https://github.com/nelsoncash/angular-ripple/blob/master/bower.json#L3

I'd like to create an issue on angular-ripple's repository but I don't know what they should change. Any hints?

**Comment by sheerun** [comment]
bower doesn't care about version in bower.json. package needs semver git tags.
