### ISSUE TITLE
Service down?

### ISSUE THREAD

**Issue by jasdeepsingh** [tenex/rails-assets#274]
I'm getting 500 errors willy-nilly from the service. 

<img width="970" alt="screen shot 2015-08-14 at 1 18 51 pm" src="https://cloud.githubusercontent.com/assets/603900/9279649/dc4e83c4-4286-11e5-8178-f0c9defaa250.png">

PS: Also getting timeouts from the dependency endpoint.

Anything, that I can help out figure/resolve this issue?

**Comment by jasdeepsingh** [comment]
Update: It's working now, But i'm quite certain the willy-nilly behaviour will show back up again. If there's a stack trace, I may have cycles to help out.

**Comment by charliewilkins** [comment]
Seems to be down right now.

**Comment by charliewilkins** [comment]
![image](https://cloud.githubusercontent.com/assets/978754/11252273/24bdd0d4-8dea-11e5-8c55-2d8607d92871.png)

response:

```
[
```

**Comment by v9n** [comment]
It is intermientent. Sometime it works sometime it doesn't :(.

I think we should just ditch those kind of stuff and switch to Gulp https://viget.com/extend/gulp-rails-asset-pipeline

**Comment by jandudulski** [comment]
Duplicate #195

**Comment by Austin-Qu** [comment]
Not Again???
