### ISSUE TITLE
Interaction between rails-assets & require()

### ISSUE THREAD

**Issue by loganb** [tenex/rails-assets#275]
Hello, 

I'm trying to figure out how to import superagent (https://github.com/visionmedia/superagent) into my Rails app. It barfs when I include "//= require superagent/lib/client" in application.js because it uses "require(…)" to pull in dependencies (https://github.com/visionmedia/superagent/blob/master/lib/client.js#L5). After googling around, I can't figure out how to handle this (since I don't fully understand how JS modules are supposed to work in the browser). 

Can you share any thoughts on how this is supposed to work? It seems like there's an implied dependency here or some functionality is missing, but I'm not sure which.

**Comment by sheerun** [comment]
You need to use something like babel + npm instead of rails-assets + sprockets

**Comment by venticco** [comment]
@loganb You could try to replace sprockets with Webpack, then you can use `require()` for managing your JS files:
https://medium.com/brigade-engineering/setting-up-webpack-with-rails-c62aea149679
https://reinteractive.net/posts/213-rails-with-webpack-why-and-how

**Comment by loganb** [comment]
Got it, ok, thanks!
