### ISSUE TITLE
Chart.js not working

### ISSUE THREAD

**Issue by jasonsilberman** [tenex/rails-assets#276]
I am having trouble using `rails-assets-Chart.js` in my rails project.

When I run:

```
//= require Chart.js
```

I get this error:

```
couldn't find file 'Chart.js' with type 'application/javascript'
```

I am using other "gems" from rails-assets just fine but Chart.js just won't work. Could it be because it has  `.` in its name that is causing the autoloading not to work?

Thanks

**Comment by pvenky** [comment]
+1 I have the same issue while using Chart.js and angular-chart.js (installed using bower to lib/assets/bower_components)

**Comment by claycarpenter** [comment]
I'm seeing the same issue with `typeahead.js`. I too wonder if it's because of the `.` in the name.

Are there counter examples where bower packages with `.`s in the name do work with Rails Assets?

**Comment by jasonsilberman** [comment]
Yes, I am assuming the `.` is causing the problem.

**Comment by fritzblue** [comment]
+:100: Started happening after upgrade to Rails 4.2 (for any dependency with a `.` in the name) — When can we expect this bug to be fixed?

**Comment by iamdionysus** [comment]
I had the same issue with Chart.js as well. I just did the monkey patch and it's working. The problem is rails-assets gem will install Chart.js.js to require Chart.js/Chart.js. It sounds confusing but go to the actual gem folder to check it out. So, I changed the require part to this, and it works.

```
//= require Chart.js.js
```

**Comment by monttda** [comment]
Is is not possible at the moment to Make that fix on rails-assets-Chart.js but there is another solution if you check on Rail Assets for existing gems and you search chartjs (without the dot) You will see that there is an existing gem of Chart.js but called rails-assets-chartjs so that should work. For any other gems that only exists as rails-assets-XXXX.JS please just require them in the application.js file as 

```
//= require XXXX.js.js
```

instead of

```
//= require XXXX.js
```

**Comment by sheerun** [comment]
In other words, you always use:

```
//= require NAME_OF_PACKAGE.js
```

Even if NAME_OF_PACKAGE ends with `.js`.
