### ISSUE TITLE
Converting source files for using properly paths

### ISSUE THREAD

**Issue by gkopylov** [tenex/rails-assets#277]
Hi there!

I am trying to use rails-assets for material design lite framework but encountered some problem with assets paths. Because I'd like to use different color scheme then default, I have included(i.e. imported) source files of mdl library(not already compiled material-design-lite.scss in the root) and changed palette colors in variables. But the problem is that they use hardcoded paths in their scss assets(i.e. url('images/'... for example) and it seems that they wouldn't change that( https://github.com/google/material-design-lite/issues/258 ). So maybe it would be better to convert paths in source files also?

**Comment by monttda** [comment]
Hi @gkopylov  Could You give me a more detailed explanation on this? :) also PR are always welcome

**Comment by gkopylov** [comment]
Hi @monttda, thank you for your reply :-) 

I suggest to convert hardcoded assets path in src files too. So any hardcoded `url` in src files will become to `asset-url`.

But the problem has already gone since this commit https://github.com/google/material-design-lite/commit/e0fd7ee59b5f3c9751aa0889f09bac4d4c1488c0 They create variable `$image_path` for that.
