### ISSUE TITLE
Support for overriding main that is missing or incorrect in bower.json

### ISSUE THREAD

**Issue by mfdj** [tenex/rails-assets#278]
When a library author — like [ic-ajax](https://github.com/instructure/ic-ajax/issues/13) — is obstinate about not specifying a `main` key in bower.json is there a workaround to requiring it's files?

Realizing this was a longshot I tried `#= require ic-ajax/dist/globals/main` to no avail.

**Comment by teamon** [comment]
@mfdj You should be able to require any file, e.g.

``` js
//= require moment
//= require moment/lang/en-gb
```

You might want to try `gem open rails-assets-ic-ajax` and see the `vendor/assets` content for available files,

**Comment by iabdulin** [comment]
it would be nice to document this option on the homepage

**Comment by dreyks** [comment]
what about https://github.com/vitalets/x-editable package?
when I do `cd `bundle show rails-assets-x-editable`` a file that i need appears at `app/assets/stylesheets/x-editable/dist/bootstrap3-editable/css/bootrstrap-editable.scss`
doing `//= require x-editable/dist/bootstrap3-editable/css/bootstrap-editable` doesn't work. How can I include this file?

**Comment by dreyks** [comment]
well actually never mind, it works. Maybe there was a typo somewhere, but `//= require x-editable/dist/bootstrap3-editable/css/bootstrap-editable` does exactly what is needed
