### ISSUE TITLE
Tests randomly fail

### ISSUE THREAD

**Issue by porada** [tenex/rails-assets#28]
After moving back to Travis (#27), some tests randomly fail (while passing locally):

https://travis-ci.org/rails-assets/rails-assets/builds/11654743
https://travis-ci.org/rails-assets/rails-assets/builds/11654181

It’s the same commit (e4ae792a530f9bc62c2de1de5bb48f32cf7711e3). :crying_cat_face: 

Judging by the error code, it might be an error while connecting to Bower. My suggestion is to perform up to 3 trials of building a package in order to pass the test.

**Comment by sheerun** [comment]
No way. It's better to disable those tests until they're fixed.

**Comment by teamon** [comment]
They are not broken, this is clearly a network issue. And mock are not an option at all.

**Comment by sheerun** [comment]
Thests fail on Travis, and this issue needs to be addressed one or other way. This should be reopened.

**Comment by porada** [comment]
It looks like updating Bower [fixed the issue](https://travis-ci.org/rails-assets/rails-assets/builds/11685240).
