### ISSUE TITLE
Problem with rails-assets-masonry

### ISSUE THREAD

**Issue by smaboshe** [tenex/rails-assets#280]
Hello!

I'm using the Rails Assets masonry component (gem 'rails-assets-masonry') in a Rails 4.2.4 project. After installing the component with bundler and requiring the library in application.js, I get the following error (using the Chrome developer tools console):

```
Uncaught TypeError: Cannot read property 'create' of undefined
```

Using masonry via the CDN works fine. Is there a way to verify that the masonry component actually works?

I've created a demo repository to demonstrate my issue:
https://github.com/smaboshe/Chavuma

**Comment by danielmag** [comment]
Also happening with me. I think the problem is that the require should load the packaged version and not the normal one

**Comment by monttda** [comment]
It is an issue of Masonry.  See the issue at their repository https://github.com/desandro/masonry/issues/618#issuecomment-136295697

**Comment by tkhduracell** [comment]
You can use `//= require masonry/dist/masonry.pkgd` to solve this problem, instead of the include specified in https://rails-assets.org/#/components/masonry
