### ISSUE TITLE
Cannot install rails assets

### ISSUE THREAD

**Issue by polskais1** [tenex/rails-assets#281]
Looks like rails-assets.org is down. Any updates on when it might be back up again? Thanks a million!

**Comment by drewhamlett** [comment]
+1

**Comment by allanwgithub** [comment]
+1

**Comment by jpope777** [comment]
+1

**Comment by stefangomez** [comment]
+1

**Comment by trinityXmontoya** [comment]
+1

**Comment by willcosgrove** [comment]
+1 Is there anything we can do to help?

**Comment by bboylilshaw** [comment]
+1

**Comment by jcarlos** [comment]
+1

**Comment by ardeearam** [comment]
+1

**Comment by bartkozal** [comment]
Bartek from Shelly Cloud here. Rails Assets is back online. We had a problem with the connection to our network filesystem from RA virtual servers. We need to do a further investigation what exactly was the issue to prevent situations like this in future. Sorry to everyone for the complications.

**Comment by polskais1** [comment]
Dzięki Bartek!

**Comment by chrisnicola** [comment]
To future is here, situation is back, possibly. Server is down, getting maintenance mode and 504 errors from Shelly Cloud.

**Comment by matthewrudy** [comment]
I think the answer is an easy one click heroku installer. Pushing asset gems to a configured S3 bucket with some crude auth token.
