### ISSUE TITLE
Incorrect range converting with tilda "~" and "x"

### ISSUE THREAD

**Issue by panych** [tenex/rails-assets#284]
Hello. Many thanks to your very useful and awesome project.

Problem: bower `~1.x.x` converts into bundler `~> 1.0.0` which is not correct. `~1.x.x` is actually a valid range (you can test it on http://semver.npmjs.com/ or with "semver" npm module).

```
~1.x.x → ~> 1.0.0 
bower:   ~1.x.x   :=  >=1.0.0 <2.0.0 
bundler: ~> 1.0.0 :=  >=1.0.0 <1.1.0
```

Real example: https://github.com/jeromegn/Backbone.localStorage/blob/v1.1.16/bower.json

`~1.x.x` can be simplified to `~1` but I think rails assets should handle it.

**Comment by hut8** [comment]
This seems resolved based on the commit history, so I'm closing it.
