### ISSUE TITLE
Bower version deprecated

### ISSUE THREAD

**Issue by dwilkie** [tenex/rails-assets#285]
https://github.com/bower/spec/blob/master/json.md#version

rails-assets requires a bower version, but this is deprecated in bower.json

**Comment by sheerun** [comment]
Could you send example repository?

**Comment by dwilkie** [comment]
Sure,

https://github.com/accursoft/caret

Here's the PR to re-add the version which was rejected
https://github.com/accursoft/caret/pull/10

**Comment by sheerun** [comment]
Bower requires git tags for versions (not `version` in bower.json).

The repository you've sent doesn't have git tags.

**Comment by dwilkie** [comment]
ah! ok thanks! I'll ask the owner to deploy tags. Cheers
