### ISSUE TITLE
rails-assets.org is down

### ISSUE THREAD

**Issue by andrewhamon** [tenex/rails-assets#289]
https://rails-assets.org is currently throwing a 504
![screen shot 2015-11-18 at 10 47 33 pm](https://cloud.githubusercontent.com/assets/5134584/11261820/675fbde2-8e46-11e5-9c8e-93510c0dd2dc.png)

**Comment by sevenseacat** [comment]
And any app using rails-assets can no longer be bundled because the gem source cannot be reached.

**Comment by jaybloke** [comment]
Same here.

**Comment by outsmartin** [comment]
Same issue here, is there a mirror available?

**Comment by sheerun** [comment]
Please contact http://monterail.com/ that supports this application

**Comment by jandudulski** [comment]
Duplicate #195
