### ISSUE TITLE
cannot access package from a self-hosted Private Bower server

### ISSUE THREAD

**Issue by aventinesolutions** [tenex/rails-assets#290]
Thanks for the great work.  I think your project Rails Assets can help our enterprise at this moment.  We have our own hosted Private Bower server as well as our own Gem in a Box server, all of this running behind our enterprise VPN.

We have a single Bower package which is proprietary and not open to the public in a private Git repository which we serve from our Private Bower.  How can we configure Rails Assets to use this Bower registry instead of the public one.

I browsed you code quickly but could not find a quick answer.  Sticking in a .bowerrc file with our Private Bower URL (the obvious solution) doesn't work.

Any help is appreciated.

**Comment by teamon** [comment]
The conversion from bower package to gem happens on the server side, so the rails-assets.org server would need to have access to your private registry.

Since we need to conform to the rubygems API, the only piece of information we can pass is the gem name, so unfortunately using private bower repos seems to be impossible to implement at this time.

**Comment by aventinesolutions** [comment]
I have cloned the project and was using the 'rake' task locally to build my gems then I pushed them to our Gem in a Box server:

For example

``` shell
rake 'component:convert[waves]'
gem inabox public/gems/rails-assets-waves-0.7.4.gem --host 'http://my_geminabox:9292/'
```

**Comment by teamon** [comment]
If so, you can just use this gem directly in you Gemfile, right?

**Comment by aventinesolutions** [comment]
Right, but my problem is not with the 'waves' Bower component ... that is public and is publically accessible from bower.io.

My problem is when I try to access a private Bower component on our private bower server:

``` shell`
rake 'component:convert[my-private-package:0.0.20]'

Package my-private-packge:0.0.20 not found
/export/home/matthew/Desktop/workspace/rails-assets/app/models/build/utils.rb:21:in `rescue in bower'
/export/home/matthew/Desktop/workspace/rails-assets/app/models/build/utils.rb:10:in `bower'
/export/home/matthew/Desktop/workspace/rails-assets/app/models/build/converter.rb:124:in `block in install!'
/export/home/matthew/Desktop/workspace/rails-assets/app/models/build/converter.rb:123:in `install!'
/export/home/matthew/Desktop/workspace/rails-assets/app/models/build/converter.rb:52:in `block in process!'
/export/home/matthew/Desktop/workspace/rails-assets/app/models/build/converter.rb:51:in `process!'
/export/home/matthew/Desktop/workspace/rails-assets/app/models/build/converter.rb:25:in `block in run!'
/export/home/matthew/Desktop/workspace/rails-assets/app/models/build/locking.rb:8:in `block in with_lock'
/export/home/matthew/.rvm/gems/ruby-2.0.0-p643@rails-assets/gems/redis-mutex-2.1.1/lib/redis/mutex.rb:81:in `with_lock'
/export/home/matthew/Desktop/workspace/rails-assets/app/models/build/locking.rb:7:in `with_lock'
/export/home/matthew/Desktop/workspace/rails-assets/app/models/build/converter.rb:24:in `run!'
/export/home/matthew/Desktop/workspace/rails-assets/lib/tasks/component.rake:9:in `block (2 levels) in <top (required)>'
/export/home/matthew/.rvm/gems/ruby-2.0.0-p643@rails-assets/bin/ruby_executable_hooks:15:in `eval'
/export/home/matthew/.rvm/gems/ruby-2.0.0-p643@rails-assets/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => component:convert
(See full trace by running task with --trace)

```

**Comment by aventinesolutions** [comment]
I figured it out guys:  From the Bower documentation ... just stick a `.bowerrc` file in my home directory ....

``` javascript
{
  "registry": "http://my_private_bower:5678"
}
``
```

**Comment by teamon** [comment]
I'm glad to hear that :)
