### ISSUE TITLE
rails-assets is down

### ISSUE THREAD

**Issue by reiz** [tenex/rails-assets#292]
I'm getting this error since more than 1 hour: 

```
Could not fetch specs from https://rails-assets.org/
```

Other people have the same issue. See the feed on [Twitter](https://twitter.com/search?f=tweets&vertical=default&q=rails-assets&src=typd).

**Comment by thibaudgg** [comment]
:+1:

**Comment by teamon** [comment]
Today is a bad day. We are working on bringing the site back.

**Comment by joerichsen** [comment]
What's the time horizon for a solution? Ie. minutes, hours, days, or work :-)

Just wanted to know, so that I can plan accordingly.

(I can't deploy my Rails app at the moment)

**Comment by teamon** [comment]
Quick fix - should be matter of minutes (10-15 I'd say) if this issue is the same as earlier today.
Fixing it properly will definitely take some more time :/

**Comment by joerichsen** [comment]
Excellent, thanks a lot :-)

**Comment by thibaudgg** [comment]
Great news! Thanks!

**Comment by teamon** [comment]
Everything should be back to normal. Please let us know in case of any further issues.

**Comment by reiz** [comment]
Thanks :+1:
