### ISSUE TITLE
Doesn't understand bower dependency operator ||

### ISSUE THREAD

**Issue by itkin** [tenex/rails-assets#297]
``` json
"dependencies": {
    "jquery": "~1.11.3 || ~2.1.4"
}
```

seems to keep only the first operand

Current workaround is to fork the gem refactor the bower.json file and rebuild build the component

**Comment by sheerun** [comment]
It's correct. Rubygems doesn't support this operator as well. We have failing test for it: https://github.com/rails-assets/rails-assets/blob/master/spec/models/build/utils_spec.rb#L123 We'll accept a PR.
