### ISSUE TITLE
Contribute to the website?

### ISSUE THREAD

**Issue by chenasraf** [tenex/rails-assets#304]
Sorry if I missed it, but I'm wondering if the front-end website is open source. I'd like to contribute and change 2 things:
1. Sometimes typing in the search is non-indicative. We should add a loading state and a 404 state. Right now they just load and fail transparently and it's not very clear to developers whether rails-assets is catching up with their updates and how fast.
2. I'd like to add the option to bookmark a search query (add a hashbang such as `#!package:my-package` that will prefill the search field and attempt to immediately show the package.

If the source is closed, could this be considered to be done by the staff?

Thank you!

**Comment by sheerun** [comment]
the frontend is hosted with this repository as well. feel free to send a PR
