### ISSUE TITLE
SSL certificate for rails-assets.org will expire soon

### ISSUE THREAD

**Issue by tkawa** [tenex/rails-assets#306]
Are you ready to update?

<img width="424" alt="2016-01-18 17 59 39" src="https://cloud.githubusercontent.com/assets/562433/12387073/4be36e8c-be0d-11e5-8fb1-3f0d3eed5556.png">

**Comment by ppworks** [comment]
:+1:

**Comment by ryumu** [comment]
:+1:

**Comment by ainame** [comment]
:+1:

**Comment by fukajun** [comment]
:+1:

**Comment by jackmcpickle** [comment]
Can you use cloudflare or letsencrypt.org?

**Comment by jandudulski** [comment]
New cert from letsencrypt has just been setup, so we're safe ;)
