### ISSUE TITLE
Assets for bower packages named like "name.js" are generated as "name.js.js"

### ISSUE THREAD

**Issue by joshuap** [tenex/rails-assets#307]
See also: https://github.com/honeybadger-io/honeybadger-js/issues/37. The issue we're having is:
1. Our [bower package](http://bower.io/search/?q=honeybadger) is named "honeybadger.js" (note the .js extension is already in the name).
2. The rails-assets-honeybadger.js gem is generated with the root asset file as "honeybadger.js.js" instead of "honeybadger.js":

![image](https://cloud.githubusercontent.com/assets/474649/12429362/ac70d67c-be9e-11e5-8fda-133e84c97451.png)

Is there a way to make it use just "honeybadger.js"?

**Comment by joshuap** [comment]
Also, I'm not sure where this package is coming from:

![image](https://cloud.githubusercontent.com/assets/474649/12429534/a7d0e35e-be9f-11e5-94fe-12b7e4ad0661.png)

**Comment by sheerun** [comment]
We generate js files by appending ".js" suffing to package name. It is a correct behavior.

You can include this package with `//=require honeybadger.js.js`

**Comment by joshuap** [comment]
I know how to include it, thanks. It's just really counter-intuitive imo. ¯\_(ツ)_/¯

**Comment by sheerun** [comment]
If anything, it's sprockets' issue that it doesn't allow you to just `//=require honeybadger.js` ;/

**Comment by joshuap** [comment]
True, that would be nice. Might be a hard sell though. :) Anyway, just wanted to see if this is something rails-assets could handle more gracefully, since it has confused a few of our customers. Let me know if there's anything I can do to help.

**Comment by sheerun** [comment]
Unfortunately it's not possible. Otherwise we would have manifest name clash for `honeybadger.js` and `honeybadger` packages.
