### ISSUE TITLE
Typekit fonts make mirroring tricky

### ISSUE THREAD

**Issue by hut8** [tenex/rails-assets#309]
I'm setting up a mirror of rails-assets which I plan on supporting (see #291). It seems to work okay except that these two lines cause problems because Adobe makes you whitelist domains of uses:

```
    = stylesheet_link_tag '//cloud.typography.com/6743452/745062/css/fonts.css', media: 'all'
    = javascript_include_tag '//use.typekit.net/jvv3pir.js'
```

https://github.com/rails-assets/rails-assets/blob/master/app/views/layouts/application.html.slim#L8-L9

I find it slightly ironic that a tool that's used to make packaging front-end assets easy would cause me this problem :smile: 

Would you rather this URL be factored out into a configuration option? Or perhaps Google Fonts might provide a less restrictive hosting alternative?

**Comment by sheerun** [comment]
You can't whitelist all the domains with typekit.

Maybe you can try to embed these fonts (woff2 default, and the test as fallback).

Not sure it is legal, though. Perhaps you need to choose different, free font, and embed it

**Comment by teamon** [comment]
@hut8 Good catch! We definitely will need to switch to some other provider or font. 

I passed the topic to our Head of Design @pawelhawrylak :)

**Comment by hut8** [comment]
@sheerun while I do like the embedding method, unfortunately it's illegal :disappointed: 

Here's what I did for now: https://github.com/tenex/rails-assets/commit/8d0482eaa7f796729231d37e6266330cd75b3c29

It would be nice to have a separate header font, but if you don't hate my solution, then I can open a PR. Can you explain the rationale for using both typography.com and typekit?

**Comment by sheerun** [comment]
Font looks pretty

**Comment by sheerun** [comment]
Here is font similar to Whitney: 

http://www.whatfontis.com/Hind-Jalandhar.font?text=WhtneyMdumEcofs

**Comment by hut8** [comment]
Resolved on our fork.
