### ISSUE TITLE
Does not understand versions "0.0.x"

### ISSUE THREAD

**Issue by tallica** [tenex/rails-assets#31]
``` ruby
gem 'rails-assets-selectize'
```

> bundle install

Result:

> Could not find gem 'rails-assets-microplugin (= 0.0.x) ruby', which is required by gem 'rails-assets-selectize (>= 0) ruby', in any of the sources.

https://github.com/brianreavis/selectize.js/blob/master/bower.json#L33

**Comment by sheerun** [comment]
Fixed in #33 + urls as version names
