### ISSUE TITLE
Sprockets::FileNotFound: couldn't find file 'matches-selector'

### ISSUE THREAD

**Issue by dt1973** [tenex/rails-assets#310]
Maybe it's just another one of my silly mistakes, but why can't Sprockets find `matches-selctor.js`?

It's part of `gem rails-assets-packery, "2.0.0.beta1"` which includes `rails-assets-matches-selector` as a dependency. But when doing `//= require matches-selector` or `//= require matches-selector/matches-selector.js` from `application.js` like I'm supposed to, I get:

```
Sprockets::FileNotFound: couldn't find file 'matches-selector' with type 'application/javascript'
```

This despite the existence of `~/vendor/bundle/ruby/2.2.0/gems/rails-assets-matches-selector-1.0.3/`.

**Comment by hut8** [comment]
What about `//= require matches-selector/matches-selector` without the js?

**Comment by dt1973** [comment]
Nope, `couldn't find file 'matches-selector/matches-selector'`.

**Comment by hut8** [comment]
What about `//= require desandro-matches-selector` ?

**Comment by dt1973** [comment]
It worked! Thanks man!
