### ISSUE TITLE
Could not find rails-assets-jquery-2.2.1 in any of the sources

### ISSUE THREAD

**Issue by chrishough** [tenex/rails-assets#311]
Interesting error starting popping up tonight:

```
Could not find rails-assets-jquery-2.2.1 in any of the sources
Run `bundle install` to install missing gems.
```

Gemfile:

```
source 'https://rails-assets.org' do
  gem 'rails-assets-holderjs'
  gem 'rails-assets-linkifyjs'
end
```

**Comment by chrishough** [comment]
_Update_

It only happens with.. 

```
gem 'rails-assets-linkifyjs'
```

**Comment by chrishough** [comment]
I had to run bundle update to fix this... Thoughts as to why?

**Comment by hut8** [comment]
Are you saying that when you ran a command inside of `bundle exec` (like rails or whatever), and it printed the error:

```
Could not find rails-assets-jquery-2.2.1 in any of the sources
Run `bundle install` to install missing gems.
```

Running `bundle install` didn't work, but `bundle update` did?

**Comment by chrishough** [comment]
Correct, I had to run `bundle update` and then bundle install.  It was very odd...

**Comment by hut8** [comment]
What were the gemfile.lock versions for jquery and linkifyjs before and after?

**Comment by chrishough** [comment]
Currently it is using:

```
    rails-assets-holderjs (2.9.3)
    rails-assets-jquery (2.2.1)
    rails-assets-linkifyjs (1.1.7)
      rails-assets-jquery (>= 1.9.0)
```

Before it was using:

```
rails-assets-holderjs (2.9.1) 
```

... I am having a hard time locating the commit where I added linkifyjs

**Comment by hut8** [comment]
Can you give me exact steps to reproduce?

https://rails-assets.org/gems/rails-assets-jquery-2.2.1.gem

That seems to work fine, and it seems to be in the database. Since the server was moved, maybe something else happened but I can't really be sure without more steps.

**Comment by hut8** [comment]
Closing due to lack of feedback.

**Comment by chrishough** [comment]
I am ok with closing, the issue has since disappeared.

**Comment by joshjordan** [comment]
Thanks, @chrishough !
