### ISSUE TITLE
rails-assets is down

### ISSUE THREAD

**Issue by endenis** [tenex/rails-assets#315]
The service is down. I cannot install gems from it :(
The web-site shows this error for a few hours by now:

> This website is under heavy load (queue full)
> 
> We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.

**Comment by mockdeep** [comment]
Ditto, our builds have started failing on this. Tried both rails-assets.org and https://rails-assets.tenex.tech.

**Comment by theprogramer** [comment]
The service is down.
:+1:

**Comment by zero-code-hero** [comment]
Still having issues here as well.

**Comment by theprogramer** [comment]
My DO servers are unstable.
Would it be this?
:tired_face:

**Comment by hut8** [comment]
Hey guys, sorry about the confusion here. Please use this thread for now: https://github.com/tenex/rails-assets/issues/65 -- I realize it's confusing having two repositories but Monterail and I will get that sorted out ASAP, but separately.

@LPiner Can you be more specific?

@theprogramer What do you mean your "DO servers"? 

@jandudulski (or someone else from this repo) can you lock this thread as I've redirected people to the above? Or alternatively, get me access to this one? Thanks :+1:

**Comment by theprogramer** [comment]
DO = Digital Ocean
LOL

**Comment by endenis** [comment]
Okay, I close this thread in order to move the discussion to https://github.com/tenex/rails-assets/issues/65
