### ISSUE TITLE
Can't fetch gems or ping rails-assets.org

### ISSUE THREAD

**Issue by AldanaQuintana** [tenex/rails-assets#322]
Hi. Thanks for the amazing work.

This might not even be a rails-assets issue, but I'd really appreciate some help because I'm lost, and google didn't help me. (Oh my)

I have the following in my Gemfile: 

```
source 'https://rails-assets.org' do
  gem 'rails-assets-chosen'
  gem 'rails-assets-bootstrap-tagsinput'
  gem 'rails-assets-switchery'
end
```

I have two servers in which I deploy the same app. In one of them everything is working like a charm, and in the other, everything worked fine until yesterday.

When I try to deploy the app to this last server it just stops when trying to fetch from rails-assets.org and after a while it exists failing.

I logged in into the server with ssh and tried to ping rails-assets.org and there is no response (from the other server I do get a response).  I also tried to ping rails-assets.tenex.tech and still no response. 100% packet loss.
When I ping google, or any other page I do get a reply.

Thank you!

**Comment by hut8** [comment]
Investigating.

**Comment by hut8** [comment]
Can you try again? If that doesn't work, please contact me at liam@tenex.tech with what IP address the server has (try `curl -4 icanhazip.com`)

**Comment by AldanaQuintana** [comment]
Still same result. I'm emailing you what you requested.

**Comment by hut8** [comment]
Thanks for getting me the IP address off the thread. When you first mentioned this, I had a hunch that maybe this had something to do with a firewall (I had been using `fail2ban` earlier, but disabled it and reset the rules). I grepped through the firewall logs and nothing was blocked from that IP address. Are you sure you're using IPv4? Can you flush your DNS cache and try again please?

What does `getent hosts rails-assets.org` give on _both_ servers?

**Comment by AldanaQuintana** [comment]
Yes, I'm sure is IPV4.

I don't have nscd or anything like that installed on that server.
I tried to clear the cache executing this: `sudo /etc/init.d/dns-clean restart` (I googled it, not really sure if it will be good for something). Same result.

Both servers give the same output: `45.55.126.192   rails-assets.org`

**Comment by sheerun** [comment]
Maybe there's problem with missing certificates. If you're using ubuntu, you might try

```
sudo apt-get update && sudo apt-get upgrade
```

**Comment by hut8** [comment]
@sheerun that would not cause the problem with not being able to ping. Frankly, I'm puzzled here.

@AldanaQuintana can you please run `mtr` or `traceroute` to figure out what's going on here? Where are the packets stopping? If you can give me a login on one of these servers I can also try to assist. Keys are at https://github.com/hut8.keys

**Comment by sheerun** [comment]
Hmm. You're right ping should work with or without certificates..

**Comment by AldanaQuintana** [comment]
Traceroute gives the following output:

```
traceroute to rails-assets.org (45.55.126.192), 30 hops max, 60 byte packets
 1  45.55.32.254 (45.55.32.254)  0.646 ms  15.114 ms  0.614 ms
 2 * * *
...
30 * * *
```

Thank you for your readiness, but I can't give you access to the server.

**Comment by hut8** [comment]
Understandable about not being able to give access. I just want to help :+1: 

This is quite bizarre :smiley: I can ping the IP address _from_ the production server to your server with no problem, and traceroute works fine.

It just occured to me that you may very well be on the same ISP, and probably even in the datacenter.  Are you in DigitalOcean's NYC3 datacenter? To quote the 1979 cult classic film _When a Stranger Calls_, 

> We've traced the call... it's coming from inside the house. 

What happens when you ping 45.55.42.52 ? Can you also try 10.132.45.214 ?

**Comment by AldanaQuintana** [comment]
Lol, we are neighbors. I don't see why that might be an issue though, the other server is in the same region too (NYC3).

I'm stuck with no internet for a while (I made a hotspot with my cellphone but still is not enough to connect to ssh), when it comes back I will try pinging  45.55.42.52 and  10.132.45.214

**Comment by hut8** [comment]
Are you sure it's actually NYC3 and not NYC1 or NYC2?

Tip: On bad mobile connections, instead of SSH you should try [mosh](https://mosh.mit.edu/). It's unbelievably great.

I'm 98% sure now that it's because of something to do with this:
https://www.digitalocean.com/community/tutorials/how-to-use-floating-ips-on-digitalocean

Thanks so much for your bug report and information. I'm opening a support ticket with Digital Ocean, since they're really awesome and can provide some insight.

**Comment by AldanaQuintana** [comment]
Yeap. Sure. (Although the other server has an ip that's quite different, I don't know if it can have something to do with it.)

Thanks for the tip, I'll give mosh a try.
And thank you again for your readiness and support.

I'll post here any updates on the subject just in case someone else stumbles upon something similar.

**Comment by hut8** [comment]
Support ticket opened. I will reply when they do.

**Comment by hut8** [comment]
We've been talking back and forth and Digital Ocean said that this is the result of a known (but rarely occurring) bug involving floating IPs in the same data center. Can you please try to ping `45.55.42.52` from the machine having connectivity issues, _then_ try again?

From DO:

> ... two Droplets in the same datacenter won't be able to reach each other by floating IP, until the ARP table is populated by pinging the public IP (your public IP would be 45.55.42.52). After they ping that address, they should be able to access your floating IP address.

**Comment by AldanaQuintana** [comment]
I did what you said and ping is working now!

I'll try to deploy tomorrow and I'll let you know what happens.

**Comment by AldanaQuintana** [comment]
Success! Thank you!

**Comment by hut8** [comment]
Just FYI, in case anyone made this a part of their build process, it's no longer necessary as we no longer use the floating IP that Digital Ocean provides.
