### ISSUE TITLE
different file / folder names inside the same gem version

### ISSUE THREAD

**Issue by gingerlime** [tenex/rails-assets#326]
We're having a very strange problem with rails-assets. We're using a gem (`rails-assets-store.js`, latest version `1.3.20`).

On one environment, the files inside the gem look like this:

```
tree `bundle show rails-assets-store.js`
/usr/lib/ruby/gems/2.2.0/gems/rails-assets-store.js-1.3.20
├── app
│   └── assets
│       ├── javascripts
│       │   ├── store.js
│       │   │   ├── build.js
│       │   │   ├── json.js
│       │   │   ├── scripts
│       │   │   │   ├── 3-run-saucelabs-tests.js
│       │   │   │   └── saucelabs-platformSets.js
│       │   │   ├── store.js
│       │   │   ├── store+json2.min.js
│       │   │   └── tests
│       │   │       ├── browser-test-runner.js
│       │   │       ├── node-test-runner.js
│       │   │       └── tests.js
│       │   └── store.js.js
│       └── templates
│           └── store.js
│               └── index.html
├── Gemfile
├── lib
│   ├── rails-assets-store.js
│   │   └── version.rb
│   └── rails-assets-store.js.rb
├── rails-assets-store.js.gemspec
├── Rakefile
└── README.md

10 directories, 17 files
```

In another very similar environment (same ruby version, same Gemfile/Gemfile.lock, same gem version), it looks like this:

```
tree `bundle show rails-assets-store.js`                                                                                                                                                                               
/home/runner/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rails-assets-store.js-1.3.20
|-- app
|   `-- assets
|       |-- javascripts
|       |   |-- store-js
|       |   |   |-- build.js
|       |   |   |-- json.js
|       |   |   |-- scripts
|       |   |   |   |-- 3-run-saucelabs-tests.js
|       |   |   |   `-- saucelabs-platformSets.js
|       |   |   |-- store.js
|       |   |   |-- store+json2.min.js
|       |   |   `-- tests
|       |   |       |-- browser-test-runner.js
|       |   |       |-- node-test-runner.js
|       |   |       `-- tests.js
|       |   `-- store-js.js
|       `-- templates
|           `-- store-js
|               `-- index.html
|-- Gemfile
|-- lib
|   |-- rails-assets-store.js
|   |   `-- version.rb
|   `-- rails-assets-store.js.rb
|-- rails-assets-store.js.gemspec
|-- rails-assets-store.js.json
|-- Rakefile
`-- README.md

10 directories, 18 files
```

Apart from one extra file, the file / folder names are very slightly different. Instead of `store.js/` and `store.js.js`, it's now `store-js/` and `store-js.js` inside `app/assets/javascripts`

How is it possible to have different file names with the exact same gem version?

**Comment by hut8** [comment]
Looks like this works as expected:

https://github.com/rails-assets/rails-assets/blob/master/spec/models/build/paths_spec.rb#L198

We can't guarantee that a particular version of a gem will always contain the same contents.

By design, the version of a bower package being built is simply copied to the gem. So if the gem needs to be rebuilt differently because a bug is discovered in the build process, then of course the gem's contents will change.

The aforementioned issue alludes to support in an upcoming bundler version which uses hashes to verify integrity. We will support that as soon as we have more of an idea of scope.

**Comment by rocket-turtle** [comment]
I am facing a similar problem. I installed the gem `rails-assets-tinymce-dist` on the 5. February 2016 and added the require `//= require tinymce-dist` in the `application.js` file. 

if you go to [https://rails-assets.org/](https://rails-assets.org/) and search for tinymce-dist it says to do it like this:

> Include following in application.js:
> //= require tinymce-dist

If I download the gem now it has a different file structure.

> gem fetch rails-assets-tinymce-dist --source https://rails-assets.org/ -v 4.0.28

The old version had a file:

> app/assets/javascripts/tinymce-dist.js

Where the new file name is.

> app/assets/javascripts/tinymce.js

It was version 4.0.28 in both cases.

**Comment by vakuum** [comment]
Maybe the update of bower in commit c0eb100db496405fe83a02c68b6ee327d8971aa4 caused this trouble.

There are two bower components for tinymce: tinymce and tinymce-dist.

Both components are using the same name inside the bower.json file.

With bower 1.3.12 both components can be installed separately.

With bower 1.7.9 only the tinymce component can be installed.

And if you ask bower 1.7.9 for tinymce-dist, then you will also end up with the tinymce component.

### With bower 1.3.12

```
$ bower --version
1.3.12

$ bower info tinymce
...
name: 'tinymce',
...

$ bower info tinymce-dist
...
name: 'tinymce',
...

$ bower install tinymce#4.0.28
bower tinymce#4.0.28            cached https://github.com/tinymce/tinymce-dist.git#4.0.28
bower tinymce#4.0.28          validate 4.0.28 against https://github.com/tinymce/tinymce-dist.git#4.0.28
bower tinymce#4.0.28           install tinymce#4.0.28

tinymce#4.0.28 bower_components/tinymce

$ bower install tinymce-dist#4.0.28
bower tinymce-dist#4.0.28       cached https://github.com/tinymce/tinymce-dist.git#4.0.28
bower tinymce-dist#4.0.28     validate 4.0.28 against https://github.com/tinymce/tinymce-dist.git#4.0.28
bower tinymce-dist#4.0.28      install tinymce-dist#4.0.28

tinymce-dist#4.0.28 bower_components/tinymce-dist

$ bower list
bower check-new     Checking for new versions of the project dependencies..
clemens /home/clemens
├── tinymce#4.0.28 extraneous (latest is 4.3.11)
└── tinymce-dist#4.0.28 extraneous (latest is 4.3.11)

$ ls -1 bower_components
tinymce
tinymce-dist
```

### With bower 1.7.9

```
$ bower --version
1.7.9

$ bower info tinymce
...
name: 'tinymce',
...

$ bower info tinymce-dist
...
name: 'tinymce',
...

$ bower install tinymce#4.0.28
bower tinymce#4.0.28            cached https://github.com/tinymce/tinymce-dist.git#4.0.28
bower tinymce#4.0.28          validate 4.0.28 against https://github.com/tinymce/tinymce-dist.git#4.0.28
bower tinymce#4.0.28           install tinymce#4.0.28

tinymce#4.0.28 bower_components/tinymce

$ bower install tinymce-dist#4.0.28
bower tinymce-dist#4.0.28       cached https://github.com/tinymce/tinymce-dist.git#4.0.28
bower tinymce-dist#4.0.28     validate 4.0.28 against https://github.com/tinymce/tinymce-dist.git#4.0.28
bower tinymce#4.0.28           install tinymce#4.0.28

tinymce#4.0.28 bower_components/tinymce

$ bower list
bower check-new     Checking for new versions of the project dependencies...
clemens /home/clemens
└── tinymce#4.0.28 extraneous (latest is 4.3.11)

$ ls -1 bower_components
tinymce
```

**Comment by hut8** [comment]
@vakuum Thank you so much for the information. I've actually been investigating this for almost 8 hours so far. You can see how I've been meandering on the "hut8/fix-specs" branch of the tenex/rails-assets mirror:

https://travis-ci.org/tenex/rails-assets

This was while trying to fix some tests that have been failing off and on recently.

With 1.7.9, everything works fine on my local machine, but then breaks on travis. Totally baffled about this one. The locale settings, Node version, NPM version, all Ruby-related versions are all the same.

**Comment by hut8** [comment]
This morning we reverted back to the old version of Bower until we can figure out what's going on. Help would be very appreciated as I'm swamped with work right now.

**Comment by sheerun** [comment]
This is probably related to https://github.com/bower/bower/issues/2247

**Comment by hut8** [comment]
We've rebuilt all the gems that were built using bower 1.7.{7,9} with the older version in which all the tests pass. Can you all confirm that this worked? There were thousands, so it took a couple days.

**Comment by rocket-turtle** [comment]
I can confirm that the problem is solved for the `rails-assets-tinymce-dist` gem.
Thank you for your time and work.

**Comment by gingerlime** [comment]
Thanks for the update. Are there any plans to add some integrity checks to rails-assets? e.g. for the same bower package version, the gem it produces should always have the same files/structure. Using some kind of a hash digest could be quite effective in my opinion... I think bundler is heading in this direction, but I would imagine that rails-assets could also benefits from its own integrity checks.

**Comment by hut8** [comment]
@gingerlime indeed I do believe bundler is implementing that. But that basically ensures that if you have a given gem on your machine called x-y-z.1.2.3.gem , and the gem server has x-y-z.1.2.3.gem, then if the two don't match it will re-download it (at least, that's how I understand it).

rails-assets should only ever produce a given gem one time (of course there are provisions to rebuild, just for situations like this). So when you say "the gem it produces should always have the same files/structure", what would it check against?

We have a pretty good test suite which covers a lot of tricky cases; I think that's the best we can do for ensuring that the right files end up in the right places in the gems.

**Comment by gingerlime** [comment]
Hey @hut8,

Not sure about bundler, but I would hope that it at least warns you about overwriting an existing version of a gem, so you might have a chance to fix something or check if the difference somehow breaks things for you.

I'm not too familiar with rails-assets either, but what do you guys do if, say, the bower tag suddenly points to a different commit? would this trigger a rebuild? what if the repo moved? Or when you guys upgrade bower to a new version and rebuild?

In those situations (and maybe others), aren't you interested knowing whether the produced gem (for the same bower version) is the same or different?
