### ISSUE TITLE
rails-assets not picking the latest version?

### ISSUE THREAD

**Issue by gingerlime** [tenex/rails-assets#328]
I'm having a strange problem with `rails-assets-alephbet`. It was updated to version 0.12.0 a [while ago](https://github.com/Alephbet/alephbet/releases/tag/v0.12.0). On bower it shows the [latest version](https://bowercdn.net/package/alephbet), but on rails-assets it still shows [version 0.11.0](https://rails-assets.org/#/?query=alephbet). Any idea why?

![screenshot - 060516 - 11 03 34](https://cloud.githubusercontent.com/assets/524274/15068839/3b299496-137a-11e6-82df-3d5142933674.png)
![screenshot - 060516 - 11 03 12](https://cloud.githubusercontent.com/assets/524274/15068838/3b2920ce-137a-11e6-98c3-85c03a7bf26b.png)
![screenshot - 060516 - 11 02 59](https://cloud.githubusercontent.com/assets/524274/15068840/3b29f62a-137a-11e6-9bde-43296525fada.png)

**Comment by hut8** [comment]
rails-assets does have functionality to automatically grab and build latest versions, but it wasn't being used due to it not having been integrated with Capistrano at all and fear of more overloading issues (which have since been resolved quite well).

I'm developing that part now on https://github.com/tenex/rails-assets/tree/lb/fix-update-scheduler

**Comment by hut8** [comment]
Fix has been merged and is deploying now.

**Comment by hut8** [comment]
Verified that cron was updated, and manually triggered the scheduler. All of the components should be updated shortly.

**Comment by gingerlime** [comment]
Thanks, @hut8

**Comment by hut8** [comment]
This is taking longer than anticipated, as the jobs that fetch the metadata were being enqueued every 3 hours, and it takes longer than that for the jobs that are spawned by those jobs to complete. So I changed it to update every 12 hours.

The job that enqueued the build job for alephbet completed, but the build job will be done by tomorrow (I hope ;)

Anyway, just wanted to update you on that.

**Comment by hut8** [comment]
Looks fixed.
