### ISSUE TITLE
Backup server

### ISSUE THREAD

**Issue by joshjordan** [tenex/rails-assets#333]
Implementation:

In NYC1, create a 4 GB instance with a beta storage drive attached that's big enough to hold the gems and indexes. Periodically (every 4 hours?) rsync the gems and dump the master database, copying them over locally.

Failover procedure: the slave will have a simple script that tests to see if the master is up. As soon as the slave detects that the master is unavailable, it will use the Digital Ocean API to redirect the high availability IP to itself.

**Comment by hut8** [comment]
Resolved via https://github.com/tenex/rails-assets/pull/351
