### ISSUE TITLE
jquery-oembed-all has no versions defined (originally reported by hakkiplaten)

### ISSUE THREAD

**Issue by joshjordan** [tenex/rails-assets#336]
Anybody know why this is? It should have a valid `bower.json`:

https://github.com/nfl/jquery-oembed-all/blob/master/bower.json

Thanks! [Issue automatically imported by https://github.com/controlgroup/CSV-GitHub-import-export]

**Comment by ghost** [comment]
Hi,

We just need to get the jquery-oembed-all guys to use semantic versioning for their Git tags and the rest should be fine. Check out https://github.com/nfl/jquery-oembed-all/pull/39 and maybe also voice your support. Other than that I think this issue should be safe to close.

Many thanks!

**Comment by joshjordan** [comment]
Check. @hakkiplaten I am going to close this issue - please reopen if there is more we can do.
