### ISSUE TITLE
NPM Support? (originally reported by jrasanen)

### ISSUE THREAD

**Issue by joshjordan** [tenex/rails-assets#340]
Hi!

Any plans adding NPM support for proxying packages?

And thanks for continuing maintaining rails-assets. [Issue automatically imported by https://github.com/controlgroup/CSV-GitHub-import-export]

**Comment by Envek** [comment]
+1 on this as some projects drops support for pure Bower because they do not want to commit built js into repository.

For example Chart.js 2.2.0+: https://github.com/chartjs/Chart.js/releases/tag/v2.2.0

**Comment by joshjordan** [comment]
Hi @Envek! Thanks for adding your support to this issue. We're definitely going to implement it, right now its just a matter of when.

For what its worth, in the meantime, if you come across any packages that you want to use but aren't in bower yet, you can fork them and add a `bower.json`, then get them into the bower repository. Just a stopgap in case you get blocked.

**Comment by hut8** [comment]
@Envek you shouldn't need to commit built JS into a repository to support bower. See https://github.com/bower/spec/blob/master/json.md#main -- it specifically says:
- Use source files with module exports and imports over pre-built distribution files.
- Do not include minified files.

**Comment by Envek** [comment]
I got it, but it would be better if someone from @chartjs will read it. May be @simonbrunel or @etimberg? And people from other js libraries too.

Thank you for feedback.

**Comment by simonbrunel** [comment]
@Envek: is using [bower-npm-resolver](http://www.chartjs.org/docs/#getting-started-installation), for Chart.js, an issue? It seems to provide the feature reported by this ticket. See [PR#2555](https://github.com/chartjs/Chart.js/pull/2555) for details.

**Comment by Envek** [comment]
@simonbrunel: it require us to change build system for project's frontend (and separate frontend from backend). We're currently installing js libs from [rails-assets](https://rails-assets.org/) (this repo, which in turn is proxy to Bower and converter from bower packages to Ruby gems) and compile them with [sprockets](https://github.com/rails/sprockets). I don't think it worth it for simple project (kinda website, not SPA, as we still need to render ready HTML on server).

So if rails-assets add support for bower-npm-resolver I will be able to upgrade to Chart.js 2.2.0 (for now stick at 2.1.6).

**Comment by simonbrunel** [comment]
@Envek, I didn't know about rails-assets and understand your point. Having built files in the repository itself doesn't make sense, is pretty confusing since it never reflects the actual sources, and many times, pollutes PRs and commit history. In case of Chart.js, we provide different alternatives to get built versions (minified or not). Not sure which ones Bower officially supports, but I hope rails-assets will be able to implement at least one of them:
- as downloads attached to GitHub releases (tags)
- as part of the NPM package (in the dist/folder)
- or from cdn.js

**Comment by hut8** [comment]
Closing this because of the three better asset management alternatives in Rails 7 (and other alternatives in 5 and 6)
