### ISSUE TITLE
Rails-assets lists unknown version as latest airbrake-js

### ISSUE THREAD

**Issue by zefer** [tenex/rails-assets#355]
The latest [airbrake-js](https://github.com/airbrake/airbrake-js) version is `0.5.9`. This is correctly listed on [Bowercdn](https://bowercdn.net/package/airbrake-js).

[rails-assets.org](https://rails-assets.org/#/components/airbrake-js) lists an unknown version `4.0.1`, expected `0.5.9`.

Thank you!

**Comment by hut8** [comment]
Interesting. Let me see what I can find.

**Comment by hut8** [comment]
https://github.com/airbrake/airbrake-js/commit/baa6cc1f32b1b9a7069489468c057260b1b78f83 There's your problem ;)

I'm deleting the erroneous gem right now.

**Comment by zefer** [comment]
Excellent, thank you @hut8. There's also a `4.0.0` that needs deleting.

**Comment by hut8** [comment]
Thanks for filing this issue, by the way. Had me nervous for a minute :relieved: 

Should be resolved now; please confirm.

**Comment by zefer** [comment]
Fixed. Thanks very much for the super-fast fix, much appreciated! We'll try not to mix up our versions in future :)

**Comment by hut8** [comment]
And especially thanks for including a rails-assets.org example in your repo! No problem at all with your versions; we should have a method of un-releasing bower packages.
