### ISSUE TITLE
Sprockets error on a component that I added on rails-assets

### ISSUE THREAD

**Issue by karthikkp** [tenex/rails-assets#359]
https://rails-assets.org/#/components/imagine.js

I ran bundle, required imagin.js in my application.js file and restarted the server multiple times, but sprockets is throwing:
Sprockets::FileNotFound at -----
couldn't find file 'imagine.js' with type 'application/javascript

**Comment by hut8** [comment]
Please see https://github.com/tenex/rails-assets/issues/307
