### ISSUE TITLE
Conflict with sprockets if a package's name ends with `.js` and its css component is required in a sass file

### ISSUE THREAD

**Issue by namiwang** [tenex/rails-assets#361]
A demo may be re-pro with package `fullpage.js` and the following code:

```
# application.sass
#= require fullpage.js
```

And the package `fullpage` works fine.

**Comment by namiwang** [comment]
I guess this is duplicated with https://github.com/tenex/rails-assets/issues/266, which is closed but it's still unresolved.

**Comment by frankie-loves-jesus** [comment]
Have you tried `fullpage.js/fullpage.js`?

Also try http://code.runnable.com/ for demonstrating problems.

**Comment by emartini** [comment]
I had a similar issue with the `rangeslide.js` package, after take a look on the gem tree I figured out (and exactly as @frankie-loves-jesus pointed out) it's need add the package name to the css path:

application.js

```
//= require rangeslider.js.js
```

application.scss

```
/*
*= require rangeslider.js/rangeslider
*
```

This is the gem tree:

```
.
├── Gemfile
├── README.md
├── Rakefile
├── app
│   └── assets
│       ├── javascripts
│       │   ├── rangeslider.js
│       │   │   └── rangeslider.js
│       │   └── rangeslider.js.js
│       └── stylesheets
│           ├── rangeslider.js
│           │   └── rangeslider.scss
│           └── rangeslider.js.scss
├── lib
│   ├── rails-assets-rangeslider.js
│   │   └── version.rb
│   └── rails-assets-rangeslider.js.rb
├── rails-assets-rangeslider.js.gemspec
└── rails-assets-rangeslider.js.json
```
