### ISSUE TITLE
SSL Cert Expired

### ISSUE THREAD

**Issue by michaelburris** [tenex/rails-assets#363]
`→ bundle install
Fetching source index from https://rails-assets.tenex.tech/
Retrying fetcher due to error (2/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rails-assets.tenex.tech/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Retrying fetcher due to error (3/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rails-assets.tenex.tech/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Retrying fetcher due to error (4/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rails-assets.tenex.tech/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Could not verify the SSL certificate for https://rails-assets.tenex.tech/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For
information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.`

![screen shot 2016-06-27 at 9 14 24 am](https://cloud.githubusercontent.com/assets/13320631/16382705/9210991c-3c47-11e6-9398-18d3b3e31f9c.png)

**Comment by hut8** [comment]
@michaelburris Please use rails-assets.org instead of rails-assets.tenex.tech. Thanks!

**Comment by michaelburris** [comment]
@hut8 👍 Thank you!
