### ISSUE TITLE
Using Rails 5, some rails-assets will create a jQuery version conflict 

### ISSUE THREAD

**Issue by maduhaime** [tenex/rails-assets#372]
Using rails 5, rails-assets packages that `require "rails-assets-jquery"` and include RailsAssetsJquery as a dependencies will creates a jQuery version conflict.  Because bundler will download and install the **rails-assets-jquery ('~> 3.1.0') gem** (or the latest version available).

When jQuery is required inside the manifest in application.js, the **assets pipeline** will load jQuery **3.1.0** instead of the **1.12.1** version, included in the jquery-rails gem ('~> 4.1.1').

At the console, `jQuery.fn.jquery` will help you find witch version is currently in use.

The following rails-assets will produce the conflict : 
- rails-assets-bootstrap-select ('~> 1.10.0')
- rails-assets-jquery.equalheights ('~> 1.5.3')
- rails-assets-tagmanager ('~> 3.0.2')
- rails-assets-typeahead.js ('~> 0.11.1')

The following will not : 
- rails-assets-bootstrap-filestyle ('~> 1.2.1')

It is important to know that some plugins are not compatible with jQuery v.3.  As an exemple with the **bootstrap-datepicker** plugins, the popup will open but the calendar inside won't be displayed.

To temporary solve the problem , you have to solution : 
- download plugins from a cdn;
- require jquery2 in your application.js manifest, as it will force version 2.2.1 to be loaded from the jquery-rails gem ('~> 4.1.1').  The jquery-rails gem include the latest versions of jQuery 1, 2 and 3.

**Comment by maduhaime** [comment]
It was very difficult to find.  It all start with a broken datepicker.

**Comment by hut8** [comment]
It seems like this is because you're purposely including jQuery from both rails-assets-jquery (which naturally will be a dependency of projects in rails-assets which reference jQuery in their bower.json dependencies)  as well as `jquery-rails`. Can you explain why `jquery-rails` is still in your gemfile?

**Comment by maduhaime** [comment]
It is still in my gem file because my application is not compatible with jQuery 3.  Only with jQuery version 1 or 2.  Also the gem provide `jquery_ujs`.  

If you look at the bower.json file from bootstrap-select repository, the dependency to jquery is set to 1.8.0.  But it is the jquery version 3.1.0 that rails-assets download as a dependency.

[https://github.com/silviomoreto/bootstrap-select/blob/master/bower.json](url)

Does the version number is taken into account in the creation of gems?

**Comment by hut8** [comment]
The bower.json file you referenced set the jQuery dependency to `>= 1.8`. `3` is definitely `>= 1.8`, so it resolved correctly to 3. The dependencies in the gem are derived directly from the `bower.json` file. Therefore `bootstrap-select` can work with jQuery 3 according to its `bower.json`. It still seems to me like it's working as designed, and you've included a second jQuery.

So are you saying you personally have written code that is incompatible with jQuery 3? You can, of course, explicitly include a requirement in your Gemfile that reduces the maximum jQuery version, as long as the others gems don't produce a mutually exclusive dependency (i.e., yours requires <2, but another gem requires > 2, which makes the dependency unsatisfiable).

**Comment by maduhaime** [comment]
Yes, parts of my code and other plug-ins, like bootstrap-datepicker, are not compatible with jQuery 3.  My point is that if I decide to use rails-assets and a plugins that resolve to jquery version 3, I will lose the ability to choose the jquery version I want to use and to prevent any conflict, I will have to remove `jquery_rails`, loosing at the same time `jquery_ujs`.

I think that all dependencies to jQuery, found in bower.json file, should be skipped to leave a full control on jQuery to `jquery_rails`...

**Comment by hut8** [comment]
I still don't understand why you can't use rails-assets-jquery-ujs and specify in the gemfile that your code depends on a lower version of jQuery. Defeating the dependency resolution of rails-assets (and Bower) makes no sense to me. If you need a specific version of jQuery, you can just specify it in the gemfile. Also, your claim that bootstrap-datepicker is not compatible with jQuery 3 seems wrong: https://github.com/eternicode/bootstrap-datepicker/blob/master/bower.json

**Comment by hut8** [comment]
Closing due to lack of feedback. Let me know if you have further questions.
