### ISSUE TITLE
Version mismatched on algolia-autocomplete

### ISSUE THREAD

**Issue by jonchay** [tenex/rails-assets#374]
I found this [issue](https://github.com/tenex/rails-assets/issues/240) regarding requesting to remove version mismatched in rails-assets. It appears that the latest version in rails-assets for this library is `1.17.0` which actually maps to the libraries' `0.17.0` version.

The latest version of the library is actually `0.21.3`, could we clean this up? 
https://rails-assets.org/#/components/algolia-autocomplete.js

**Comment by hut8** [comment]
I deleted the two that were greater than 1. Please close if it's resolved to your satisfaction.

**Comment by jonchay** [comment]
Thanks for the quick turnaround! Closing this.
