### ISSUE TITLE
Version out of sync / broken for videojs-vast-vpaid

### ISSUE THREAD

**Issue by Genkilabs** [tenex/rails-assets#378]
Rails Assets only shows version 1.1.0 as the most recent https://rails-assets.org/#/components/videojs-vast-vpaid
It also shows an error for the bowerfile missing a 'main'

The actual current version is 2.0.2 and the bower file includes its js and css in main
https://github.com/MailOnline/videojs-vast-vpaid/blob/2.0.2/bower.json

Is there a way in the UI to re-index this or do we need a change in the repo?

**Comment by hut8** [comment]
Checking now.

**Comment by hut8** [comment]
Ah yes, I found this in our failed build logs:

```
Build::BuildError: MailOnline/swfobject has no versions defined. Please create an issue in component's repository.
```

So one of your dependencies is https://github.com/MailOnline/VPAIDFLASHClient . In turn, that depends on MailOnline/swfobject (see https://github.com/MailOnline/VPAIDFLASHClient/blob/master/bower.json).

According to your releases page, there are no _semver_ releases defined: https://github.com/MailOnline/swfobject/releases

If you make one that's semver-compatible, like 2.2.0 or something, then you should be good 😄 

I'll admit this was a bad user experience, and for that I apologize. There should be some sort of "Hey, this build is broken 💥" flag on the component page. We do have a https://rails-assets.org/status page, but that only goes back 7 days. PRs are welcome!

**Comment by hut8** [comment]
Also, as a note, the `version` field in `bower.json` has been totally ignored for quite a while, so there's one less chore to worry about during your release process. `bower` itself is coupled tightly to `git`, so it just uses tags.

**Comment by Genkilabs** [comment]
Awesome. Thanks for getting back to me so quickly.

Also, I did not realize that no one cares about version, (other than for human reference), thats good to know.

Unfortunately swfobject is totally outdated, but needs to stick around to support older apps... I'll see if I can get it semver'd for now so people can use this thing in rails.

BTW, I friggin' love rails-assets, and I try to use it and promote it as much as I can to my whole team. Thank you so much for supporting it so well.

**Comment by hut8** [comment]
All you should need to do is push a tag in git to the repo, which it looks like is owned by your organization. Therefore I'm going to go ahead and mark this as closed, since we have related tickets for improving the UX.

Thanks for the kind words 👍

**Comment by Genkilabs** [comment]
Sound good. Unfortunately I'm just a vendor so I can't make the change, but I'll bug someone over there till it happens.
Thanks for the help.
