### ISSUE TITLE
Issues when downloading gemspes.rz

### ISSUE THREAD

**Issue by teamon** [tenex/rails-assets#38]
Most probably some race condition between gem build, reindex and file download

**Comment by sheerun** [comment]
I find no other solution than hard (non-background) reindex upon each build.

Please also reference https://github.com/rubygems/rubygems/issues/494

**Comment by sheerun** [comment]
Maybe set Gem::Specification.all to one gam and run build_marshal_gemspecs and then run full reindex (build_modern_indices) in background?

**Comment by sheerun** [comment]
@teamon by the way, why HackedIndexer?

**Comment by teamon** [comment]
Because by default Indexer somehow ignores file lists and uses system paths (to system gemspacs)

**Comment by sheerun** [comment]
I use `update_index` instead of `generate_index` in #37. It should fix the problem as there is no reindexing in background.
