### ISSUE TITLE
sweetalert2 build failure

### ISSUE THREAD

**Issue by yyyyaaa** [tenex/rails-assets#387]
For some reason version 6.0 of sweetalert2 build fails, any ideas why?

**Comment by hut8** [comment]
What error message are you getting?

**Comment by yyyyaaa** [comment]
I'm not getting any errors but I couldn't terminate the modal by clicking outside of the modal or clicking on the confirm button

**Comment by hut8** [comment]
There was actually a small glitch which caused new builds to stop which I just resolved. What version are you using now? 5.3.1 is the latest that's been indexed as of this writing, so it's impossible that you were using 6. That's probably the cause of the problem. The queue of new versions being built will be gone through in about 6 hours at the latest.

**Comment by hut8** [comment]
Closing due to lack of feedback.
