### ISSUE TITLE
Submodule support

### ISSUE THREAD

**Issue by kenn** [tenex/rails-assets#389]
I'm having issue with `rails-assets-card` gem. It just errors out with this line:

```
Sass::SyntaxError: File to import not found or unreadable: bourbon/app/assets/stylesheets/bourbon
```

because [bourbon is referenced as submodule](https://github.com/jessepollak/card/tree/master/src/scss) and is not expanded in the gem.

Is there any way to solve this issue?

Also reported in the upstream: https://github.com/jessepollak/card/issues/319

**Comment by hut8** [comment]
Does bower recursively clone when you install bower packages? Have you tried adding the submodule as a separate gem?

**Comment by kenn** [comment]
Sorry, I'm not familiar with bower, so I can't really answer your question.

It looks like a relative path, so I wonder if adding submodule as a separate gem would help.

**Comment by kenn** [comment]
https://github.com/jessepollak/card/issues/319

Actually the gem worked if I removed `*= require card` from `application.scss` as instructed.

I'm not sure if submodule support is a problem in general, but since my particular issue is resolved, I'm going to close this ticket.

Thank you for your great work with rails-assets!
