### ISSUE TITLE
Production SSL Certificate has expired

### ISSUE THREAD

**Issue by rposborne** [tenex/rails-assets#390]
https://www.dropbox.com/s/os3exk54o4y2qds/Screenshot%202017-02-07%2023.06.06.png?dl=0
![screenshot 2017-02-07 23 06 06](https://cloud.githubusercontent.com/assets/243989/22723148/273bc75c-ed8a-11e6-9d86-350389312b20.png)

**Comment by jaybloke** [comment]
Yep... just experienced the same problem

**Comment by adamaiken89** [comment]
+1 
Hope it can be fixed soon.

The projects depend on "rails-assets" cannot be compiled at the moment.

**Comment by DavidBennettPIO** [comment]
As a workaround for development I've changes my Gemfile to use http://insecure.rails-assets.org

When you've restarted nginx let us know.

**Comment by jaybloke** [comment]
That works - A big thank you!

**Comment by hut8** [comment]
Working on it now. This is actually caused by the failover instance not having an up to date certificate (which is in use currently due to a problem on the master instance).

**Comment by hut8** [comment]
Resolved.

**Comment by hut8** [comment]
Apologies to all those affected by this issue. Our failover plan has worked incredibly well, but lacked this one part, which was to copy the SSL certificates from the primary to the failover web server *and remember to restart nginx*. It won't happen again. Thanks for your patience.

**Comment by rposborne** [comment]
@hut8 We are more than happy to test systems for you :) Thanks for your short response time.  We all appreciate the work you do!!

**Comment by zhongxiao37** [comment]
Hey, issue happens again!
