### ISSUE TITLE
Run Locally (company-wide)

### ISSUE THREAD

**Issue by waynerobinson** [tenex/rails-assets#398]
Is it possible to get a quick guide on the initial Ansible bootstrapping and executing to get Rails Assets deployed in production onsite?

I have it running in dev, but wondered if there is anything special to do in production. For example, the concurrency for workers seems to be set at 1 in sidekiq and I was wondering if this is for a reason?

**Comment by joshjordan** [comment]
We don't have one put together right now, but we should do so once this hosting event is concluded. If you move forward, we'd truly welcome a PR as a first step towards this.

We're also considering a paid, self-hosted option that we'd setup & maintain for you. Hit me up at josh@tenex.tech if anyone finds that interesting.

**Comment by hut8** [comment]
I'm going to close this; the concurrency is certainly configurable. This is a pretty standard rails app to deploy. Let us know if you get stuck -- you've probably moved on from rails-assets by now 😄
