### ISSUE TITLE
Corrupted index

### ISSUE THREAD

**Issue by sheerun** [tenex/rails-assets#40]
For some reason index were corrupted and `bundle install` returned error message that gem `rails-assets-angular-1.0.7` were not found. It probably was `specs` file or `lastest_specs`

@dmilith Do you think it could be because of deploy fixes you made?

**Comment by dmilith** [comment]
@sheerun Don't think so. We just fixed webistrano deploy processs.

**Comment by sheerun** [comment]
It may, but not have to be a RubyGems issue: https://github.com/rubygems/rubygems.org/issues/581

Probably just some weird concurrency error though.

**Comment by sheerun** [comment]
No such issue for a month, closing.
