### ISSUE TITLE
Wrong info for masonry

### ISSUE THREAD

**Issue by dsandstrom** [tenex/rails-assets#400]
Masonry has duplicates:

- https://rails-assets.org/#/components/masonry
- https://rails-assets.org/#/components/jquery-masonry

In addition, the require instructions don't work.  We have to use the "pkgd" version, not the js file in the root

This worked for me:
```
//= require masonry/dist/masonry.pkgd
```

However, maybe the bower file can be updated to point to the right file https://github.com/desandro/masonry/issues/618#issuecomment-136295697:
```
"masonry": {
  "main": ["./dist/masonry.pkgd.js"],
  "dependencies": {}
},
```

**Comment by hut8** [comment]
How is this different than https://github.com/tenex/rails-assets/issues/280 ?

**Comment by dsandstrom** [comment]
Sorry, I neglected to search for similar issues.  However, this also illustrates the problem with duplicate gems like #399.  Should I join this issue with that one?
