### ISSUE TITLE
rails-assets-angular-ui-calendar stuck on rails-assets-angular ~> 1.4.0

### ISSUE THREAD

**Issue by vrogers** [tenex/rails-assets#405]
I tried to install angular-ui-calendar via rails-assets '>= 1.0.2' and ran bundle and got this error:

![image](https://cloud.githubusercontent.com/assets/1660723/25640968/c46b1fe8-2f5f-11e7-8c13-7dae809179e4.png)

it says that rails-assets-angular '~> 1.4.0' is required, when the actual ui-calendar bower.json only requires '>= 1.4.x'

https://github.com/angular-ui/ui-calendar/blob/master/bower.json

am I mistaken, or should the requirement be changed to rails-assets-angular '>= 1.4.0'?

**Comment by hut8** [comment]
That's a good question. `>= 1.4.x` seems like a pretty odd way of saying this. Can you check https://github.com/tenex/rails-assets/issues/263 and https://github.com/tenex/rails-assets/pull/375 ? Clearly it's related. It actually seems like it works as designed, simply because Bower uses semver v2.

**Comment by hut8** [comment]
Closing due to lack of feedback and high probability of duplicate with above issues. Feel free to reopen.
