### ISSUE TITLE
popper.js does not have dist/

### ISSUE THREAD

**Issue by glebm** [tenex/rails-assets#409]
For some reason, the `rails-assets-popper.js` https://github.com/FezVrasta/popper.js, does not have the `dist/` directory.

It is a dependency of the current Bootstrap 4 master, so it'd be nice if it worked.

**Comment by hut8** [comment]
Looking now.

**Comment by hut8** [comment]
Looks like popper.js doesn't really support bower: 

* https://github.com/FezVrasta/popper.js/issues/274 
* https://github.com/FezVrasta/popper.js/issues/223
* https://github.com/FezVrasta/popper.js/issues/254

It seems like the maintainer of that project isn't really interested in supporting bower, which is his choice, but unfortunately since there is no bower metadata in the project's repository, there's nothing we can do here.

**Comment by glebm** [comment]
Thank you! Do you know if there is a bundler-to-yarn/npm proxy?

**Comment by hut8** [comment]
I'm afraid not. However, you can use these natively with Rails 5.1:

http://weblog.rubyonrails.org/2017/4/27/Rails-5-1-final/

**Comment by glebm** [comment]
Well I'm packaging [Bootstrap 4 for Sprockets](https://github.com/twbs/bootstrap-rubygem) so I need a gem. I've solved the problem by packaging popper.js as a rubygem: https://github.com/glebm/popper_js-rubygem

**Comment by joshjordan** [comment]
We really would like to implement bundler-to-yarn/npm, as you say, in Rails Assets. PRs welcome. Poke me if this is something you (or anyone else!) would like to work on.

**Comment by klihelp** [comment]
Need list, es5?

**Comment by joshjordan** [comment]
Can you elaborate?

**Comment by FezVrasta** [comment]
How could a bower metadata file help you? I'm not against Bower per se, I'm against the idea to put compiled code in the repository.

If the idea is to simply add a bower.json file I'm okay with it.

**Comment by hut8** [comment]
Unfortunately it's really an issue of putting compiled code in the repository. I understand why you're against it, but rails-assets.org can't work without it since Bower's file format doesn't give any hints as to how to build the code in the first place 😄

**Comment by FezVrasta** [comment]
**¯\\\_(ツ)_/¯**

**Comment by joshjordan** [comment]
@glebm your best bet is probably to fork it, compile it, commit it, and point Rails Assets at your fork.

**Comment by FezVrasta** [comment]
I'm open to PRs to introduce some kind of automatic magic that pushes the compiled stuff in a different branch on each release. Always if Bower allows to define a branch different from `master`...
