### ISSUE TITLE
Angular 1.2.0 were a blank .gem

### ISSUE THREAD

**Issue by sheerun** [tenex/rails-assets#41]
Fore some reason angular 1.2.0 were an "empty gem" according to `gem generate_index` command. Re-building it helped, but I'm not sure why it was empty in first the first place.

**Comment by dgertych-monterail** [comment]
rails-assets-flot gem is empty as well @sheerun can you rebuild all the versions?

**Comment by sheerun** [comment]
@chytreg This should be resolved by 7a374eee321 where I raise an error if builded component is empty; so even if bundler somehow fails to install component we won't build it. Ii'm going to rebuild all component after implementing #46

**Comment by sheerun** [comment]
@chytreg 90eaaa3a9b6a should fix empty build in general. Let me know if you still experience any problems.
