### ISSUE TITLE
add status page: https://cachethq.io/

### ISSUE THREAD

**Issue by joshRpowell** [tenex/rails-assets#410]
thought of this: https://cachethq.io/

when I ran into this: 
![image](https://user-images.githubusercontent.com/6732638/27148972-1456af28-5110-11e7-8058-f780c31aba37.png)

**Comment by joshjordan** [comment]
Thats very cool! Would you be willing to host an instance of Cachet for us?

**Comment by hut8** [comment]
The status page would be nice, but hosting another service just to monitor our service would require more resources. If you see that error, you know the site is down 😄 If you can recommend a free, hosted alternative, I'm all ears.
