### ISSUE TITLE
perfect-scrollbar out of sync

### ISSUE THREAD

**Issue by skyschub** [tenex/rails-assets#412]
The `perfect-scrollbar` package at https://rails-assets.org/#/components/perfect-scrollbar is out of sync, since v0.7.1 was released at May 27. Manually re-submitting the component via `add component` seems to be unable to discover the new tag. What to do?

**Comment by hut8** [comment]
Looking now

**Comment by hut8** [comment]
Try running:

```
bower info perfect-scrollbar
```

This seems to show that the latest release that bower sees is 0.7.0. I agree with you that another tag was pushed. But ultimately rails-assets.org grabs its information from the bower repository. This particular project seems somewhat unusual and removed the bower installation directions from its README between 0.7.0 and 0.7.1. Perhaps you could try building and importing `https://github.com/noraesae/perfect-scrollbar-bower`?

**Comment by hut8** [comment]
Ah yes, looks like they forgot to push a tag: https://github.com/noraesae/perfect-scrollbar-bower/issues/7

If you need this fixed now, you could fork it yourself, add a tag and build your fork via rails-assets.org. Or contact the maintainer more directly.

**Comment by skyschub** [comment]
Oh yikes, that's a good catch. Thanks for that, will follow up with the maintainer.
