### ISSUE TITLE
Network error connecting to rails-assets.org

### ISSUE THREAD

**Issue by connor-t** [tenex/rails-assets#415]
Trying to do bundle install with

```
source 'https://rails-assets.org' do
  gem 'rails-assets-lazyloadxt'
  gem 'rails-assets-material-icons'
  gem 'rails-assets-tether'
  gem 'rails-assets-bootstrap', '~> 4.0.0.alpha.2'
  gem 'rails-assets-bootstrap-social'
  gem 'rails-assets-tagsinput'
  gem 'rails-assets-typeahead.js'
  gem 'rails-assets-jquery-migrate'
end
```
which gives the error;

`Fetching gem metadata from https://rails-assets.org/..Retrying dependency api due to error (2/4): Bundler::HTTPError Network error while fetching https://rails-assets.org/api/v1/dependencies?gems=rails-assets-angular%2Crails-assets-jasmine%2Crails-assets-rainbow%2Crails-assets-bootstrap-3%2Crails-assets-bootstrap-2.3.2
Retrying dependency api due to error (3/4): Bundler::HTTPError Network error while fetching https://rails-assets.org/api/v1/dependencies?gems=rails-assets-angular%2Crails-assets-jasmine%2Crails-assets-rainbow%2Crails-assets-bootstrap-3%2Crails-assets-bootstrap-2.3.2
Retrying dependency api due to error (4/4): Bundler::HTTPError Network error while fetching https://rails-assets.org/api/v1/dependencies?gems=rails-assets-angular%2Crails-assets-jasmine%2Crails-assets-rainbow%2Crails-assets-bootstrap-3%2Crails-assets-bootstrap-2.3.2`

**Comment by dpsk** [comment]
have the same issue, can't deploy my app for hours

**Comment by betamatt** [comment]
@dpsk Try using `--full-index`, that's gotten me by some of these issues.

**Comment by bsbodden** [comment]
I'm getting the same here today and using `--full-index` does indeed solve it.

**Comment by bitcoiners** [comment]
How do you solve it for heroku deployments?
