### ISSUE TITLE
SSL certificate has expired

### ISSUE THREAD

**Issue by pwim** [tenex/rails-assets#416]
The SSL certificate for rails-assets.org has expired (it expired at 2017-12-05 03:00:00 UTC).

**Comment by alexssung** [comment]
+1

this is blocking deployment

**Comment by g3ortega** [comment]
Same here! We have a presentation, and we can't deploy to staging :smile:

**Comment by alexssung** [comment]
You can temporarily change your Gemfile to use http://insecure.rails-assets.org/ if it's an emergency

**Comment by g3ortega** [comment]
Cool, thanks for the tip @alexssung :+1:

**Comment by lakehouseru** [comment]
+1 !

**Comment by artiommocrenco** [comment]
Bad suggestion, @alexssung .

Better wait for the certificate to be renewed to avoid MitM attacks.

**Comment by artiommocrenco** [comment]
@hut8 @sheerun

**Comment by jordiclariana** [comment]
Another nasty trick to avoid the problem (but insecure if you don't rely in expired certificates):
I installed an Nginx and configured this server:
```
server {
  listen 80;
  location / {
    proxy_set_header Host rails-assets.org;
    proxy_pass https://rails-assets.org;
  }
}
```
Then instruct bundle to point to the Nginx:
`bundle config --local mirror.https://rails-assets.org/ http://localhost/`

It works now, but as I said: not 100% secure.

**Comment by mansoorelahi** [comment]
+1 !

**Comment by RonaldDijkstra** [comment]
+1!

**Comment by avokhmin** [comment]
@joshjordan , @hut8 , @tenex Houston,  we have a problems

**Comment by dkhgh** [comment]
it's 04:50am at the Tenex office right now
Calling their office (1-833-TENEX10) doesn't work from here (NL).

**Comment by artiommocrenco** [comment]
There is a certain amount of pleasure associated with the moment when everyone in the world is waiting until you renew your SSL certificate. :smile:

**Comment by Br3nda** [comment]
Put certbot in cron and this can just not happen.
https://certbot.eff.org

**Comment by thromera** [comment]
After this is fixed, we should definitely think at how to alleviate those kind of critical issues (@Br3nda solution could work I believe).

**Comment by murdoch** [comment]
@Erowlin the simplest solution would be for tenex to ask their CA to send them a reminder email a month or two before their certificate is due to expire. I'm sure the rails community in general would be happy to help pay for the renewal through kickstarter or something.

**Comment by mynameiswillporter** [comment]
Hey everyone, I think I was just able to renew the SSL certificate.  Sorry for everyone affected by the outage.  I think it makes sense to automate the renewal of the certificate to try and prevent this in the future, but as I am relatively unfamiliar with this project I would like to discuss further @joshjordan during normal business hours.  Its not yet 6:00 am.

**Comment by murdoch** [comment]
@mynameiswillporter I can confirm this is fixed for me, my `bundle install` runs fine now. Well done. Thanks.

**Comment by mynameiswillporter** [comment]
Great! Thanks @murdoch

**Comment by fs-watanabe-noriyuki** [comment]
Close ok?

**Comment by pwim** [comment]
My original issue was resolved. Looks like it happened again in #419, so hopefully the maintainers have taken some steps to prevent the certs from expiring again.

**Comment by GuiCarneiro** [comment]
Expired again =l

**Comment by ozbendavid** [comment]
Expired again this morning
With who should I contact?

Thanks

**Comment by jeffbdavenport** [comment]
SSL is expired again

**Comment by anu-vaid** [comment]
Expired again!!

**Comment by dbackeus** [comment]
Again?

**Comment by joshjordan** [comment]
Locking thread - not to suppress discussion, but to make sure that folks are commenting on new threads when new issues arise or reoccur.
