### ISSUE TITLE
rails-assets.org is down

### ISSUE THREAD

**Issue by drusepth** [tenex/rails-assets#425]
<img width="520" alt="screen shot 2018-04-24 at 3 07 35 pm" src="https://user-images.githubusercontent.com/538235/39211450-3d48192c-47d1-11e8-97e6-5fa76be371ae.png">

**Comment by joshjordan** [comment]
Thanks for the heads up. You created this issue at the same time my alarms started going off. On it.

**Comment by joshjordan** [comment]
Up now. The server failed harder than it had in the past, and took some time to provision new resources. As always, if you get a lot of value out of rails assets, please shoot us even a small donation to keep it running. It truly helps! :)
