### ISSUE TITLE
The SSL certificate has expired

### ISSUE THREAD

**Issue by edudepetris** [tenex/rails-assets#426]
The SSL certificate for rails-assets.org has expired Expired: Sunday, 3 June 2018

**Comment by truongduyng** [comment]
Yes, it have been occuring again. Someone please help to fix! Thanks

**Comment by kirillplatonov** [comment]
Durty workaround and should be switched back to https ASAP when SSL certificate will be fixed. Until that, you can use `source 'http://insecure.rails-assets.org'`.

**Comment by DoubleMalt** [comment]
Seems like the discussion mentioned in https://github.com/tenex/rails-assets/issues/416#issuecomment-349270105 never lead to anything ;)

**Comment by chriscz** [comment]
Hey, @joshjordan @hut8

**Comment by joshjordan** [comment]
We will renew as soon as one of us can get on. Should be within an hour or two. As always, in the meantime, use `source 'http://insecure.rails-assets.org`

**Comment by wasuint** [comment]
When you change url in the Gemfile to http://insecure.rails-assets.org I get another issue:   
```
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.
```
So I will wait another hour or so for the certificates to be renewed. 
By adding this in the  crontab, it renews the certificates automatically;
`sudo crontab -e`  
`0 12 * * * /usr/bin/certbot renew --quiet`  
Good luck and thanks for the good work.

**Comment by joshjordan** [comment]
We're up now with a renewed cert. Thanks for the advice, but it generally doesn't fit our configuration/problem set. In this case, we had a renewed cert but nginx was having trouble picking up the changes.

As always, we put a lot of effort into keeping Rails Assets running well for the rails community. If you find it valuable, we'd appreciate a donation (on the homepage!)

Have a great weekend, all!
