### ISSUE TITLE
URGENT: Website is down

### ISSUE THREAD

**Issue by pedrofurtado** [tenex/rails-assets#428]
@joshjordan 

![screenshot from 2018-07-06 17-40-56](https://user-images.githubusercontent.com/10530520/42399332-c8e736e2-8143-11e8-93dd-8a855c9351e6.png)

The website is down. It fails all `bundle install` commands.

**Comment by hnatt** [comment]
Let us know if we can chip in for the domain/hosting expenses. For me personally it would be easier to spend a few bucks than migrating to webpacker in urgent manner, while all other work is blocked.

**Comment by vlymar** [comment]
we're having issues deploying as well :(

**Comment by hnatt** [comment]
Quick fix is to add

```
192.241.135.61 rails-assets.org
```

to your `/etc/hosts` file.

The domain has expired, but the server is still running. Dug the IP here: https://securitytrails.com/domain/rails-assets.org/dns

**Comment by vlymar** [comment]
if someone else scoops up this domain they could potentially do some harm... cc @tenex and @joshjordan

**Comment by sethherr** [comment]
It looks like this was fixed?

**Comment by gearoidoceallaigh** [comment]
@sethherr Still down for me.

**Comment by joshjordan** [comment]
Thanks for the tag. Will look into it shortly.
