### ISSUE TITLE
HTTP only?

### ISSUE THREAD

**Issue by krainboltgreene** [tenex/rails-assets#43]
Apparently I can only access rails-assets.org via HTTP and rails-assets.org allows me to upload my own packages over HTTP.

This is a recipe for disaster.

**Comment by teamon** [comment]
This project isn't publicity released yet. HTTPS is somewhere down the todo list. 

Anyway, how is HTTPS connected with "uploads" ?

**Comment by krainboltgreene** [comment]
Oh, it looks publically released.

And if I can MITM the connection I can change the upload.

**Comment by sheerun** [comment]
@krainboltgreene We don't have uploads :) But I agree TLS would be helpful. @teamon @bartoszpietrzak Could you take care of it? We need certificate only for bare domain.

**Comment by sheerun** [comment]
Rails Assets is now available under https too.

**Comment by krainboltgreene** [comment]
Awesome.

On Mon, Dec 9, 2013 at 2:12 AM, Adam Stankiewicz
notifications@github.comwrote:

> Closed #43 https://github.com/rails-assets/rails-assets/issues/43.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rails-assets/rails-assets/issues/43
> .

## 

Kurtis Rainbolt-Greene, Hacker
Software Developer
612 S. Flower St.
Los Angeles, CA, 90017
