### ISSUE TITLE
If a version is clicked then change gem tag

### ISSUE THREAD

**Issue by jnylen** [tenex/rails-assets#43]
Hi,

It would be wonderful that if you click a version like 1.4.8 of Angular then the standard:

> gem 'rails-assets-angular'

turns into 

> gem 'rails-assets-angular', '1.4.8'

**Comment by joshjordan** [comment]
I love that idea. I'm thinking about an overhaul to the gem selection interface. Once I sketch something up, would you mind giving me some feedback on it?

**Comment by jnylen** [comment]
Sure!

**Comment by joshjordan** [comment]
Thanks @jnylen! I'm actually going to keep this open just as a double-check that we get it done in #50.

**Comment by hut8** [comment]
:+1: Looks pretty fixed. @jnylen, feedback appreciated.
