### ISSUE TITLE
SSL certificate needs to be renewed (3 Aug 2018 03:00AM UTC)

### ISSUE THREAD

**Issue by Kenneth-KT** [tenex/rails-assets#430]
The SSL certificate has just expired. It seems the automated certificate renewal is somehow not working.
![image](https://user-images.githubusercontent.com/2994474/43623010-baf3628e-9711-11e8-8901-5bb2defe7a23.png)

**Comment by tiffanypang** [comment]
Having the same problem here.

**Comment by Kenneth-KT** [comment]
Seems there is a script `infrastructure/lets-encrypt-renew-certificate` to be run daily, supposedly for checking and renewing certificate. (defined in `infrastructure/provision-rails-assets.yml`).

However, the function `get-certificate` which actually does the renewal never get called from anywhere (it seems to be).

Is that done intentionally? Am i missing something?
Please advise.

https://github.com/tenex/rails-assets/blob/master/infrastructure/lets-encrypt-renew-certificate

**Comment by Kenneth-KT** [comment]
Created a PR #432 to attempt fixing the issue based on my assumption.

**Comment by jufemaiz** [comment]
<img width="614" alt="screenshot 2018-08-03 15 04 42" src="https://user-images.githubusercontent.com/16481/43625142-ab0c4936-972e-11e8-9327-fdde38310352.png">

Seeing this too. Our build pipeline is broken as a result. 😿

**Comment by Kenneth-KT** [comment]
Seems an overlook that the command that got run daily inside `infrastructure/provision-rails-assets.yml` is actually `letsencrypt renew`, so that cert renewal script modified in #432 could actually be unused.

But I've found this post in let's encrypt forum:
https://community.letsencrypt.org/t/should-we-use-certbot-auto-or-letsencrypt-auto/28290
It saids `letsencrypt` exists in older version and suggests to use `certbot-auto` or `certbot` command instead.

Just an FYI for the rails-assets team.
Since I've no access to server infrastructure, I'm just making wild guesses. Sorry if that's not the correct root cause.

**Comment by PascalPixel** [comment]
Keep it up @Kenneth-KT

**Comment by Kenneth-KT** [comment]
As a quick and dirty workaround in this moment while waiting for the rails-assets.org team to respond, you can simply switch to insecure endpoint:

Look for
```
source 'https://rails-assets.org'
```
Replace with
```
source 'http://insecure.rails-assets.org'
```

That may risk your system in MITM attack and may cause code to be injected into your system, but at least your CI can still pass.

Remember to switch back to https endpoint after this issue has been fixed.

**Comment by ans0600** [comment]
Same as last year

**Comment by aleksandrs-ledovskis** [comment]
It's back. [Certificate](https://censys.io/certificates/6c7f1ebb55f5eee5fe55641b77007aa064968728af9c03dcb725e6fee9139e93) valid till 2018-10-02

**Comment by davidlibrera** [comment]
You can run it every day this way
```
0 0 * * * /root/certbot/certbot-auto renew --keep-until-expiring
```
This way every day certbot try to renew all certificates whose expiry is less than 30 days

usually I use this command

```
0 0 * * * /root/certbot/certbot-auto renew --keep-until-expiring && nginx reload
```

But I don't know if you're using nginx

**Comment by joshjordan** [comment]
Thanks @Kenneth-KT ! We'll be making some changes there. It isn't getting set properly in cron, so when we provision a new server (which happens from time to time), the new machine does not get its auto renew set properly. Will fix.
