### ISSUE TITLE
SSL certificate certificate expired for rails-assets.org

### ISSUE THREAD

**Issue by mirajrajee** [tenex/rails-assets#433]

**Comment by ans0600** [comment]
Same as last year

**Comment by Kenneth-KT** [comment]
Duplicate of #430

**Comment by mirajrajee** [comment]
okey

**Comment by Mihoid** [comment]
Guys! Job stoped 😕. Please help!

**Comment by Kenneth-KT** [comment]
> Guys! Job stoped 😕. Please help!

@Mihoid 
I've proposed a temporary workaround on the 6th comment in issue #430.
https://github.com/tenex/rails-assets/issues/430#issuecomment-410149994

**Comment by Mihoid** [comment]
@Kenneth-KT Thanks. Now will try it.

**Comment by leonardoprg** [comment]
same last year,
I think for the next year will change to use assets dependencies behind `yarn`.

**Comment by redrick** [comment]
Hey guys, kinda stopped deployment of couple projects over here....

From what I see you have letsencrypt certs there and with certbot or some such you should really consider putting it in crontab to prevent these... not the best end of week I got to tell you :)

but I guess is time to embrace webpacker goodness then...

**Comment by aleksandrs-ledovskis** [comment]
It's back. [Certificate](https://censys.io/certificates/6c7f1ebb55f5eee5fe55641b77007aa064968728af9c03dcb725e6fee9139e93) valid till 2018-10-02

**Comment by joshjordan** [comment]
@redrick yes, definitely

**Comment by ervinb** [comment]
the good thing is that it's read only Friday
