### ISSUE TITLE
SSL Certificate Expired Again (2 Oct 2018 04:00AM UTC )

### ISSUE THREAD

**Issue by fatwong** [tenex/rails-assets#436]

**Comment by Kenneth-KT** [comment]
+1

**Comment by micapam** [comment]
😱

**Comment by jufemaiz** [comment]
<img width="830" alt="screen shot 2018-10-02 at 2 08 00 pm" src="https://user-images.githubusercontent.com/16481/46328787-a30aac80-c64c-11e8-9101-dbed22e456e5.png">

See also:

- https://github.com/tenex/rails-assets/issues/435
- https://github.com/tenex/rails-assets/issues/433
- https://github.com/tenex/rails-assets/pull/432 <-- this looks like an actual resolution?
- https://github.com/tenex/rails-assets/issues/431
- https://github.com/tenex/rails-assets/issues/430
- https://github.com/tenex/rails-assets/issues/426
- https://github.com/tenex/rails-assets/issues/420
- https://github.com/tenex/rails-assets/issues/419

+ more @ https://github.com/tenex/rails-assets/issues?utf8=%E2%9C%93&q=ssl

**Comment by house9** [comment]
Of course this happens while I am trying to deploy to production 🤦‍♂️
