### ISSUE TITLE
"Marketing" website should be posted on www., and the api should be root or api.

### ISSUE THREAD

**Issue by krainboltgreene** [tenex/rails-assets#44]
Having the marketing and the endpoint share the same domain is going to suck down the line.

**Comment by teamon** [comment]
Any arguments?

**Comment by sheerun** [comment]
I think for now it's ok. We can change it at any moment. API endpoint won't change anyway.

**Comment by sheerun** [comment]
@krainboltgreene http://rubygems.org/ doesn't seem to have problems with that. Are you sure it's an issue?

**Comment by sheerun** [comment]
@teamon I re-thought it and it can be an issue if enough people (or one hacker) are building components through www and exhaust worker pool. In this case the site would just block. It is not http://rubygems.org/ issue because they don't allow building from www.

**Comment by teamon** [comment]
I'd rather make building via www async (put it in queue, simple ajax polling for status)

**Comment by sheerun** [comment]
I've created new issue for it #47 This one is closed.
