### ISSUE TITLE
https://rails-assets.org SSL expired just now?

### ISSUE THREAD

**Issue by kanejamison** [tenex/rails-assets#440]
The SSL certificate for https://rails-assets.org just expired:

Issued by: Let's Encrypt Authority X3
Expired: Tuesday, January 29, 2019 at 7:00:11 PM Pacific Standard Time

I noticed because my Heroku build failed:

"Retrying fetcher due to error (2/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rails-assets.org/.
       There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'."

**Comment by leshik** [comment]
Seeing this every 3 months. Is it too hard to automate things? There is a wonderful `lego` tool...
