### ISSUE TITLE
Certain version of package missing.

### ISSUE THREAD

**Issue by huangyq23** [tenex/rails-assets#447]
We are getting 404 for
https://rails-assets.org/quick/Marshal.4.8/rails-assets-angular-base64-upload-0.1.14.gemspec.rz

But 
https://rails-assets.org/quick/Marshal.4.8/rails-assets-angular-base64-upload-0.1.13.gemspec.rz
https://rails-assets.org/quick/Marshal.4.8/rails-assets-angular-base64-upload-0.1.15.gemspec.rz
all works.

**Comment by joshjordan** [comment]
We did not have 0.1.14 in our database. If you find a missing package or missing version, please add it here. I have done so and that link is working now.

![image](https://user-images.githubusercontent.com/521674/59852637-38fe7880-933d-11e9-85a0-0e54519aad98.png)
