### ISSUE TITLE
Website returns 504 Gateway timeout error

### ISSUE THREAD

**Issue by billsaysthis** [tenex/rails-assets#45]
http://rails-assets.org returns a 504 error, sticking in www. gets an Nginx not configured message.

**Comment by teamon** [comment]
Thanks @billsaysthis, we are working on it. Please keep in mind that this project hasn't been publicly released yet (it will be very soon, just not yet)

**Comment by sheerun** [comment]
We have severe issues with locking between processes to re-generate indexes. For now site is going down. I'll try to implement some stable locking solution. I cannot find any maintained gem for it, unfortunately.

**Comment by dmilith** [comment]
@billsaysthis www.* will also point to web site now.

**Comment by porada** [comment]
@dmilith, could you simply redirect anything served from `www.rails-assets.org/*` to `rails-assets.org/$1`?

**Comment by dmilith** [comment]
@porada Done redirect from www.rails-assets.org/anything to rails-assets.org/anything

**Comment by porada** [comment]
Thanks! Can I close this issue?

**Comment by sheerun** [comment]
It's not about www or not, but about 504 on homepage because of problems with locking.

**Comment by porada** [comment]
Okay, leaving this to you guys.

**Comment by sheerun** [comment]
This should be resolved by 8f7c0039d1a I made numerous tests regarding file locking and released gem that should hold the standard. I also added 60 seconds timeout for file locking, so there should be no permanently locked processes.

**Comment by sheerun** [comment]
It can be noted, SideTiq was also the problem. It restarted scheduled jobs repeatedly causing 100% CPU and blocking. @teamon Fixed that in 9fa8ba636322
