### ISSUE TITLE
Can't add a gem

### ISSUE THREAD

**Issue by jnylen** [tenex/rails-assets#45]
Hi,
I can't add the gem "angular-h-sweetalert".

The http code returned is 405 Not Allowed

**Comment by hut8** [comment]
Looking now!

**Comment by hut8** [comment]
This has to do with the caching we did with components.json. Fixing now.

**Comment by hut8** [comment]
Fixed and gem built. Sorry for the 22 minute wait!

**Comment by hut8** [comment]
Resolved via 02adb66e88cf40ff3e42993a38a6e3a2517a6504
