### ISSUE TITLE
Expired domain 🤬

### ISSUE THREAD

**Issue by ornsteinfilip** [tenex/rails-assets#450]
RIP

**Comment by ornsteinfilip** [comment]
**Quick fix**

Put `192.241.135.61 insecure.rails-assets.org` in your /etc/hosts and add `source 'http://insecure.rails-assets.org'` to the top of your Gemfile.

**Comment by joshjordan** [comment]
Will be back up as soon as the registrar gets caught up.

**Comment by thadeu** [comment]
Seems to be down me too.

This block my deploy on CI :(

![Screen Shot 2020-01-21 at 21 21 08](https://user-images.githubusercontent.com/77889/72854739-02eaf380-3c94-11ea-8177-fceffd7ef06d.png)
