### ISSUE TITLE
rails-assets.org is down

### ISSUE THREAD

**Issue by leshik** [tenex/rails-assets#451]
![image](https://user-images.githubusercontent.com/443678/61629663-b7896580-acaf-11e9-8aa0-265524eaa881.png)

Can't deploy.

**Comment by joshjordan** [comment]
See https://github.com/tenex/rails-assets/issues/450

Will leave this thread open until resolved

**Comment by i5okie** [comment]
Still down...

**Comment by joshjordan** [comment]
It may still be down for you depending on what DNS servers between the authority and your ISP have cached. Try this nameserver: ns-360.awsdns-45.com

**Comment by rapito** [comment]
Down again :(

**Comment by faken** [comment]
Our deployment is broken because if that.
Any chance somebody can please fix the server.

**Comment by sh3244** [comment]
Is this a scheduled outage? Our CI is broken...

**Comment by atstockland** [comment]
Would be nice to be able to just check a status page or twitter.  I'm in the dark too...and, unable to push to Heroku because of this.

**Comment by joshjordan** [comment]
Working on recovering. I don’t think a status page will add any value since
it would be the same as just checking if the site is up. Just adds another
thing that needs to be updated.

**Comment by andresbarcenas** [comment]
Any update on this?

**Comment by gustavo-iha** [comment]
Would like to know as well

**Comment by joshjordan** [comment]
Please track in https://github.com/tenex/rails-assets/issues/462

**Comment by VincentSim** [comment]
down again

**Comment by lironbeni** [comment]
And down again they go....
