### ISSUE TITLE
rails-assets.org is down

### ISSUE THREAD

**Issue by bubbavcita** [tenex/rails-assets#452]
Howdy,

I am not sure what happened but currently https://rails-assets.org is unavailable. Perhaps there has been some mishap with DNS? Any chance someone can look at this and resolve it?

Thanks!
Bubba

**Comment by joshjordan** [comment]
There was DNS snafu this morning (see https://github.com/tenex/rails-assets/issues/450 ) but it should be good now. Would need you to show what namservers are being returned from your DNS queries so I can help you trace, but this will almost definitely be resolved once TTLs die throughout your chain of DNS servers.

https://isitup.org/rails-assets.org
![image](https://user-images.githubusercontent.com/521674/61637330-52a91d80-ac65-11e9-992e-eb83ad73eeff.png)

**Comment by bubbavcita** [comment]
@joshjordan I see it now working from my mobile device but not from my desktop. This is probably some weird caching issue on my side. In any case, thanks for the prompt response!

**Comment by Teckden** [comment]
the same for me. Still cannot access the web site. I guess I just need to wait more time =(
