### ISSUE TITLE
rails-assets.org is down again

### ISSUE THREAD

**Issue by marek-mazur** [tenex/rails-assets#453]

**Comment by marek-mazur** [comment]
"In development, if you have issues with SSL certificates and security is not a priority, you can use the alternate endpoint http://insecure.rails-assets.org instead."

**Comment by nadrooJ** [comment]
Seems to be every other week now.

**Comment by marek-mazur** [comment]
@joshjordan At least we have live updates every time: https://twitter.com/railsassets ... oh wait ;-)

**Comment by Teckden** [comment]
> "In development, if you have issues with SSL certificates and security is not a priority, you can use the alternate endpoint http://insecure.rails-assets.org instead."

@marek-mazur did that "http://insecure.rails-assets.org" worked for u?
For me it says: "Could not fetch specs from http://insecure.rails-assets.org"

**Comment by marek-mazur** [comment]
@Teckden Yes. It helped.

**Comment by Teckden** [comment]
@marek-mazur  thanx for the reply.
It seems that for some reason our dns servers in VPN have the old address for rails-assets in the cache :(
I guess, need to wait extra time

**Comment by cema-sp** [comment]
Just faced this issue again.
Hope the solution will help someone: just add `192.241.135.61  rails-assets.org` to _/etc/hosts_ and try `curl https://rails-assets.org`.

**Comment by ans0600** [comment]
If you cannot manage an open source project in a reliable fashion, how could customer trust your consultation services? 👎

**Comment by joshjordan** [comment]
@ans0600 would you like a refund? You are also welcome to run rails assets yourself if you are dissatisfied.  See https://github.com/tenex/rails-assets/issues/457#issuecomment-536178487 for statistics I'm tracking. Will update once this outage ends (its on Route 53 to fix right now).

**Comment by ans0600** [comment]
@joshjordan Great attitude. 👍 🏆

**Comment by joshjordan** [comment]
Bypassed Route 53 and updated DNS directly - we're up again. See #459
