### ISSUE TITLE
rails-assets or bower didn't include js file into gem

### ISSUE THREAD

**Issue by sevenmaxis** [tenex/rails-assets#455]
I was upgrading my Rails project and noticed that new versions `rails-assets-spinjs-4.0.0` doesn't have `spinjs` file at all. Here's the structure of gem's folder
![Screenshot from 2019-07-31 15-59-35](https://user-images.githubusercontent.com/293438/62213930-b4c3fa00-b3ac-11e9-90af-49c3007a8b96.png)
But old version does have `spinjs` file
![Screenshot from 2019-07-31 16-06-16](https://user-images.githubusercontent.com/293438/62214173-34ea5f80-b3ad-11e9-9d10-9cef578f2557.png)

That's why in my project I have such error 
`couldn't find file 'spinjs' with type 'application/javascript'`

**Comment by hut8** [comment]
That package dropped bower support: https://github.com/fgnass/spin.js/pull/343

**Comment by hut8** [comment]
https://github.com/fgnass/spin.js/compare/2.3.2...3.0.0 it was dropped as of v3
