### ISSUE TITLE
Rails-assets search is not working

### ISSUE THREAD

**Issue by chalofa** [tenex/rails-assets#456]
rails-assets.org search is broken, returning empty result regardless of the searched term:

![image](https://user-images.githubusercontent.com/217029/63550503-6eb80d00-c4f8-11e9-9aa4-91dcc1d6f606.png)

In "Network", it's not triggering any AJAX request.

I've tried in Chrome, Safari & Firefox, and none works... other people is reporting in Twitter as well.

**Comment by chalofa** [comment]
@joshjordan hi Josh, sorry for tagging you, but is this project still alive? because right now I can't use the search to find some libraries I need to add

**Comment by vasiliy-pdk** [comment]
This is strange because nothing was committed to the repo for a while. Even Gemfile.lock the same. I wonder what could cause the AJAX request not triggering if there were no changes in the codebase? Maybe browsers got updated so some legacy browser feature Angular depends upon stopped working?

**Comment by joshjordan** [comment]
I had the same reaction. It seems there is some process that didn’t execute
properly - probably a background job that didn’t prime the cache. I’ll
solve this this weekend.

**Comment by sandrogomez** [comment]
Is this project still alive?

**Comment by joshjordan** [comment]
Yes, but has not been solved yet. Things look good at the application level
but something is getting coached improperly at the web server level.

**Comment by bear454** [comment]
Is there a workaround?

**Comment by chalofa** [comment]
gosh, I really wish we would have never found rails-assets... now our deploys are totally broken thanks it :disappointed:

**Comment by raykin** [comment]
@chalofa it still not work, why close the issue?
