### ISSUE TITLE
rails-assets.org is down again again

### ISSUE THREAD

**Issue by victorlcampos** [tenex/rails-assets#459]
🙂

**Comment by andriimosin** [comment]
☹️

**Comment by cema-sp** [comment]
Hope it could help: https://github.com/tenex/rails-assets/issues/453#issuecomment-543402282

**Comment by victorlcampos** [comment]
Guys, this project is an alicerce of rails community 

Shit happens and they always fix it very fast

I open this issue only to warning

**Comment by joshjordan** [comment]
Looks like a Route 53 issue. The site is up  (see https://github.com/tenex/rails-assets/issues/453#issuecomment-543402282 ) but DNS resolution is failing. Looking into it.

**Comment by joshjordan** [comment]
This is in AWS's hands at the moment without an ETA from their side. I'm going to update DNS records manually and bypass our Route 53 configuration. If it persists throughout the evening, we'll move to another provider.

**Comment by joshjordan** [comment]
rails-assets.org is up again. Will continue to monitor and switch back to Route 53 when they resolve bugs on their end.
