### ISSUE TITLE
SSL certificate for rails-assets.org expired on 11/26/2019 10:00pm  ET (03:00 UTC)

### ISSUE THREAD

**Issue by stockandawe** [tenex/rails-assets#460]
![Screen Shot 2019-11-26 at 10 50 04 PM](https://user-images.githubusercontent.com/1410662/69692344-b2925380-109f-11ea-93c8-7a23ccf6bb43.png)

**Comment by etipton** [comment]
you're off by 13 seconds

**Comment by gregoryfm** [comment]
Any news?

**Comment by yamitake** [comment]
When can you recover it?
Can I donate?

**Comment by chriscz** [comment]
@joshjordan I believe this is fairly urgent

**Comment by aleksandrs-ledovskis** [comment]
Workaround, if being pressed to use rails-assets "as-is"/unsecurely (and not changing `Gemfile`)

Can add following build steps in `Dockerfile` context:

```
RUN echo ':ssl_verify_mode: 0' > ~/.gemrc
ENV BUNDLE_SSL_VERIFY_MODE='0'
```

Same options (bar `RUN`/`ENV`) also are applicable for local development/non-Docker environments

**Comment by kurata-precena** [comment]
I used `http://insecure.rails-assets.org` instead of `https://rails-assets.org`.
This way is written on https://rails-assets.org

> In development, if you have issues with SSL certificates and security is not a priority, you can use the alternate endpoint http://insecure.rails-assets.org instead.

**Comment by yoyostile** [comment]
Well, maybe using something like Cloudflare is an option, as this happens fairly often:
https://github.com/tenex/rails-assets/issues?utf8=%E2%9C%93&q=is%3Aissue+certificate

**Comment by mobilutz** [comment]
Does tenex still exist?
Their website just returns `Not found` and also all the Build Status on `rails-assets.org` is looking strange:
http://tenex.tech/
https://rails-assets.org/status

Maybe it is time, to look for an alternative 😦

**Comment by csrutil** [comment]
Yeah, I think so, it's too hard for me to deal that issues.

**Comment by joshjordan** [comment]
Resolving this issue shortly.

**Comment by joshjordan** [comment]
This is resolved. @stockandawe  @etipton  @gregoryfm  @yamitake @chriscz @aleksandrs-ledovskis @kurata-precena @yoyostile @mobilutz @csrutil

**Comment by rtsinani** [comment]
Thanks @joshjordan I really appreciate it 🙏

**Comment by joshjordan** [comment]
@rtsinani :+1:

**Comment by bendilley** [comment]
> This is resolved.

Until Sunday, 26 January 2020 at 03:00:22 UTC anyway 😶

**Comment by aleksandrs-ledovskis** [comment]
@joshjordan If moving to CloudFlare fronted SSL termination is not an option, could you explore signing up for some certificate tracking service (e.g. https://certificatemonitor.org/)?

Let's Encrypt's ACME clients should renew certificate long (weeks) before it expires, so getting pings by some service N days before expiry will be tell-tale of problem needing manual intervention.

**Comment by bendilley** [comment]
That date is only 60 days off so the auto-renewal must have happened 30 days ago, but presumably the webserver hadn't been reloaded to pick it up. If it's certbot you're using @joshjordan and it's running on the same box as the webserver, it can be configured to reload the webserver on a successful renewal (see [the docs](https://certbot.eff.org/docs/using.html#renewing-certificates)) - I don't know your setup tho, obvs.

**Comment by marcelotedeschi** [comment]
It seems this issue has been fixed!
