### ISSUE TITLE
Possible failure of rails-assets.org TLS certificate renewal automation

### ISSUE THREAD

**Issue by aleksandrs-ledovskis** [tenex/rails-assets#461]
@joshjordan Could you please verify if `certbot`(?) is working adequately on rails-assets.org serving machine?

[The current TLS certificate](https://crt.sh/?id=2045205205) expiry is less than 30 days away (on 2020-01-26) and ACME client should have run the renewal/unless there's different threshold.

**Comment by joshjordan** [comment]
Certbot is fine, it’s nginx that isn’t picking up the new certificate. I’ll
restart it today.

**Comment by aleksandrs-ledovskis** [comment]
Indeed, I have missed it somehow that new cert was issued on 2019-12-27 ([@ censys](https://censys.io/certificates/fd4559e44776bfaa0374435857aa3ae5b7111fb1ba2d29e2727c6de66c63bc36)).

As failure to act would have caused an outage similar to ones we have experienced in 2019, would it be a tall order to introduce a daily/weekly/fortnightly Nginx restart cron task that would unconditionally do its job?

**Comment by joshjordan** [comment]
That actually does exist, but something Nginx-related is holding an open
file handle on the old certificate. We’ve spent quite awhile debugging but
have not turned up anything. Often we end up just doing manual restarts.

**Comment by joshjordan** [comment]
However, that’s not to say the issue is closed. Definitely still working on
it, but not always actively.

**Comment by aleksandrs-ledovskis** [comment]
Maybe "restart" is a wrong approach then. How about stop/start? That should clear any open handles.

**Comment by aleksandrs-ledovskis** [comment]
Another idea that I've floated in one previous issue was move to CloudFlare fronted TLS termination. Do you hold any strong objection; are there technical/legal obstacles to implementation?

That would make this whole local-renewal a non-issue for a foreseeable future.

**Comment by sheerun** [comment]
maybe you are reloading nginx instead of restarting it
