### ISSUE TITLE
rails-assets.org is down again again

### ISSUE THREAD

**Issue by huangyq23** [tenex/rails-assets#462]
```
 Bundler::HTTPError Could not fetch specs from https://rails-assets.org/
```

**Comment by eveevans** [comment]
Same here...

**Comment by kelsonpw** [comment]
Also getting this error

**Comment by Awatatah** [comment]
same

**Comment by shouta-dev** [comment]
same

**Comment by Awatatah** [comment]
@joshjordan

**Comment by wkaskie** [comment]
#329 suggests a mirror site.  Any progress on that?

**Comment by victorlcampos** [comment]
Any suggests?

**Comment by nathanhinchey** [comment]
There's a build error in the google search results, so at least that suggests that the domain isn't expired (like in #450).
<img width="566" alt="Screen Shot 2020-01-21 at 4 50 19 PM" src="https://user-images.githubusercontent.com/8533472/72846345-64986700-3c6e-11ea-8c0b-752c430f6330.png">

(PS: #451, so that this issue shows up in that one)

**Comment by asymptotik** [comment]
I can't afford these outages. Will be looking to dump this dependency ASAP.

**Comment by gabrielrdrguez** [comment]
Down here too

**Comment by wkaskie** [comment]
> Any suggests?

* Dupe the site at another domain with another host e.g rails-assets.io
* Get a more reliable host (I'm not sure what the current host is, but AWS is a solid option)
* A more complicated solution would again require an AWS-like service, but spin up multiple servers and configure auto cutover and auto-rollback on critical failures

**Comment by victorlcampos** [comment]
Sry, 
I’m not the maintainer, I asked for a workaround suggestion

**Comment by johnmcauley** [comment]
Down for us also, any ideas?

**Comment by inertia186** [comment]
https://www.spritle.com/blogs/2015/09/25/three-ways-to-manage-assets-in-rails/

**Comment by gabrielrdrguez** [comment]
@victorlcampos May not work right now as it's already down, but you may use a repo manager like https://www.sonatype.com/nexus-repository-oss to act as a proxy / cache for gems

**Comment by Awatatah** [comment]
3 hours and still down...

**Comment by codeodor** [comment]
Is there any reason to not do this?

```ruby
#source 'https://rails-assets.org' do
  gem 'rails-assets-tether', '>= 1.1.0'
#end
```

**Comment by johnmcauley** [comment]
> Is there any reason to not do this?
> 
> ```ruby
> #source 'https://rails-assets.org' do
>   gem 'rails-assets-tether', '>= 1.1.0'
> #end
> ```

I wont find them as there is no source.

**Comment by johnmcauley** [comment]
If you are having issues you can bundler show rails-assets-tether, copy the gem into the vendor directory and reference using https://bundler.io/v2.0/man/gemfile.5.html#PATH. Then you can deploy safely - I hope.

**Comment by victorlcampos** [comment]
We are trying bundle package to deploy safety ... I hope this work

**Comment by codeodor** [comment]
@johnmcauley  

In my scenario, I was assuming `source 'https://rubygems.org'` would also be in the gemfile, and it would fall back to that. 

So to be more clear, is there any reason not to use `source 'https://rubygems.org'` instead of `source 'https://rails-assets.org'`?

**Comment by johnmcauley** [comment]
> @johnmcauley
> 
> In my scenario, I was assuming `source 'https://rubygems.org'` would also be in the gemfile, and it would fall back to that.
> 
> So to be more clear, is there any reason not to use `source 'https://rubygems.org'` instead of `source 'https://rails-assets.org'`?

Reference the vendor dir - see how it’s done here: https://bundler.io/v2.0/man/gemfile.5.html#PATH

**Comment by owen-c** [comment]
> @johnmcauley
> 
> In my scenario, I was assuming `source 'https://rubygems.org'` would also be in the gemfile, and it would fall back to that.
> 
> So to be more clear, is there any reason not to use `source 'https://rubygems.org'` instead of `source 'https://rails-assets.org'`?

Yes the reason is it would not work. The rails-assets-* gems do not exist in rubygems.org

It may appear to work on your local machine b/c you have all the rails-assets-* gems installed already, but if you try to bundle install on a clean machine it will fail to find them.

**Comment by joshjordan** [comment]
Working on recovering.

**Comment by nonatojunior** [comment]
I'm not able to run the bundle install. This makes my project impossible to progress.

**Comment by thadeu** [comment]
seems to be down me too

**Comment by joshjordan** [comment]
Yes, when its down its down for everyone :) Working on a bit of a complex logistical issue with Digital Ocean support, I'm afraid. Will update this thread ASAP when I have more info.

**Comment by EnriqueCanals** [comment]
@joshjordan If there's anything I can do to help you resolve this issue, please don't hesitate to send over a DM. I definitely appreciate the effort put into maintaining this service, so I'm more than glad to provide any assistance I can to help resolve this outage.

**Comment by joshjordan** [comment]
@EnriqueCanals accept my request on twitter and I'll hit you up for help.

**Comment by joshjordan** [comment]
Everyone, we're at a bit of a roadblock and it may be a few hours until we've resolved it. In the meantime, this is a great chance to switch to webpacker or vendor your javascript libs to reduce your dependency footprint! Also working on a solution to host another instance of Rails Assets and repoint the DNS at that. Will let you all know, once again, when I have more to share.

**Comment by joshjordan** [comment]
We're probably about an hour away from getting this fixed.

**Comment by hut8** [comment]
No luck. Will look at this again in a few hours. The gentleman who offered
to set up another instance for us has not responded.

**Comment by richpeck** [comment]
How much does it cost to keep it online?

**Comment by krazyjakee** [comment]
Is there a docker image so I can run rails-assets on my own servers?
The readme has a development guide but how can I run this for production?

**Comment by madoleary** [comment]
Still down.

**Comment by HariShankarS** [comment]
Any work around ?

**Comment by jaredsohn** [comment]
Was able to work around this by removing or replacing gems that use rails-assets (could tell by looking at the list of the `source 'https://rails-assets.org'` section of the Gemfile). Fortunately it was only one gem and it wasn't critical. (It was just timezone detection and we used that only to set the default timezone for new users.)

**Comment by ksbek** [comment]
I use 5 rails-assets gems in my RoR project. 
For temporary solution, I created git repo on my github account and upload those gems to it.
https://github.com/ksbek/rails-assets

And set gem path in the Gemfile like this.
gem 'rails-assets-chartist', github: 'ksbek/rails-assets', branch: 'chartist'
gem 'rails-assets-jquery', github: 'ksbek/rails-assets', branch: 'jquery'
gem 'rails-assets-momentjs', github: 'ksbek/rails-assets', branch: 'momentjs'
gem 'rails-assets-notifyjs', github: 'ksbek/rails-assets', branch: 'notifyjs'
gem 'rails-assets-timeago', github: 'ksbek/rails-assets', branch: 'timeago'

**Comment by BlackAppl3** [comment]
Is there any update?

**Comment by sharshenov** [comment]
As temporary workaround might work:
1. Get server ([referral link!](https://m.do.co/c/df1384cbbfe7) to get credit for 2 months)
2. Spin up [your own gemserver](https://github.com/geminabox/geminabox)  `docker run -d --restart unless-stopped -p 80:9292 -P -h geminabox --name geminabox -e USERNAME=myuser -e PASSWORD=mypassword spoonest/geminabox:latest`
3. Go to your bundler cache dir `cd $GEM_HOME/cache`
4. [Push gems](https://github.com/geminabox/geminabox#client-usage) to your server `gen inabox rails-assets-somegem-1.0.gem -g http://myuser:mypassword@yourserveraddress`
5. Replace `https://rails-assets.org` with `http://yourserveraddress` in Gemfile

Then think about migrating to Webpacker or other solution

UPD: added referral link to get temporary server in case if it might be helpful to somebody

**Comment by joshjordan** [comment]
@krazyjakee I don't think so. @richpeck its not terrible, but cost isn't the primary issue right now.

If anyone is able to help out with temporary hosting, please contact me so we can work out a plan. The short of the situation is that we're locked out the Digital Ocean right now, and unable to get in to resolve the issue. Working closely with them on it.

Edit: fix wording to remove confusion.

**Comment by miguelbernadi** [comment]
@joshjordan We are willing to provide temporary hosting. Please contact me for details on setup.

**Comment by joshjordan** [comment]
Thanks for your patience, all. This is resolved. Please confirm you're able to bundle again.

**Comment by bcardiff** [comment]
As a workaround while this was being solved, I attempt to create the packages locally for vendoring.

If someone wants to go that way I dropped the following gist https://gist.github.com/bcardiff/3916e61bcce03959748468e89b53d19a

**Comment by eveevans** [comment]
I don't when this was solved, but now it is working again :)
