### ISSUE TITLE
rails-assets.org is down again

### ISSUE THREAD

**Issue by faken** [tenex/rails-assets#464]
Its down again, could somebody check the cause of the problem.

**Comment by nathanhinchey** [comment]
related: #462, #459, #453, #452, #448, #451, #305, #292, #274

**Comment by hut8** [comment]
On it.

**Comment by hut8** [comment]
Fixed. We’ve been having trouble with our digital ocean account. Working on
resolving it with them so it does not reoccur.

**Comment by faken** [comment]
Thank you very much for your support!

**Comment by lumaxis** [comment]
Thanks so much for the quick resolution @hut8 !
