### ISSUE TITLE
Bundler::HTTPError Could not fetch specs from https://rails-assets.org/

### ISSUE THREAD

**Issue by rgaufman** [tenex/rails-assets#471]
Is rails-assets down at the moment? - My CircleCI is failing with:

```
Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rails-assets.org/
 

 
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rails-assets.org/
 

 
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rails-assets.org/
 

 
Could not fetch specs from https://rails-assets.org/
 
 
Exited with code exit status 17 
CircleCI received exit code 17 
```

**Comment by hut8** [comment]
Appears to be. On it.

**Comment by hut8** [comment]
Coming back up in ~5 min.

**Comment by hut8** [comment]
Scratch that, available now.

**Comment by rgaufman** [comment]
Thank you!!

**Comment by jmeattle** [comment]
@hut8 Bump - getting this error again this morning.

```
$ bundle install
Fetching source index from https://rails-assets.org/

Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rails-assets.org/

Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rails-assets.org/

Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rails-assets.org/

Could not fetch specs from https://rails-assets.org/
```

```
$ curl -I https://rails-assets.org/
curl: (7) Failed to connect to rails-assets.org port 443: Operation timed out
```

**Comment by jmeattle** [comment]
Follow-up issue - https://github.com/tenex/rails-assets/issues/472

**Comment by Aviv389** [comment]
This is happening again right now

**Comment by joshjordan** [comment]
Strange timing. Use http://insecure.rails-assets.org for now until I can
fix.

**Comment by hut8** [comment]
This isn't still happening for you right?

**Comment by Aviv389** [comment]
it does :(
<img width="798" alt="image" src="https://user-images.githubusercontent.com/81958738/166132102-64968b5e-1fff-4ce9-93cc-65575a82a4ff.png">

**Comment by joshjordan** [comment]
I think you have the wrong URL. Use https.

**Comment by Aviv389** [comment]
It's working now Tx

**Comment by meredithlind** [comment]
@joshjordan / @hut8 I am seeing this issue again. I tried `http://insecure.rails-assets.org/` as well, but no luck.
```
#0 22.50 Fetching source index from https://rails-assets.org/
#0 82.58
#0 82.58 Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rails-assets.org/
#0 142.6
#0 142.6 Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rails-assets.org/
#0 202.7
#0 202.7 Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rails-assets.org/
#0 262.7
#0 262.8 Could not fetch specs from https://rails-assets.org/

**Comment by joshjordan** [comment]
Your error log shows a mismatch between the url scheme and the host name.
Use https with rails-assets.org

The certificate is currently valid until Nov 18

**Comment by meredithlind** [comment]
Looks like I posted the wrong logs initially - I was seeing the same output using `https`. At any rate, it seems to be working fine now! Thanks

**Comment by xeruf** [comment]
https://rails-assets.org is online, but I am getting this exact error, everything configured appropriately to HTTPS - the exact same config used to work until about a week ago :/

**Comment by hut8** [comment]
@xeruf does http://insecure.rails-assets.org work?

**Comment by xeruf** [comment]
The issue seems to be local, as rubygems also fails, still trying to find out what is going on...
