### ISSUE TITLE
Failing to connect to rails-assets

### ISSUE THREAD

**Issue by nbrien** [tenex/rails-assets#472]
Fetching source index from https://rails-assets.org/
---
Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rails-assets.org/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rails-assets.org/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rails-assets.org/
Could not fetch specs from https://rails-assets.org/

**Comment by filipealc** [comment]
same problem here as @nbrien ! Any news from the team?

**Comment by hut8** [comment]
Looking.

**Comment by joshjordan** [comment]
Hmm. The failing requests are (not surprisingly) not reaching our server. Can you provide more detail? Perhaps a trace route? We may be seeing external intermittent internet issues -- none of our alarms have gone off regarding server down or unreachable.

Note the 23 mins ago here:
![image](https://user-images.githubusercontent.com/521674/88063874-89e03200-cb38-11ea-8a8b-7fc582258d3b.png)

Lets keep this open so folks can collaborate on tracking this down.

**Comment by jmeattle** [comment]
It's now working for me.

**Comment by filipealc** [comment]
it has comeback for us.
