### ISSUE TITLE
bower is deprecated, is rails-assets deprecated too?

### ISSUE THREAD

**Issue by senid231** [tenex/rails-assets#474]
on https://bower.io/docs/creating-packages/ I see messages like "As Bower is deprecated, registering new Bower packages is not supported anymore" and "While Bower is maintained, we recommend using Yarn and Webpack or Parcel for front-end projects read how to migrate!"

should we consider rails-assets are deprecated too? Or maybe some plan to use npm registry?

**Comment by joshjordan** [comment]
Rails Assets will remain available as a tool for those using Bower package, with no plans to formally deprecate it But, you should know that using Rails Assets means you're using the deprcated Bower platform. With the addition of webpacker in newer rails applications, and the predominance of npm generally, we'll encourage folks starting new projects to use those tools instead. No need to move older projects off of RA, though.

**Comment by joshjordan** [comment]
Please
