### ISSUE TITLE
https://rails-assets.org is down (2021-05-24)

### ISSUE THREAD

**Issue by bfool** [tenex/rails-assets#475]
![image](https://user-images.githubusercontent.com/10784256/119305369-3defa380-bc9b-11eb-9ac3-065be0b00685.png)

![image](https://user-images.githubusercontent.com/10784256/119305481-5d86cc00-bc9b-11eb-9366-4639c2a459cd.png)

**Comment by m-an** [comment]
+1 The SSL certificate for rails-assets.org has expired

**Comment by m-an** [comment]
For anyone having an emergency deployment like me, I found using http://insecure.rails-assets.org/  to be a temporary solution.

Just don't forget to change it back when the certificate issue is resolved!

**Comment by harrikauhanen** [comment]
Yup, would be great if fixed.

**Comment by mainameiz** [comment]
Why you couldn't make an automatic reissueing of certificates?

**Comment by jimbali** [comment]
Is this project even alive? 😬😬😬

**Comment by hut8** [comment]
Resolving shortly.

**Comment by whyman** [comment]
ITS BACK! Thanks @hut8!
