### ISSUE TITLE
rails-assets.org has an invalid/expired letsencrypt cert (2021

### ISSUE THREAD

**Issue by zswanson** [tenex/rails-assets#477]
Your site letsencrypt cert appears to have expired this morning. We're getting errors from rails builds pulling from the site complaining of invalid TLS.

sh-4.2$ cat DST-Root-CA-X3.pem | openssl x509 -noout -enddate
notAfter=Sep 30 14:01:15 2021 GMT

**Comment by hut8** [comment]
![image](https://user-images.githubusercontent.com/363720/135540435-1edca9a1-2fbe-488d-ad3c-da3abd23724d.png)

**Comment by hut8** [comment]
What IP address does rails-assets.org resolve to on your machine that's getting errors? Might be connecting to a failover server; I need to make sure that server has an updated cert as well.

**Comment by hut8** [comment]
@joshjordan check this out: https://docs.digitalocean.com/products/accounts/security/certificates/

**Comment by zswanson** [comment]
We've managed to get a patch in for the CA certificates from redhat that
resolves this on the client side, but that Let's Encrypt intermediate  will
still cause issues for older systems.

**Comment by m-an** [comment]
For anyone having an emergency deployment like me, I found using http://insecure.rails-assets.org/ to be a temporary solution.

Just don't forget to change it back when the certificate issue is resolved!

**Comment by SuperTux88** [comment]
@zswanson and @m-an: There is nothing rails-assets can do about this (at least this time it isn't rails-assets fault, their cert is just fine), but you need to update your systems if you have problems accessing it.

**Comment by kknd113** [comment]
For anyone on AWS: https://aws.amazon.com/premiumsupport/knowledge-center/ec2-expired-certificate/

**Comment by shelmire** [comment]
@kknd113 Thanks!
