### ISSUE TITLE
Handle version with || inside

### ISSUE THREAD

**Issue by sheerun** [tenex/rails-assets#49]
For example `jquery: '~1.8.0 || ~1.9.0'` should be translated to `add_dependency 'jquery', ['>= 1.8.0', '< 1.10.0']`

**Comment by tallica** [comment]
@sheerun This is related: https://github.com/urish/angular-spinner/blob/master/bower.json#L12

**Comment by sheerun** [comment]
@teamon It's worth noticing, that rubygems does not support "or" operator for versions, only "and"

**Comment by sheerun** [comment]
I don't think I'll be ever implemented. PR is welcome.
