### ISSUE TITLE
SSL certificate for rails-assets.org  expired on Nov 19 2022

### ISSUE THREAD

**Issue by karim-semmoud** [tenex/rails-assets#495]
SSL certificate for rails-assets.org expired today
Expires On	Saturday, November 19, 2022 at 5:47:21 AM
This is causing multiple issues when accessing the website and also when using bundle
![Screenshot from 2022-11-19 14-14-40](https://user-images.githubusercontent.com/114252883/202852641-1dcdb730-a48c-4def-a953-f262b54435e3.png)

**Comment by hut8** [comment]
Fixed. Sorry about that. I will figure out why later.
