### ISSUE TITLE
Icon/logo

### ISSUE THREAD

**Issue by teamon** [tenex/rails-assets#5]

**Comment by porada** [comment]
@teamon, don’t you like the avatar that’s currently used by the organization? :wink:

**Comment by teamon** [comment]
yellow == js, rails-assets is more that js! ;)

TBH I'm fine with that, just make favicon version

**Comment by porada** [comment]
How lame of me:

> If you make a commit in a non-default branch with the `Fixes #33` syntax, the issue is referenced with a tooltip. [#](https://help.github.com/articles/closing-issues-via-commit-messages)
