### ISSUE TITLE
Search and component page separation

### ISSUE THREAD

**Issue by joshjordan** [tenex/rails-assets#50]
Have a better, separate page for each component. Use search results just to decide which one you want.

**Comment by joshjordan** [comment]
Probably addresses #49

**Comment by joshjordan** [comment]
## Changes to search / home page

![image](https://cloud.githubusercontent.com/assets/521674/13557403/9a9ceb04-e3bd-11e5-87bf-ea6ee3910080.png)

## Which links to this component / install page

![image](https://cloud.githubusercontent.com/assets/521674/13557406/a334eb9a-e3bd-11e5-8965-c49521a0cace.png)
![image](https://cloud.githubusercontent.com/assets/521674/13557407/a9ad714a-e3bd-11e5-9603-e30540bd3699.png)

**Comment by joshjordan** [comment]
@hut8 looking for feedback. My goal is to declutter the UI and make it less confusing for first time users.

**Comment by joshjordan** [comment]
@jnylen your suggestion in #43 fits right in here, I think. In step #2, the version would be listed when a non-latest version is chosen. I'd love to get your feedback on that and on the rest of the UI I've posted here.

**Comment by hut8** [comment]
@joshjordan feedback:
Have you used https://invisionapp.com/ ? If not, it's cool and is more interactive than PNGs :smile: 

In general, I think these are all great ideas and shouldn't be too hard to implement. The only concern I have is the "add scripts and stylesheets" section. How do we know what things needed to be added? "Adding all of them" could be an answer, but of course order matters, and I'm not sure that's specified anywhere necessarily. What are your thoughts on this one point?

**Comment by joshjordan** [comment]
@hut8 nice! I tried to take on only things that would be easy to add here, and not any new functionality (hence no CLI or `patch` in this mockup).

Rails assets already does this, but its so convoluted between how to setup for rails-assets, how to add the gem, and how to reference the assets. That's a big part of the motivation for this PR - you didn't even know it did this!

![image](https://cloud.githubusercontent.com/assets/521674/13614631/7940c646-e53f-11e5-88a6-78f2c0dc51ef.png)

**Comment by joshjordan** [comment]
Another screenshot to show that there is more intelligence here than "require every JS and CSS file":

![image](https://cloud.githubusercontent.com/assets/521674/13614706/cff9c7da-e53f-11e5-9d72-eede9a25dabe.png)

**Comment by hut8** [comment]
OK Cool, so this is perfect then.

**Comment by joshjordan** [comment]
Discussed offline. Add a  “Need help? <a>Visit the project homepage</a>” link at the end of the instructions.

**Comment by jnylen** [comment]
Looks nice. Maybe offtopic but, is there going to be a "Follow" function to get notification when an version is out etc?

Also if it's possible to fix the "honey.js.js" thing when the name itself have a ".js" in the name.

**Comment by joshjordan** [comment]
Hadn't considered either of those, but they are great ideas. I'm going to spin them off into separate issues.

**Comment by hut8** [comment]
Done :confetti_ball:
