### ISSUE TITLE
 hostname "rails-assets.tenex.tech" does not match the server certificate

### ISSUE THREAD

**Issue by jnylen** [tenex/rails-assets#55]
`Gem::RemoteFetcher::FetchError: hostname "rails-assets.tenex.tech" does not match the server certificate (https://rails-assets.tenex.tech/gems/rails-assets-tether-1.1.1.gem)`

**Comment by hut8** [comment]
Yikes, that's a big deal. https://www.ssllabs.com/ssltest/analyze.html?d=rails-assets.tenex.tech says it's fine though. Can you try in a browser? Or tell us at least what hostname the server certificate says it has?

**Comment by jnylen** [comment]
Might have been a hiccup when I did bundle install.
I ran it again afterwards and it went through.
