### ISSUE TITLE
Move gems to S3

### ISSUE THREAD

**Issue by hut8** [tenex/rails-assets#56]
We've had the sidekiq build process now killed twice because of running out of memory. This morning, I increased our swap file to 4 GB as a stop gap, but then ran out of disk space.  Digital Ocean is generous enough to sponsor us, but we still need to be responsible with usage.

The `/gems` subdirectory of public has 30GB of stuff in it (there are no subdirectories). This is sort of a headache. Vultr.com has attachable block-storage devices just  like S3, but DO doesn't have that.

For the immediate future, as basically an emergency fix, I don't have much of a choice but to just increase the size of our droplet, which is a huge waste of resources, since provisioning a 30GB instance and just mounting that via NFS would be useless (it is already almost 30GB in that one directory).

**Comment by joshjordan** [comment]
Still thinking about pushing the gems out to S3.

**Comment by hut8** [comment]
Gems that have already been produced are now living there. Scripting out the switch tomorrow.

**Comment by hut8** [comment]
Backing these up now, then I'm going to switch them.

**Comment by hut8** [comment]
Switched. The gems are now being served from s3! neat. Also I tested it and it seems fine.

TODO: Write script to mount s3 on startup.
