### ISSUE TITLE
Something gonna bad with version lock

### ISSUE THREAD

**Issue by jandudulski** [tenex/rails-assets#56]
```
Bundler could not find compatible versions for gem "rails-assets-angular":
  In Gemfile:
    rails-assets-angular-route (= 1.2.4) ruby depends on
      rails-assets-angular (= 1.2.3) ruby

    rails-assets-angular (1.2.4)
```

but manifest for [angular-route](https://github.com/angular/bower-angular-route/blob/master/bower.json) looks ok:

``` json
{
  "name": "angular-route",
  "version": "1.2.4",
  "main": "./angular-route.js",
  "dependencies": {
    "angular": "1.2.4"
  }
}
```

**Comment by sheerun** [comment]
Could you post relevant parts of Gemfile and Gemfile.lock?

**Comment by jandudulski** [comment]
Gemfile:

``` ruby
gem 'rails-assets-angular', '1.2.4'
gem 'rails-assets-angular-route', '1.2.4'
```

I cannot do `bundle update` so Gemflie.lock is outdated right now.

**Comment by sheerun** [comment]
I doesn't matter, could you post those entries from Gemfile.lock?

**Comment by sheerun** [comment]
OK, I recreated issue, nvm.

**Comment by sheerun** [comment]
If you look at commits in this repo, it turns out they fixed this dependency a day after releasing 1.2.4, and rails-assets built this component before that fix: https://github.com/angular/bower-angular-route/commits/master

Rails Assets is working OK. I'm not sure what to do with such cases.

**Comment by sheerun** [comment]
I've re-builded this gem. Please try:

```
gem uninstall rails-assets-angular-route
bundle install
```

**Comment by jandudulski** [comment]
We should probably slap angular guys :wink: helped, thanks!
