### ISSUE TITLE
Remove the beta badge when it’s out of beta

### ISSUE THREAD

**Issue by porada** [tenex/rails-assets#61]
![](http://images3.wikia.nocookie.net/__cb20090707173545/wykopedia/pl/images/9/9b/200px-CaptainobviousChooseOption.jpg)

**Comment by sheerun** [comment]
Make something useful instead and define requirements to get out of beta ;>

**Comment by porada** [comment]
More precisely, please.

**Comment by sheerun** [comment]
What requirements must be fulfilled to decide to go out of beta.

**Comment by teamon** [comment]
Let's at least wait a couple of weeks

**Comment by sheerun** [comment]
I'm closing this. It just clutters the issues.
