### ISSUE TITLE
Handle "Build::BowerError: Package html5-shiv not found" with nice message

### ISSUE THREAD

**Issue by teamon** [tenex/rails-assets#62]

**Comment by sheerun** [comment]
no way to do that

**Comment by teamon** [comment]
There is always a way. We can at least optimistically parse bower error message with regexp

**Comment by sheerun** [comment]
Oh, you meant Bower error, not rubygems error. That's possible.

**Comment by sheerun** [comment]
Message now says: "Package html5-shiv not found"
