### ISSUE TITLE
Broken underscore package

### ISSUE THREAD

**Issue by teamon** [tenex/rails-assets#63]
```
⌘ ~ λ gem install rails-assets-underscore --source https://rails-assets.org
Fetching: rails-assets-underscore-1.2.2.gem (100%)
This component doesn't define main assets in bower.json.
Please open new pull request in component's repository:
https://github.com/jashkenas/underscore
Successfully installed rails-assets-underscore-1.2.2
```

but

https://github.com/jashkenas/underscore/blob/master/bower.json

and

https://dl.dropboxusercontent.com/s/crbmj8s4wrnabsy/2013-12-12%20at%2017.48.png

**Comment by sheerun** [comment]
It's not a bug. underscore 1.2.2 has no bower.json

https://github.com/jashkenas/underscore/tree/8c346141dc9687c5952991195eefe1988cf92124

**Comment by teamon** [comment]
Right, they were added in https://github.com/jashkenas/underscore/commit/8f808971a73e8495c7886319ad825e5a7583f936 but this hasn't been released yet.

**Comment by porada** [comment]
Let’s silently build this gem with `lodash.underscore.js`.

**Comment by sheerun** [comment]
what do you mean?
