### ISSUE TITLE
group :assets - Rails 4

### ISSUE THREAD

**Issue by onlymejosh** [tenex/rails-assets#64]
First off - Great idea,very excited to start using this. 

group :assets is depreciated in Rails 4. The readme needs updating. Shall I submit a pull request?

**Comment by teamon** [comment]
Thanks :)

PRs are more than welcome.

**Comment by onlymejosh** [comment]
Just realised its on the website do you use gh-pages?

Josh
Serious Fox

**Comment by teamon** [comment]
It is here https://github.com/rails-assets/rails-assets/blob/master/app/views/shared/_diff_gemfile.html

**Comment by teamon** [comment]
Done in https://github.com/rails-assets/rails-assets/pull/65
