### ISSUE TITLE
Gem version was here yesterday and gone today

### ISSUE THREAD

**Issue by masonjm** [tenex/rails-assets#64]
This is strange, and I'm not sure if it's an issue with rails-assets or something upstream.

Yesterday `rails-assets-d3` had version `3.5.16` available. Today, the latest version is `3.5.14`. `npm` still lists `3.5.16`, but I'm not sure if that's relevant.

I also triggered a rebuild for `d3`, but that didn't change anything.

**Comment by joshjordan** [comment]
Hi @masonjm. `rails-assets` is currently experiencing a backlog of builds. We just switched servers today and got slammed with a large number of requests for gems that hadn't been built on the new machine. It looks like `3.5.16` is in the queue (https://rails-assets.org/status) but it may be around an hour before we chew through everything that's ahead of it. Sorry for the inconvenience! Should be a one-time thing.

May we keep this issue open to see if this clears up later tonight? I am actively monitoring the build queue.

**Comment by joshjordan** [comment]
@masonjm it looks like `3.5.16` is available now. Can you confirm?

**Comment by masonjm** [comment]
Confirmed. Thanks :-) 

And great job on the server move! It was almost seamless :-D.
