### ISSUE TITLE
dependency weirdness (isotope 2.0.0.beta.3)

### ISSUE THREAD

**Issue by aaronchi** [tenex/rails-assets#67]
I was testing this out and tried to install isotope 2.0.0.beta.3. It installs duplicate dependencies with funny names (includes the owner) and then the js include doesn't include the correct dependencies.

```
Installing rails-assets-desandro--eventie (1.0.3) 
Installing rails-assets-desandro--doc-ready (1.0.2) 
Installing rails-assets-desandro--get-style-property (1.0.3) 
Installing rails-assets-desandro--get-size (1.1.6) 
Installing rails-assets-desandro--matches-selector (1.0.1) 
Installing rails-assets-eventEmitter (4.2.6) 
Installing rails-assets-eventie (1.0.3) 
Installing rails-assets-get-size (1.1.6) 
Installing rails-assets-jquery-bridget (1.0.1) 
Installing rails-assets-outlayer (1.1.1) 
Installing rails-assets-masonry (3.1.3) 
Installing rails-assets-metafizzy--outlayer (1.1.1) 
Installing rails-assets-isotope (2.0.0.beta.3) 
```

Is this an error in the way the gem was originally built? Can it be rebuilt?

**Comment by sheerun** [comment]
This is correct behavior. Dependencies with -- are forks. -- is replaced by /

For example github.com/desandro/eventie maps to rails-assets-desandro--eventie

We had to do this such way if you think about it long enough ;)

**Comment by sheerun** [comment]
Hmm. @teamon what happens if one gem has dependency on normal component, but other on fork?

Does `= require metafizzy` for example require first or last component?

**Comment by teamon** [comment]
I thinks we missed that case. TBH I don't know what will happen, we need to check that.

**Comment by sheerun** [comment]
I think the core question is what bower does in such case.

**Comment by aaronchi** [comment]
This doesn't explain why the dependencies are duplicated though:

for example:

```
Installing rails-assets-desandro--eventie (1.0.3)
Installing rails-assets-eventie (1.0.3) 
```

There are two 'eventie' gems being loaded. If you install isotope from bower, it just loads the primary eventie library. I haven't looked at the internals, but it also seems like any dependency that was duplicated doesn't load when you include isotope.

**Comment by sheerun** [comment]
@aaronchi 

`isotope` depends on `metafizzy` which depends on:
1. `"eventie": "eventie#>=1.0.3 <2.0"`
2.  `"doc-ready": "desandro/doc-ready#>=1.0.1 <2.0",`

And now `doc-ready` depends on:

```
"eventie": "desandro/eventie"
```

Check out `Gemfile.lock` for details.

So in dependency tree we have two versions of eventie:

```
"eventie": "eventie#>=1.0.3 <2.0" // normal version
"eventie": "desandro/eventie" // github
```

It's not Rails Assets fault, but @desandro because he uses github version of eventie in one project, and normal version in other.

Does it make sense?

**Comment by sheerun** [comment]
Anyway, I and @teamon need to brainstorm what to do in such cases. Any suggestions?

**Comment by aaronchi** [comment]
I guess you need to figure out how bower handles it. Only one library gets installed via bower

**Comment by sheerun** [comment]
You're right. I'm marking this issue as bug. We should comply to bower way of managing dependencies.

**Comment by sheerun** [comment]
I've checked it and it seems that bower treats Github versions like `desandro/eventie` as "any version of desandro/eventie" while we treat it as "latest version of desandro/eventie".

**Comment by sheerun** [comment]
I tried to fix it, but now I'm having problems with circular dependencies that change causes.

I'll touch this problem again tomorrow.

**Comment by desandro** [comment]
Sorry about the bug, but hey, at least you found it. :tulip:

**Comment by sheerun** [comment]
@aaronchi Problem is fixed, but I need to rebuild all gems. I'll let you know.
