### ISSUE TITLE
Ignore *.min.js files

### ISSUE THREAD

**Issue by teamon** [tenex/rails-assets#7]

**Comment by sheerun** [comment]
No such need imho. But we can send PR, that minified versions are not needed..

**Comment by teamon** [comment]
There is a need, in some repos there is

``` json
"main": ["mylib.js", "mylib.min.js"]
```

**Comment by porada** [comment]
I agree that `foo.min.js` is a _valid_ part of project `dist/` contents, but—in such cases—it’s simply a duplicate of `foo.js` and shouldn’t be referenced within `main`.
