### ISSUE TITLE
How to handle some types of files ?

### ISSUE THREAD

**Issue by Jerska** [tenex/rails-assets#73]
Hi,

First of all, thanks for this great tool, please continue this amazing job. :+1: 

I have two questions that are tied together and it seems to me that it doesn't require two issues.
- The first one is `How to handle files that aren't declared in bower.json`. Quick example, dalelotts/angular-bootstrap-datetimepicker only has the `js` file declared in `main`, but the css file is also needed in order to make it work.
- The second one, is `How to handle fonts`. Typically, twbs/bootstrap does include its font files in the `main` part of the `bower.json`, but I can't require it anywhere, and actually a `bundle open rails-assets-bootstrap` showed me that the files weren't even there.
  I assume it has some link with #33 , but I did not see any commit related to fonts.

Thanks in advance !

**Comment by porada** [comment]
1. Go to the [component list](https://rails-assets.org/components), find `angular-bootstrap-datetimepicker`, then click on the version number you’re interested in. You’ll see the paths to assets which you can `//= require` manually.
2. I’m afraid you can’t (at the moment). We’re still in beta, and fonts might need some more work. @teamon @sheerun

**Comment by teamon** [comment]
I think we can handle fonts the same way we handle images. I'll take a look at that tomorrow.

**Comment by porada** [comment]
Closing this issue, as #74 is more specific.

**Comment by sheerun** [comment]
@porada We need better interface for listing of files.

**Comment by porada** [comment]
Yup, #75.

**Comment by Jerska** [comment]
Amazing reactivity. Thanks.

And sorry I didn't see that list of requir-able files on the side.
