### ISSUE TITLE
How to handle fonts

### ISSUE THREAD

**Issue by porada** [tenex/rails-assets#74]
As reported in #73, you can’t use fonts right now. This might require some more thought.

**Comment by sheerun** [comment]
I think the solution is pretty easy: detect file type in url() tag and convert it either to image-url for images (already done) or asset-url() in other cases.

It has to be implemented though.

**Comment by teohm** [comment]
@sheerun +1

Do you mean rails-assets.org are now converting `url()` to `image-url()` in scss when generating asset gems?

**Comment by sheerun** [comment]
yes, and relative paths are fixed

**Comment by teohm** [comment]
@sheerun any plan to support font url() transformation? A common use case will be: sass-bootstrap-glyphicons

**Comment by sheerun** [comment]
It's matter of chaning few lines somewhere here: https://github.com/rails-assets/rails-assets/blob/master/app/models/build/transformer.rb#L145

You can make PR if you want. For now I'm fixing more critical issues.

**Comment by sheerun** [comment]
Also I think is goes beyond just changing url to asset-url for fonts because we don't want to duplicate fonts if few packages use the same font. We'd need to parse font files, extract font faces and concatenate them to some kind of font package.

**Comment by teohm** [comment]
@sheerun should we continue the discussion here? :)

I have a question, do you know how image-url(file), font-url(file), video-url(file) etc. are different from asset-url(file) ?

Starting from Rails 4, it seems like `asset-url(file)` is enough generate all types of asset url.

[1] https://github.com/rails/sass-rails/blob/v4.0.0/lib/sass/rails/helpers.rb
[2] http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#sass-rails

**Comment by sheerun** [comment]
Generally Rails flattens first level of assets directory (each first level directory contains files of different extensions, so generally there are no name-clashes). After that you can reference them with asset-url. Rails 3.x probably required second argument to disambiguate those directories, but 4.0 relies on asset extension/filetype to preprocess it correct way. It's all guessing, I need to do some research.

My current concerns:
- What if Rails 3.2 requires adding fonts directory to `config.assets.paths`
- What if Rails 3.2 properly serves fonts when using asset-url instead of font-url
- What if Rails 4.1 will completely remove support for font-url
- What to do with other kind of assets: .json files, .swf, .mp4, .csv etc.

**Comment by teohm** [comment]
I'm not sure either, I wonder if we can ask someone from Rails sprocket
community for advice.

Your concerns reminds me that Rails will introduce breaking changes in
future. Do you have a plan to support that?

I can imagine rails-assets will need to generate multiple gems to support
conflicting changes in different Rails versions e.g

rails-assets-bootstrap-3.0.4.gem
rails-assets-4.2-bootstrap-3.0.4.gem
rails-assets-5.0-bootstrap-3.0.4.gem

On Wednesday, December 18, 2013, Adam Stankiewicz wrote:

> Generally Rails flattens first level of assets directory (each first level
> directory contains files of different extensions, so generally there are no
> name-clashes). After that you can reference them with asset-url. Rails 3.x
> probably required second argument to disambiguate those directories, but
> 4.0 relies on asset extension/filetype to preprocess it correct way. It's
> all guessing, I need to do some research.
> 
> My current concerns:
> - What if Rails 3.2 doesn't require adding fonts directory to
>   config.assets.paths
> - What if Rails 3.2 properly serves fonts when using asset-url instead
>   of font-url
> - What if Rails 4.1 will completely remove support for font-url
> - What to do with other kind of assets: .json files, .swf, .mp4, .csv
>   etc.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rails-assets/rails-assets/issues/74#issuecomment-30845946
> .

## 

Huiming

**Comment by sheerun** [comment]
I'm thinking about different source endpoints:

```
source 'http://rails-assets.org/4.2'
```

or introducing `rails_assets` gem as dependency that shims incompatibilities.

Generally it's pretty tough problem...

**Comment by teohm** [comment]
Back to the font transformation a bit, I feel that removing duplicate font
definitions should be the responsibility of bower package author,
not rails-asset transformer.

On Wednesday, December 18, 2013, Adam Stankiewicz wrote:

> I'm thinking about different source endpoints:
> 
> source 'http://rails-assets.org/4.2'
> 
> or introducing rails_assets gem as dependency that shims
> incompatibilities.
> 
> Generally it's pretty tough problem...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rails-assets/rails-assets/issues/74#issuecomment-30849450
> .

## 

Huiming

**Comment by sheerun** [comment]
Hmm. I agree. There can be font duplicates when application is using incompatible bower components, but this is out of the scope of rails-assets.

**Comment by teohm** [comment]
@sheerun Do you prefer to include font-url() support first, or wait and work out a more general solution for all assets and multiple Rails versions.

**Comment by masterkain** [comment]
is there a followup somewhere of this ticket? thanks.

**Comment by sheerun** [comment]
@masterkain This issue closed, but old gems need to be recompiled. It'll happen very soon.
