### ISSUE TITLE
Rails assets down

### ISSUE THREAD

**Issue by otzy007** [tenex/rails-assets#74]
Hi,

There were a few days since rails-assets worked for me.
I cannot bundle with either rails-assets.org or rails-assets.tenex.tech as sources

```
Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rails-assets.tenex.tech/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rails-assets.tenex.tech/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rails-assets.tenex.tech/
```

Are there any other mirrors available?
Or there is a way so I can bundle without checking rails-assets?

**Comment by hut8** [comment]
Can you give details? What is the error that `bundle install --verbose` gives? And please point at rails-assets.org; rails-assets.tenex.tech is just going to issue a redirect to rails-assets.org

**Comment by KacperPucek** [comment]
Hi, I can paste the stack. Interestingly enough the same setup works for my "regular" Ruby application but fails for JRuby, here's the stack:

```
HTTP GET http://rails-assets.org/api/v1/dependencies
HTTP 301 Moved Permanently
HTTP GET https://rails-assets.org/api/v1/dependencies
Fetching source index from http://rails-assets.org/
Gem::RemoteFetcher::FetchError: Received fatal alert: handshake_failure (https://rails-assets.org/specs.4.8.gz)
/Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/stdlib/rubygems/request.rb:88:in `connection_for'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/stdlib/rubygems/request.rb:140:in `perform_request'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/stdlib/rubygems/request.rb:109:in `fetch'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/stdlib/rubygems/remote_fetcher.rb:352:in `request'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/stdlib/rubygems/remote_fetcher.rb:237:in `fetch_http'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/stdlib/rubygems/remote_fetcher.rb:253:in `fetch_http'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/stdlib/rubygems/remote_fetcher.rb:273:in `fetch_path'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/rubygems_integration.rb:560:in `fetch_specs'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/rubygems_integration.rb:574:in `block in fetch_all_remote_specs'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/stdlib/rubygems/source_list.rb:90:in `block in each'
  org/jruby/RubyArray.java:1560:in `each'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/stdlib/rubygems/source_list.rb:90:in `each'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/rubygems_integration.rb:572:in `fetch_all_remote_specs'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/fetcher/index.rb:9:in `specs'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/fetcher.rb:102:in `block in specs'
  org/jruby/RubyArray.java:1560:in `each'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/fetcher.rb:100:in `specs'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:330:in `block in remote_specs'
  org/jruby/RubyArray.java:1560:in `each'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:328:in `block in remote_specs'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/index.rb:9:in `build'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:324:in `remote_specs'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:81:in `specs'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/definition.rb:211:in `block in index'
  org/jruby/RubyArray.java:1560:in `each'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/definition.rb:209:in `block in index'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/index.rb:9:in `build'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/definition.rb:206:in `index'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/definition.rb:200:in `resolve'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/definition.rb:129:in `resolve_remotely!'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/installer.rb:79:in `run'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/installer.rb:18:in `install'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/cli/install.rb:107:in `run'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/bin/bundle:20:in `block in (root)'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/bundler-1.10.6/bin/bundle:18:in `<top>'
  org/jruby/RubyKernel.java:958:in `load'
  /Users/kacperpucek/.rbenv/versions/jruby-9.0.0.0/bin/bundle:23:in `<top>'
Could not fetch specs from http://rails-assets.org/
```

**Comment by hut8** [comment]
Got it. Thanks so much for the information. My wild guess is that jRuby's SSL implementation doesn't support SNI, which we're using currently. I'll add another IP address soon so that rails-assets.tenex.tech and rails-assets.org can work without SNI. I'll look into it more shortly.

**Comment by hut8** [comment]
@KacperPucek oh wow, check this out: https://github.com/jruby/jruby/issues/3764 -- a bug was filed against jruby which was actually encountered with rails-assets.org :)

See also: https://github.com/jruby/jruby/issues/2220

They mention a bunch of JVM flags, such as:

```
-Ddeployment.security.SSLv2Hello=false -Ddeployment.security.SSLv3=false 
-Ddeployment.security.TLSv1=false -Ddeployment.security.TLSv1.1=true 
-Ddeployment.security.TLSv1.2=true
```

Is this enough information for you? I want to try to help fix this but that's all I can do in 5 minutes :wink:

**Comment by hut8** [comment]
@RadoMark @KacperPucek if either of you can suggest a better SSL configuration, I will gladly accept it so long as it's not vulnerable to POODLE, etc -- I want to get this fixed ASAP but have quite a few other things going on, including rails-assets stuff. The configuration file is here: https://github.com/tenex/rails-assets/blob/master/infrastructure/nginx-site.conf.j2

**Comment by RadoMark** [comment]
@hut8 I don't have time nor skills/knowledge to fix this, sorry (not now at least). Thanks for quick diagnose, we really appreciate that! Fingers crossed for the fix.

**Comment by KacperPucek** [comment]
@hut8 +1 for what @RadoMark said. Thanks a lot!

**Comment by hut8** [comment]
@RadoMark @KacperPucek This should be resolved. 

I could reproduce this using JDK 8 and jruby-9.0.5.0. I changed the configuration for nginx on rails-assets.org (which serves gems) and now it works. For what it's worth, this was the only change I made:

https://github.com/tenex/rails-assets/commit/3120e5bf6edf636f84a1a599b7e7ed4479f96a8a

I shamelessly copied that list from the "Intermediate compatability" list here: https://wiki.mozilla.org/Security/Server_Side_TLS

Can you confirm it's fixed and close if you're satisfied? I appreciate the information and help you've both offered.

**Comment by RadoMark** [comment]
@hut8 switched to jruby-9.0.5.0 (jdk8) and still got the error:
```sh
$ bundle install --verbose
HTTP GET https://rails-assets.org/api/v1/dependencies
Fetching source index from https://rails-assets.org/
Retrying fetcher due to error (2/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rails-assets.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
```

**Comment by otzy007** [comment]
My problem was with jRuby too. 1.7.23 on OS X 10.11.4

Looks like now it's fixed and it's showing only a warning if I set the env variable SSL_CERT_FILE to this keychain https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt

```
Fetching version metadata from https://rails-assets.org/.WARNING: SSLSocket#session= is not supported
.
```

Using jruby without setting env variable SSL_CERT_FILE to that ca-bundle file I end up with the same error as @RadoMark

**Comment by hut8** [comment]
@RadoMark that looks like a different error. The first one was that it couldn't handshake and the second was a `CertificateFailureError`.  Please use the fix that @otzy007 described. 

See also, https://github.com/jruby/jruby/issues/3765

**Comment by snowdall** [comment]
Ok ... I believe I have found a solution for this.  Or at least a solution that works on my setup.  Firstly, I'm on a Mac OS X 10.10.5.  I'm running jruby-1.7.19.  When rails-assets changed hosting, my certificate started failing.  So in the Gemfile block I just switched it from https to http and that worked for a while.  Then rails-assets.org redirected to the SSL secure port and I was screwed.  In a regular ruby install (not jruby) I had no problem so that told me it was a jruby/jvm issue.  I tried many variations on things I found on the net.  But the FIRST discovery I made was that there was TWO openssl's on my Mac and the JVM seemed to be using ONE, while my testing was using that OTHER.  So I replaced BOTH of them with brew's install of openssl:

`brew update
brew install openssl
brew upgrade openssl
brew link --force openssl
sudo mv /usr/local/bin/openssl /usr/local/bin/openssl_OLD
sudo mv /usr/bin/openssl /usr/bin/openssl_OLD
sudo ln -s /usr/local/Cellar/openssl/1.0.2h/bin/openssl /usr/bin/openssl
sudo ln -s /usr/local/Cellar/openssl/1.0.2h/bin/openssl /usr/local/bin/openssl`

This effectively replaces BOTH system openssl installs with brew's version insuring that you can control both of them.  From there I needed to force the keystore.  So first I fetched the latest certificates to create my own keystore:

`wget http://curl.haxx.se/ca/cacert.pem`

Next I opened the browser and noticed that rails-assets.org uses a root certificate called "DST Root CA X3".  I went into Mac's "Keychain Access" app and exported that entire certificate as a .pem file on my desktop (naming it "DST.pem").  From there I combined both those certificates into a single keystore file:

`sudo keytool -importcert -file ~/Desktop/DST.pem -alias dst -keystore ~/.keystore
sudo keytool -importcert -file ~/Desktop/cacert.pem -alias cacert -keystore ~/.keystore`

The last step was to make sure that openssl could find that combine certificate.  So there's this (and can be put in ~/.profile):

`export SSL_CERT_FILE=/Users/csnowdal/.keystore`

From there I was able to not only get the rails-assets.org gems, but also all the rest.  Hope that helps folks!

Snowdall
