### ISSUE TITLE
Handling SWF filetype

### ISSUE THREAD

**Issue by aaronchi** [tenex/rails-assets#77]
After generating a rails assets gem for zeroclipboard, I found that it only includes the javascript but not the swf file. This may be related to #73

**Comment by sheerun** [comment]
Two issues:
1. I'm not sure if supporting `swf` is the best idea. I guess we can create `others` directory and put it there.
2. In case of zeroclipboard the .swf file needs to be compiled by Grunt. I'm afraid it won't ever happen for Rails Assets.

**Comment by aaronchi** [comment]
I'm not sure this is correct. If you look at the github repo for ZeroClipboard, the compiled swf file is included in the root directory and is also referenced in bower.json.

```
{
  "name": "zeroclipboard",
  "description": "The ZeroClipboard library provides an easy way to copy text to the clipboard using an invisible Adobe Flash movie and a JavaScript interface.",
  "version": "1.3.0-beta.1",
  "main": ["./ZeroClipboard.js", "./ZeroClipboard.swf"],
  "keywords": ["flash","clipboard","copy","cut","paste","zclip","clip","clippy"],
  "license": "https://github.com/zeroclipboard/zeroclipboard/blob/master/LICENSE",
  "authors": [{"name":"Jon Rohan","url":"http://jonrohan.me/"},{"name":"James M. Greene","email":"james.m.greene@gmail.com","url":"http://jamesgreene.net/"}],
  "homepage": "http://zeroclipboard.org/",
  "repository": {"type":"git","url":"https://github.com/zeroclipboard/zeroclipboard.git"},
  "location": "git://github.com/zeroclipboard/zeroclipboard.git"
}
```

**Comment by sheerun** [comment]
Oh, sorry, I didn't notice .swf file there.

I guess the only option is to create `vendor/assets/other/COMPONENT` directory (alongside `javascripts`, `stylesheets`, and `images`), and put all other file formats there (including .swf).

I can also create copies of `main` assets directly under in `vendor/assets/other` directory.

**Comment by sheerun** [comment]
I'm not sure about `other` name though. Any suggestions? For now we have: `javascripts`, `stylesheets`, `images`, `fonts`.

**Comment by sheerun** [comment]
We can also don't care for other extensions and just create `flash` directory.

**Comment by aaronchi** [comment]
The specific name doesn't really matter as long as it's consistent. I'd say swfs or flash

**Comment by mateomurphy** [comment]
Hi, just ran into this issue, is there a fix incoming? I would vote for a `flash` directory, personally

**Comment by mahemoff** [comment]
+1

**Comment by sheerun** [comment]
I implemented it. Please wait for deploy and full reindex. I'll notify about it on our twitter.
