### ISSUE TITLE
IRC?

### ISSUE THREAD

**Issue by jnylen** [tenex/rails-assets#79]
Any IRC channel for the project?
Maybe #rail-assets @ freenode can be something?

**Comment by joshjordan** [comment]
I think @hut8 may have set up a gitter.im. @hut8 is that true?

**Comment by hut8** [comment]
@joshjordan LIES!!! Actually it was @sheerun who did so. Later today I want to get the work from this repo merged into the main rails-assets one. I'll update this later.

**Comment by jnylen** [comment]
Wouldn't a IRC channel on freenode be kinda good too? As most open source projects is on there, such as #letsencrypt etc?

**Comment by hut8** [comment]
Now that I've had plenty of time to think about this, I feel like it's better to have tickets of individual issues, and document anything that people find confusing in the README. I don't think I would be able to dedicate time to paying attention to the channel at all. Thoughts, @joshjordan ?

**Comment by joshjordan** [comment]
For better or for worse, I agree. I think we've been able to respond pretty quickly to opening github issues, and I don't think I'd be able to (read: remember to) keep my eyes on another channel. Maybe we can test it at some point, but for now I'm going to close the issue.
