### ISSUE TITLE
require vs import for stylesheets

### ISSUE THREAD

**Issue by aaronchi** [tenex/rails-assets#79]
I'm not sure if I'm doing something wrong but the rails assets gems don't seem to properly import stylesheets.

I'm looking at the select2 gem as an example. The top level select2.scss contains:

```
/*
 *= require select2/select2
 */
```

When included in my scss stylesheet via `@import 'select2';`, this does nothing. I have to use `@import 'select2/select2';` to get it to work.

If we are using scss for these top level stylesheets, shouldn't we be using @import and not require?

**Comment by sheerun** [comment]
Yup, that's probably bug. We must use @import. @teamon Any comments?

**Comment by teamon** [comment]
This is not that straightforward, not everyone is using @import, many people just stick to sprockets `require`. And this will not work for .css files and I’m not sure about the other engines - @porada?

-- 
Tymon Tobolski
CTO Monterail.com
From: Adam Stankiewicz Adam Stankiewicz
Reply: rails-assets/rails-assets reply@reply.github.com
Date: 17 Dec 2013 at 17:49:39
To: rails-assets/rails-assets rails-assets@noreply.github.com
Subject:  Re: [rails-assets] require vs import for stylesheets (#79)  
Yup, that's probably bug. We should just @import. @teamon Any comments?

**Comment by aaronchi** [comment]
If you want to use require, I think you just need to use a .css extension for the top level stylesheet instead .scss

**Comment by sheerun** [comment]
@aaronchi For now we use css file as default manifest file, not scss.

**Comment by sheerun** [comment]
Oh, I see. We generate css manifest, but later it is converted to scss :(

Maybe the best solution is to create manifest file with the same format as main stylesheet, and use import for scss files while require for css.

**Comment by sheerun** [comment]
On the other hand we convert all css files to scss file to be able to convert all url() to image-url() 

@teamon I think the best solution is to use .scss manifest file and imports

**Comment by porada** [comment]
`@import` is a must—otherwise mixin-only utilities won’t get exposed in any way and will simply be unusable.

**Comment by aaronchi** [comment]
If you are already using scss, then scss is probably the way to go for all css files. If you don't want a dependency on sass, you would have to change the way the url interpolation works in the rest of the css files, using something like 
.css.erb and image_path.
