### ISSUE TITLE
Precompilation issue on rails-assets-handlebars

### ISSUE THREAD

**Issue by anero** [tenex/rails-assets#81]
The rails-assets-handlebars gem on version 1.1.2 includes a NuGet manifest file ([handlebars.js.nuspec](https://github.com/components/handlebars.js/blob/master/handlebars.js.nuspec)) which shouldn't be included in Sprockets' precompilation list.

**Comment by teamon** [comment]
@anero Does this `*.nuspec` file do any harm?

**Comment by sheerun** [comment]
Sprockets tries to compile this file and it throws an exception afair.

After compilation we get following list of files:

```
handlebars.amd.js handlebars.js handlebars.js.nuspec handlebars.runtime.amd.js handlebars.runtime.js
```

And in manifest file we have:

```
//= require handlebars/handlebars
```

Sprockets tries to compile handlebars.js.nuspec (the same way it tries to compile handlebars.js.coffee first), and we get an exception.

I'm not sure if there's a way to circumvent this except excluding nuspec from compiled component...

**Comment by sheerun** [comment]
There wouldn't be a problem if handlebars excluded nuspec in `ignore` section of `bower.json`, but I'm not sure if nuspec is included on purpose (research needed)

**Comment by sheerun** [comment]
@anero Could you post your `Gemfile.lock` or tell when the issue occurred? I'm unable to recreate it.

**Comment by sheerun** [comment]
I'm excluding .nuspec files as temporary fix. Generally either packages need to add such files to bower.json ignore section or https://github.com/sstephenson/sprockets/issues/519  needs to be fixed.
