### ISSUE TITLE
Retrying fetcher due to error (2/4)

### ISSUE THREAD

**Issue by zprima** [tenex/rails-assets#81]
Ruby: 2.1.8.p440 (i386-mingw32)
Windows 10

Tried http://rails-assets.tenex.tech/, http://rails-assets.org

HTTP GET http://rails-assets.org/api/v1/dependencies
HTTP 301 Moved Permanently
HTTP GET https://rails-assets.org/api/v1/dependencies
Fetching source index from http://rails-assets.org/
Retrying fetcher due to error (2/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for http://rails-assets.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Retrying fetcher due to error (3/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for http://rails-assets.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Retrying fetcher due to error (4/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for http://rails-assets.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Could not verify the SSL certificate for http://rails-assets.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most
likely your system doesn't have the CA certificates needed for verification. For
information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect
without using SSL, edit your Gemfile sources and change 'https' to 'http'.

**Comment by zprima** [comment]
Or at least put on the website or somewhere what the actions are.

- Go to a github gist (https://gist.github.com/fnichol/867550) and download the .pem file
- Add it somewhere, and set an windows enviromental setting named SSL_CERT_FILE that points to the file location.

**Comment by hut8** [comment]
I'm on Ruby 2.3 with Windows 10 and it works fine. I haven't installed any special certificates. Did you use the Ruby Installer? I'm using MSYS2.

**Comment by zprima** [comment]
Yes, used Ruby Installer for Windows, not using MSYS2

**Comment by hut8** [comment]
@zprima So you would be satisfied with a link to the gist and instructions in the README?

Also, have you tried this? http://blog.dustinkirkland.com/2016/04/howto-ubuntu-on-windows.html I've been playing around with it and it's pretty sweet, but lots of bugs. https://github.com/Microsoft/BashOnWindows/issues/163 in particular makes ruby stuff hard.

**Comment by zprima** [comment]
@hut8 That would be nice.

I've solved it in my second comment and putted what the steps are. No need to use any MSYS2 or Bash for Windows.
