### ISSUE TITLE
Accessing files in subdirectories?

### ISSUE THREAD

**Issue by mrrooijen** [tenex/rails-assets#82]
I'm trying to use [this little package](https://github.com/wallin/angular-gravatar). However, it requires me to use the `md5.js` file located in it's `src` folder (a dependency of the package).

How can I require this? I tried:

``` coffee
#= require angular-gravatar/src/md5
#= require angular-gravatar
```

But that doesn't work. Is it impossible to access the `md5.js` file?

**Comment by sheerun** [comment]
I'm afraid it's not possible. Because this package selects `./build/angular-gravatar.js` as main file, we assume that all javascripts files are in `./build` and remove this prefix from `vendor/assets/javascripts` of compiled gem.

Don't you think that `md5.js` should be in build directory if it's part of package? If not, why isn't it available as dependency?

**Comment by mrrooijen** [comment]
> Don't you think that md5.js should be in build directory if it's part of package? If not, why isn't it available as dependency?

My thoughts exactly. I guess the author would have to restructure the repository in order to make this work.

Thanks for clarifying!

**Comment by sheerun** [comment]
I encourage you to open issue on author's repository. This package clearly depends on md5 service, but doesn't state it in bower.json, nor include it in builded package.

**Comment by mrrooijen** [comment]
I will. I actually see that the md5 service is available in Bower as a stand-alone package. I'm trying to install that to see if it works. Having some bundler issues, though. Perhaps this is literally the dependency that te author is using, in which case he/she should just define the dependency in the Bower file, no? (I'm not very familiar with Bower yet).

**Comment by mrrooijen** [comment]
Nevermind, looks like it isn't the same thing.

**Comment by sheerun** [comment]
Yes, he should put this component in dependencies section of bower.json

What bundler issues you experience? Could you paste your output?

**Comment by mrrooijen** [comment]
Issue is resolved. It happened a few times to me the past hour. Most likely a networking issue. I'll paste it next time it occurs.

**Comment by sheerun** [comment]
:( Soon we'll change the hosting, I hope it'll help.

**Comment by mrrooijen** [comment]
Ha. No problem at all. Rails Assets is a golden project. My vendor directory was littered, and now I don't have a vendor directory at all! Much better for managing client-side dependencies, especially when upgrading whole frameworks such as Angular. :+1:
