### ISSUE TITLE
Be able to use master/commit version of an asset

### ISSUE THREAD

**Issue by alex88** [tenex/rails-assets#84]
Is is possible to declare a specific commit or branch or git repository when requiring an asset gem? With bower, afaik it's possible.

**Comment by sheerun** [comment]
Yes. It is handled by gem name. For example for `tildeio/rsvp.js` write `rails-assets-tildeio--rsvp.js`

**Comment by sheerun** [comment]
I'll reopen it because we need to document this somehow probably. @teamon @porada  ?

**Comment by alex88** [comment]
And that uses the master of a library?

**Comment by teamon** [comment]
I'm not sure if we want to support this feature. It is sometimes useful but may lead to a lot of issues. —

**Comment by sheerun** [comment]
It uses last version (tag) on fork, just like any other package. We can't use master, because it's constantly changing, and gem assets need recompilation. I also think it's poor development practice. When using master instead of tag, at some point your code stops working.

**Comment by alex88** [comment]
Oh so without master, I think you can close this issue, I needed to use master or at least a specific commit for a fix I needed inside a library, if that can't be done then I'll copy it in my vendors folder and use the gem as soon the new library gets updated

**Comment by sheerun** [comment]
You'll be able to do that, when we extract gem converting bower components to ruby gems. For now online service doesn't support such feature :(

**Comment by alex88** [comment]
Thanks for explaining! ;)
