### ISSUE TITLE
Flowplayer stylesheets missing

### ISSUE THREAD

**Issue by ghost** [tenex/rails-assets#85]
I added:

```
source 'https://rails-assets.org'
gem 'rails-assets-flowplayer'
```

But it seems all the stylesheets are missing:

```
> find /usr | grep -i flowplayer | grep -i css
> 
```

Finds nothing.

However all the javascript and images are there.

**Comment by sheerun** [comment]
Flowplayer has two issues:
1. It doesn't define bower.json manifest, so we don't know for sure what to import
2. Its stylesheet files are written in Stylus and not compiled in repo.

Currently we don't recognise .styl files as stylesheet files, but it should imgo change.

The other problem is: most Rails applications does not compile .styl files by default.

I think what we should do is list extensions mapped to plugins to sprockets engine that compile those extensions, and make those plugins dependency on component gems.

What I mean is: we should make components with `.coffee` files dependent on `coffee-rails`, components with `.styl` files dependent on `ruby-stylus` etc. 

@teamon ?

**Comment by tetherit** [comment]
Sounds like a really good idea :) - This is such a bad ass project.

**Comment by sheerun** [comment]
I've added `.styl` extension to possible extensions but sincerely it doesn't help much for `flowplayer` as it gets syntax error from `stylus` gem, and doesn't have `main` entry in bower.json.
