### ISSUE TITLE
Change settings before the gem files importings

### ISSUE THREAD

**Issue by mdesantis** [tenex/rails-assets#88]
Hello and congratulations for Rails Assets.

I'm using [`gem 'rails-assets-foundation'`](https://github.com/zurb/foundation), and I would change its settings (f.e. `$body-font-family`), but my attempts failed.

This manifest:

```
/*
 *= require_tree .
 *= require_self
 */

$body-font-family: sans-serif;
@import 'foundation';
```

leaves Foundation `body { font-family }` unchanged (that is `font-family: "Helvetica Neue","Helvetica",Helvetica,Arial,sans-serif;` at the moment).

**Comment by porada** [comment]
It’s a repercussion of Rails Assets importing main assets using Sprockets’ `require` directive, even in the case of stylesheets. We’re going to change this behavior so it takes advantage of `@import` instead (where possible), but there’s nothing you can do about it right now (apart from making a pull request).

Closing this issue for now as it’s already been reported.

**Comment by sheerun** [comment]
To be clear it concerns #79 We're going to use import by default soon. I'll post here updates as well.

**Comment by mdesantis** [comment]
Thank you, I will wait for progresses
