### ISSUE TITLE
Implement throttle on https://bower.herokuapp.com

### ISSUE THREAD

**Issue by sheerun** [tenex/rails-assets#89]
It returns 503 if requests are too frequent....

**Comment by bartoszrega** [comment]
Working solution: http://codetunes.com/2011/outbound-api-rate-limits-the-nginx-way/

**Comment by sheerun** [comment]
We can't use nginx with new hosting.

Bower allows to set alternative repository URL though.

**Comment by bartoszrega** [comment]
@sheerun it's almost impossible to handle the outbound throttle without an external service in a reasonable way. 

How often are you making requests to this domain? Maybe proxying on one of our machines would make sense? Or asking the Shellycloud guys to figure out something on their side?

**Comment by sheerun** [comment]
As I said, I can set alternative repository URL for bower to not use bower.herokuapp.com but my proxy service.

**Comment by teamon** [comment]
bower.rails-assets.org proxy? :)—

**Comment by sheerun** [comment]
I don't think it's necessary anymore
