### ISSUE TITLE
Get rid of shell commands

### ISSUE THREAD

**Issue by teamon** [tenex/rails-assets#9]
For sure we can call `bundle gem` and `rake build` from ruby code. I'm not sure about `bower install` - I'd leave it for now.

**Comment by sheerun** [comment]
@teamon Is this resolved?

**Comment by teamon** [comment]
Nope, we're still using bower

**Comment by sheerun** [comment]
You can't call node directly from ruby. I think bower is good api.

**Comment by sheerun** [comment]
We'll never get rid of them. We're using bower via JSON API and it is the only reasonable way to communicate with it. We require bower for repository information retrieval including description, versions, and dependencies. Won't fix.
