### ISSUE TITLE
Won't build latest version

### ISSUE THREAD

**Issue by aaronchi** [tenex/rails-assets#90]
Trying to install rails-assets-masonry -v 3.1.4 gives the following error:

```
ERROR:  While executing gem ... (Gem::UnsatisfiableDependencyError)
    Unable to resolve dependency: 'rails-assets-masonry (= 3.1.4)' requires 'rails-assets-outlayer (< 2.0, >= 1.1.2)'
```

outlayer is at version 1.1.9 but only in rails-assets up to verson 1.1.1 Trying to build from the website using a specific version doesn't build the most recent version of the gem.

**Comment by sheerun** [comment]
Our current production is little messed up. Beginning New Year, we're changing hosting and there won't be such issues. If that's urgent, I can fix current production.

**Comment by aaronchi** [comment]
no worries. I wasn't sure if it was a bug. Good luck with the move.

**Comment by sheerun** [comment]
We're on new servers. It should work now, could you check @aaronchi?

**Comment by aaronchi** [comment]
yes, seems to be ok now.
