### ISSUE TITLE
Question: using rails-assets in gems

### ISSUE THREAD

**Issue by anitagraham** [tenex/rails-assets#91]
Hi,
I have begun using rails-assets in my application. :+1: 
Now I've added it to a gem which is used in the application, but the assets are not being found.

In the gem's Gemfile:
```'ruby
source 'https://rails-assets.org' do
  gem 'rails-assets-multiselect'
end
````

In the application's Gemfile:

````ruby
gem 'mygem'
````

In the logfile when starting the application
````text
 ActionView::Template::Error (File to import not found or unreadable: multiselect.
Load paths:
````
The load paths include the rails-assets paths for the assets in the application's Gemfile, but not the  loadpath for `multiselect`.

Can I use rails-assets in this way. Is there more I need to do?

thanks

**Comment by anitagraham** [comment]
oops, wrong place. sorry

**Comment by joshjordan** [comment]
Are you seeking help elsewhere or do you want to address it here? :-) just
don't want to duplicate effort.

**Comment by hut8** [comment]
I'm going to go ahead and close this since it's also open on the main fork. If you need more assistance please let us know.
