### ISSUE TITLE
Sprockets::FileNotFound: couldn't find file 'adminlte' with type 'application/javascript'

### ISSUE THREAD

**Issue by Faisal-nfl** [tenex/rails-assets#92]
(If this is not the right place to ask, kindly guide me to where is right place )
I am using
source 'https://rails-assets.org' do
  gem 'rails-assets-adminlte'
end
in my rails app, it works fine on local, also for precompilation for production
but when I try to deploy it on digital ocean it say
"Sprockets::FileNotFound: couldn't find file 'adminlte' with type 'application/javascript'"
I never used rails-assets before
kindly tell what I have missed

**Comment by hut8** [comment]
What is in your main application javascript file? (e.g., application.js)?

**Comment by Faisal-nfl** [comment]
yes application.js is main javascript file

**Comment by hut8** [comment]
@Faisal-nfl can you please tell me what is in application.js?

**Comment by Faisal-nfl** [comment]
It was irritating.
At last, I opened "rails-assets-adminlte" gem and copied the adminlte.js and aap.js file and pasted them in my assets/javascripts and changed the path in file accordingly.
And it did the job

**Comment by Faisal-nfl** [comment]
It was irritating.
At last, I opened "rails-assets-adminlte" gem and copied the adminlte.js and aap.js file and pasted them in my assets/javascripts and changed the path in file accordingly.
And it did the job

**Comment by joshjordan** [comment]
But can you tell us what the contents of your `application.js` when it was not working? We have no way to diagnose and fix a potential bug otherwise.

**Comment by Faisal-nfl** [comment]
Sure.
Actually, In assets/javascripts, I have to folders **admin** and **web** .
Issue created was in assets/javascripts/admin/application.js
and its contents were
```
//= require jquery
//= require jquery_ujs
//= require admin/jQuery-2.1.4.min
//= require admin/bootstrap.min
//= require summernote
//= require switchery
//= require adminlte
//= require pnotify
//= require unobtrusive_flash
//= require_tree .

```

**Comment by joshjordan** [comment]
This looks like a case-sensitivity issue. Rails Assets tells you to use `require adminlte`, but you actually would've needed `require AdminLTE`. I'll create an issue. Thanks!

**Comment by Faisal-nfl** [comment]
what the hell that was
I spend more that a day on this
and rails-assests has disappointed me.

**Comment by joshjordan** [comment]
I'm sorry, friend. I'm not sure what the purpose of your comment is.

We responded within an hour, and if you had done what @hut8 asked of you, we could've found the bug very quickly.

**Comment by Faisal-nfl** [comment]
Disappointment in terms of **case issue**.
I make such kind of mistakes when I started programming during studies.
Buts its not good to make such mistakes by professional.
However thanks man for soln.

**Comment by Faisal-nfl** [comment]
Ohhh man
**"AdminLTE"** is still not working with error
couldn't find file 'AdminLTE' with type 'application/javascript'

**Comment by joshjordan** [comment]
Don't need to have two threads of conversation going on this at once, @Faisal-nfl. Please don't copy/paste your responses in two different places. It doesn't t help anyone.
