### ISSUE TITLE
Ignore versions with +

### ISSUE THREAD

**Issue by sheerun** [tenex/rails-assets#92]
@angular is going crazy with his version tags (https://github.com/angular/bower-angular-route/releases), I don't know if they realise that some projects are beginning to be dependent on those tags, and those tags can't be removed without a fuzz. We'll end up with 30000 different versions of angular components.

That's why we should prevent compilation of all tags with `+` inside.

**Comment by teamon** [comment]
IMHO this is reasonable approach, there are no +'s in "normal" versions. —

**Comment by sheerun** [comment]
What do you mean?

**Comment by sheerun** [comment]
Precompiled versions are now excluded from auto update. One can add them manually from www though.
