### ISSUE TITLE
Question: Is it possible to use unregistered bower packages, just from git endpoint?

### ISSUE THREAD

**Issue by panych** [tenex/rails-assets#94]
So, is it possible to do something equal to: `bower install git://github.com/someone/some-package.git` by rails-assets? If so, can you post some example, please?

**Comment by sheerun** [comment]
Yes:

```
gem "rails-assets-someone--some-package"
```

**Comment by sheerun** [comment]
It needs to be tagged though.. We don't compile `master` version for now.

**Comment by sheerun** [comment]
@teamon As I think about it now, it's huge issue. I think we should compile master version of forks, if version is not specified, and mark it as `v1.0.1.someone.abcd12` (fork name + sha). What do you think?

**Comment by panych** [comment]
Thanks, it helps. This feature probably should be mentioned somewhere in the docs.

**Comment by teamon** [comment]
This is rather an unofficial feature. We would like people to fix existing bower packages more than rely on some custom forks when the original package is somehow broken and does not play well with rails assets. —

**Comment by sheerun** [comment]
@porada I'm re-opening this. @teamon Didn't answer my question and we need to discuss this feature once.

**Comment by teamon** [comment]
TBH I think we shouldn't put too much work into supporting building fork with some weird logic. There are other issues that are much more important than this one

**Comment by porada** [comment]
[Agreed](https://github.com/rails-assets/rails-assets/issues/91#issuecomment-31371767).
