### ISSUE TITLE
problem with Digital Ocean hosting

### ISSUE THREAD

**Issue by noiseunion** [tenex/rails-assets#94]
so this is a neat one.  I am unable to deploy to my servers at the moment, which are currently hosted with Digital Ocean, because they are in the same datacenter as the rails-assets.org servers.  As a result, using the suggested source address of `https://rails-assets.org` fails and my deploy pops during the bundle install on the server.  The issue is that my servers can not communicate with the rails-assets.org servers using a Floating IP.

Here is what DO had to say about the issue:

> 
This is a known issue in which the destination you are attempting to reach (45.55.126.192) is a floating IP associated with another Droplet running in the same region as your Droplet. If you were to reach out to their team, they would be able to give you a brief workaround to get around this issue (it involves accessing their Droplet's public IP address and not their floating IP address. For their privacy, I'm not able to give this out directly). 

So what is your suggestion?  Can I update my gemfile to source `https://{your_ip_here}` instead?  Are you guys cool with providing that IP, or am I now supposed to move my servers to a different DO region if I am going to continue to use gems sourced from rails-assets?

**Comment by joshjordan** [comment]
We're definitely not going to leave you hanging or require something like that from you. I also don't want to plaster that IP up on the public internet, though. :) Would you mind shooting me an email at josh.jordan@gmail.com so I can give you this while we work with DO on a better, more permanent solution?

@hut8 might know more about this than I do

**Comment by noiseunion** [comment]
Will do @joshjordan thank you.

**Comment by hut8** [comment]
@noiseunion somewhat surprisingly I discovered this a little while ago: https://github.com/rails-assets/rails-assets/issues/322

If Josh hasn't provided you with the IP, email me at liam@tenex.tech and I will get it to you.

**Comment by noiseunion** [comment]
I am trying the IP that @joshjordan got to me yesterday.  Is DO working on a better fix for this?  I am guessing this will be an issue that occurs more and more.

**Comment by hut8** [comment]
They are working on a better solution. Pinging that IP address will fix it for now as a workaround. Personally I would probably add something in an init script that just pings it so that it's always in the ARP table in case your server reboots.

**Comment by joshjordan** [comment]
@noiseunion to clarify, @hut8 is saying you can JUST ping it, and continue to use rails-assets.org as the Gemfile's `source`, yes?

**Comment by noiseunion** [comment]
yeah unfortunately I have not found that solution to work.  I have pinged the IP and it never comes back for me.

**Comment by noiseunion** [comment]
although, I think I only pinged the 'rails-assets.org' domain.  I don't know if I pinged the floating IP directly.  Let me try that quick and see if that makes a difference.

**Comment by hut8** [comment]
Actually you need to ping the *non-floating* IP. If you don't have the IP address, email me at liam@tenex.tech

**Comment by noiseunion** [comment]
@hut8 so to be clear, you are saying that if I ping the non-floating IP, the floating IP will start working?  Or will my gemfile still need to reference the non-floating IP directly for source?

**Comment by hut8** [comment]
Your gemfile absolutely must reference `https://rails-assets.org` because the SSL certs won't work for an arbitrary IP address. I know this seems backwards, but yes, if you ping the non-floating IP (sinking IP?) then the floating IP will start working. Magic :confetti_ball:

**Comment by noiseunion** [comment]
Yeah I just saw it work that way.  I can definitely do a script to handle this for now, but it obviously is not a solid long-term solution.  Hopefully DO can get it resolved soon.  I really appreciate the help from both of you guys!  Thank you.

**Comment by pch** [comment]
I've been experiencing the same issue. Just to make it easier for others to find: 

The work-around is to ssh to your server and run `ping 45.55.42.52` - bundle should work (magically) afterwards.
