### ISSUE TITLE
why require assets error？

### ISSUE THREAD

**Issue by ytwman** [tenex/rails-assets#95]
i'm don't speak english，to the following:

gemfile added

```
gem 'rails-assets-fancybox', '2.1.5'
gem 'rails-assets-bootstrap', '3.0.3'
gem 'rails-assets-highcharts', '3.0.7'
gem 'rails-assets-underscore', '1.5.2'
gem 'rails-assets-underscore.string', '2.3.3'
```

at application.js or application.css added

```
//= require bootstrap
//= require fancybox
//= require placeholder
//= require smooth-scroll
//= require underscore.string
```

errors

```
Sprockets::FileNotFound at /
couldn't find file 'underscore.string'
  (in app/assets/javascripts/application.js:15)
```

```
Sprockets::FileNotFound at /
couldn't find file 'fancybox'
  (in app/assets/javascripts/application.js:14)
```

**Comment by Tuckie** [comment]
You're not including the correct files.  Take a look at the files being included by clicking on a specific version in the Component list, e.g. 

```
All scripts:
fancybox/source/jquery.fancybox.pack.js
fancybox/source/jquery.fancybox.js
fancybox/source/helpers/jquery.fancybox-thumbs.js
fancybox/source/helpers/jquery.fancybox-media.js
fancybox/source/helpers/jquery.fancybox-buttons.js
fancybox/lib/jquery.mousewheel-3.0.6.pack.js
fancybox/lib/jquery-1.9.0.min.js
fancybox/lib/jquery-1.10.1.min.js
```

I haven't tested this, but what you're probably looking for is source/jquery.fancybox

**Comment by sheerun** [comment]
Both `fancybox` and `underscore.string` don't have `main` entry defined in `bower.json` (you get this notification during installation.), so you can't use shorter forms of includes. 

You need to do `//= require fancybox/source/jquery.fancybox.js`. 

Please open pull requests on those repositories to update `bower.json` to include `main` entry.
