### ISSUE TITLE
`vendor/assets/fonts/` not included by default in Rails 4 asset precompile

### ISSUE THREAD

**Issue by teohm** [tenex/rails-assets#96]
Hi,

Currently, rails-assets places font files under `vendor/assets/fonts/`.

However, in Rails 4 asset precompile, by default, only non-js/css files under `app/assets/` are included [1]. Font files under `vendor/assets/fonts` are not included by default.

Is this an intended behavior?

Currently, to include the font files into asset precompile, I have to manually add them:

```
#  config/environments/production.rb
  ...
  config.assets.precompile << lambda do |filename, path|
    path =~ /vendor\/assets/ && !%w(.js .css).include?(File.extname(filename))
  end
```

[1] https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/railtie.rb#L40

**Comment by sheerun** [comment]
That's a bummer. I thought all top-level directories are included. We're going to make component gems dependent on sprockets and compilation engines, so I could add paths to sprockets on component side. Stay tuned.

**Comment by teohm** [comment]
@sheerun Great!

I was thinking about setting `config.assets.precompile` in the Rails railtie hook like [1]

[1] https://github.com/heroku/rails_serve_static_assets/blob/master/lib/rails_serve_static_assets/railtie.rb

**Comment by chrisnicola** [comment]
I'm a little confused, assuming I wish to use something like font-awesome, how to I get it to precompile the font files?

**Comment by sheerun** [comment]
@chrisnicola Rails-assets should properly include font files in package assuming `bower.json` is correct.

**Comment by teohm** [comment]
@sheerun Any updates on the issue?

**Comment by sheerun** [comment]
Hey. For now I'm working on other issues. Maybe next week.

**Comment by prashantrajan** [comment]
relates to #151

**Comment by sheerun** [comment]
Let's track this in #152
