### ISSUE TITLE
rails-assets-alasql-0.2.2 not found

### ISSUE THREAD

**Issue by balvig** [tenex/rails-assets#98]
Hello guys, first of all thanks so much for picking up this project and keeping it alive! 🙏 

Ran into an issue today that is preventing us from deploying with capistrano:

```
bundle stdout: Net::HTTPNotFound: File not found:
/quick/Marshal.4.8/rails-assets-alasql-0.2.2.gemspec.rz
```

The strange thing is that:

1. It seems like that gem should be [available on rails-assets](https://rails-assets.org/#/components/alasql?version=0.2.2)
2. This gem is nowhere to be found in `Gemfile.lock` so I don't understand why bundler would be trying to do something with it in the first place! 😓 

Is there anything we're overlooking?

**Comment by joshjordan** [comment]
Our pleasure!

Whoa, this is a strange one! I think you are right on both points. Can you post your `Gemfile`, as a sanity check? Can shoot it to me by email if you prefer to keep it private: josh.jordan@gmail.com

I'm hoping against hope there isn't a transient failure here. In the meantime, can you try to `bundle` locally, or try your deploy again? I was able to `bundle install` rails-assets-alasql 0.2.2, but I know that's not the scenario you're looking at and I want to see if we can reproduce this reliably.

**Comment by balvig** [comment]
@joshjordan thanks for looking into this!! 🙇  I've sent you the gemfile.
As an aside this morning I tried 

````bash
gem install rails-assets-alasql -v 0.2.2 --source https://rails-assets.org
```

which resulted in:

```
ERROR:  Could not find a valid gem 'rails-assets-alasql' (= 0.2.2), here is why:
          Unable to download data from https://rails-assets.org/ - bad response Not Found 404 (https://rails-assets.org/quick/Marshal.4.8/rails-assets-alasql-0.2.2.gemspec.rz)
```

However,

```bash
gem i rails-assets-alasql -v 0.2.6 --source https://rails-assets.org
```

seems to work okay (question as to why that gem is even popping up as we're not requiring it remains though! 😅 )

**Comment by joshjordan** [comment]
Jens, I have not yet gotten to the bottom of this in terms of *why* you're
encountering this gem's installation, however, I believe I've corrected the
error with alasql 0.2.2 so at least you will be unblocked. Can you confirm
that this is working now: gem install rails-assets-alasql -v 0.2.2 --source
https://rails-assets.org

**Comment by joshjordan** [comment]
I dug into your Gemfile, and expected to see rails-assets-alasql as a
transitive dependency, but I do not see that in the Gemfile.lock after
bundle installing this. I'm going to drop the investigation for now until
we have more evidence of the underlying problem.

**Comment by balvig** [comment]
Dunno if it helps, but now it's happening with a different gem (which is also not a transitive dependency...):

```
bundle stdout: Net::HTTPNotFound: File not found:
/quick/Marshal.4.8/rails-assets-angular-base64-upload-0.1.14.gemspec.rz

SSHKit::Command::Failed: bundle exit status: 17
bundle stdout: Net::HTTPNotFound: File not found:
/quick/Marshal.4.8/rails-assets-angular-base64-upload-0.1.14.gemspec.rz
```

**Comment by joshjordan** [comment]
@balvig yikes! Okay. I'm on it. Did it start working, and now break, or was this just the next error after the `alasql` error was resolved? Can you post or send me the full deployment output?

**Comment by joshjordan** [comment]
I do want to get to the bottom of this, but I can't seem to reproduce this. Does it happen only when deploying, or also when `bunde install`ling locally? If you use a brand new/empty gemset, do you see this?

I do not when doing `bundle install` with your `Gemfile`, but I also need to comment a number of gems because they are vendored in your app. Would love to get involved more deeply! :)

**Comment by balvig** [comment]
Great, thanks @joshjordan! Let me try it out locally with an empty gemset and get back to you asap :)

Re deployment output, there's a lot of it (lot of unrelated stuff too), but the gist of it is it gets to the bundler stage, running bundler on several hosts:


```
INFO [f782da89] Running /usr/bin/env bundle install --path /home/app/shared/bundle --without development test --deployment --quiet on 001.us-east-1.compute.internal
...
```

It _seems_ several of them succeed, but then one will fail:

```
INFO [3899b09f] Finished in 2.607 seconds with exit status 0 (successful).
INFO [7a694067] Finished in 78.823 seconds with exit status 0 (successful).
INFO [f782da89] Finished in 78.817 seconds with exit status 0 (successful).
INFO [1637fe98] Finished in 78.829 seconds with exit status 0 (successful).
INFO [10541df3] Finished in 78.826 seconds with exit status 0 (successful).
INFO [99c15a07] Finished in 78.818 seconds with exit status 0 (successful).
INFO [4f83f729] Finished in 78.825 seconds with exit status 0 (successful).
INFO [3795dc46] Finished in 78.831 seconds with exit status 0 (successful).
INFO [8763f4e8] Finished in 78.865 seconds with exit status 0 (successful).
INFO [c2c873d7] Finished in 79.691 seconds with exit status 0 (successful).
INFO [4b05f4d4] Finished in 90.817 seconds with exit status 0 (successful).
INFO [ff671f66] Finished in 91.743 seconds with exit status 0 (successful).
INFO [ca60166a] Finished in 94.461 seconds with exit status 0 (successful).
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host 006.us-east-1.compute.internal: bundle exit status: 17
bundle stdout: Net::HTTPNotFound: File not found:
```

**Comment by joshjordan** [comment]
Crazy. Is there any reason to expect that that host may be doing something different? Is it always the same one? Can we get more verbose output (for example, what command its actually running on this step)?

**Comment by balvig** [comment]
> Is there any reason to expect that that host may be doing something different

It was actually a different host failing earlier, so seems pretty random... 😢 

> Can we get more verbose output (for example, what command its actually running on this step)?

Here's some output using `cap deploy production --trace` that was captured when alasql was failing:

```
/Users/jens/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/sshkit-1.8.1/lib/sshkit/runners/parallel.rb:16:in `rescue in block (2 levels) in execute'
/Users/jens/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/sshkit-1.8.1/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
SSHKit::Command::Failed: bundle exit status: 17
bundle stdout: Net::HTTPNotFound: File not found:
/quick/Marshal.4.8/rails-assets-alasql-0.2.2.gemspec.rz
bundle stderr: fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
/Users/jens/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/sshkit-1.8.1/lib/sshkit/command.rb:100:in `exit_status='
/Users/jens/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/sshkit-1.8.1/lib/sshkit/backends/netssh.rb:127:in `execute_command'
/Users/jens/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:121:in `block in create_command_and_execute'
/Users/jens/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:121:in `tap'
/Users/jens/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:121:in `create_command_and_execute'
/Users/jens/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:53:in `execute'
/Users/jens/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/capistrano-bundler-1.1.4/lib/capistrano/tasks/bundler.cap:35:in `block (5 levels) in <top (required)>'
/Users/jens/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:72:in `with'
/Users/jens/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/capistrano-bundler-1.1.4/lib/capistrano/tasks/bundler.cap:26:in `block (4 levels) in <top (required)>'
/Users/jens/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:64:in `within'
/Users/jens/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/capistrano-bundler-1.1.4/lib/capistrano/tasks/bundler.cap:25:in `block (3 levels) in <top (required)>'
/Users/jens/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:15:in `instance_exec'
/Users/jens/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:15:in `run'
/Users/jens/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/sshkit-1.8.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => deploy:updated => bundler:install
The deploy has failed with an error: Exception while executing on host 004.us-east-1.compute.internal: bundle exit status: 17
```

>  Did it start working, and now break, or was this just the next error after the alasql error was resolved

Good question! It's hard to tell as It seems to only happen when we make changes to the gemfile (even _removing_ gems!), but I do think it actually worked for one deploy where we had a gemfile change after the alasql problem was resolved.

> Does it happen only when deploying, or also when bunde installling locally? 

Just tried it locally, and it went without a hitch! 😓  I guess the fact that it seems to work on _some_ hosts is also a bit suspicious... 😅 

Thanks again for looking into this! Let me know if there's anything else I can provide to help debug!

**Comment by joshjordan** [comment]
What we really need to dig into is "why is it requesting this gem?"

The output is extra confusing, since it includes other fatal errors: `Not a
git repository (or any of the parent directories): .git` and it isn't clear
if those are related. @balvig, for now, I'm going to wait on your report on
bundling with a fresh gemset. Not much else to go on right now :)

**Comment by balvig** [comment]
Ah, please ignore `Not a git repository (or any of the parent directories): .git`, this was happening back when everything was working properly 😅 

Fresh gemset seemed to work just fine locally... 😢

**Comment by joshjordan** [comment]
Damn. I'm out of tricks - without a reproducible case, my next step would be to start debugging through bundler to trace the reason its requesting this gem, but I don't have access to your boxes or your deployment setup :)

**Comment by hut8** [comment]
@balvig I'm going to go ahead and close this in day or two unless you have updates regarding the differences between the hosts (do they end up with different `Gemfile.lock`s?), or want additional help.

**Comment by balvig** [comment]
Thanks @hut8! We're still seeing this intermittently, and currently investigating https://github.com/sonots/capistrano-bundle_rsync as to whether that has some influence on the bug occurring. Will re-open if we finde more info!
