### ISSUE TITLE
Problem with the font-awesome package

### ISSUE THREAD

**Issue by chrisnicola** [tenex/rails-assets#99]
The component-font-awesome seems to work (other than asset precompile issues with the fonts themselves) but the regular font-awesome package throws an error with the SCSS. It appears to be due to this at the top of font-awesome.scss

```

---

---
{% include license-code.less %}
```

The error is:

```
Invalid CSS after "-": expected number or function, was "--"
```

Not sure where to start here.

**Comment by sheerun** [comment]
Hey. Isn't it font-awesome issue? This is invalid scss file. They don't have bower.json, so we take un-compiled scss file from `src` directory by some simple heuristic. Could you open an issue on their repository?

**Comment by chrisnicola** [comment]
Strangely, this text doesn't show up in the font-awesome repository anywhere, only the one I end up getting from rails-assets when I install via bundler.

**Comment by chrisnicola** [comment]
Hmm searching a bit further I think I've found it. Appears to be a generated file somewhere else in the repo:
https://github.com/FortAwesome/Font-Awesome/blob/master/src/assets/font-awesome/scss/font-awesome.scss

Anyways the "components" version of font-awesome is working for me now, I just had to deal with the issue of loading the font through the asset pipeline first. It would probably make sense though to create a fork of Font-Awesome specifically targeted to work out of the box with Rails/RailsAssets. When the PRs on font paths are pulled in I'll try to do that.

Cheers!

**Comment by ivanyv** [comment]
Hi Chris, I'm having the same issue, I'm close to just switching to plain bower. What do you mean by "components" version? Thanks!

**Comment by sheerun** [comment]
https://github.com/components/font-awesome

**Comment by sheerun** [comment]
Also remember to add fonts directory to your asset paths

**Comment by ivanyv** [comment]
Cool, thanks!

**Comment by ivanyv** [comment]
I have to say I find this odd. Reviewing Font-Awesome's history, it seems those lines were added 7 months ago, and this project I've been working with for the past couple weeks just suddenly has this issue.

If I compare the gem I had in Ruby 2.0.0 with 2.1.0, the old installation doesn't have those 2 `---` lines, so I tried to see what had changed in `rails-assets` that could cause this. Alas, I've been unsuccessful.

Any pointers?

**Comment by sheerun** [comment]
https://github.com/components/font-awesome doesn't work for you? Could you post your Gemfile?

**Comment by ivanyv** [comment]
Haven't tried yet, but I gotta say I have no idea how to use that in a Rails way. Would I just pull it down with `component` and put in in `vendor/assets`? Because that would not really work as I'm customizing the `$fa-font-path` so I need the source.

Here's my `Gemfile`: http://pastie.org/8655334

Thanks!

**Comment by sheerun** [comment]
Components version of font-awesome has source .scss files:
https://github.com/components/font-awesome/tree/master/scss

If you look at `bower.json` of this repository, the bower name is `components-font-awesome`:
https://github.com/components/font-awesome/blob/master/bower.json

In your gemfile you still use official version.

After changing gem to `rails-assets-components-font-awesome` you need to

```
@include "components-font-awesome/scss/font-awesome";
```

And after that you can use or modify any variables you want.

I hope it works, I didn't check.

**Comment by sheerun** [comment]
Actually if you click version number on https://rails-assets.org/components you can see that .scss is chosen by rails-assets as default stylesheet file, so following is enough:

```
@include "components-font-awesome";
```

**Comment by ivanyv** [comment]
Sweet, thanks! Just learned about `component` and `components` today so I was confused and unsure about what I was doing at first :D

**Comment by sheerun** [comment]
Cool. If anything goes wrong you can always use "officially packed" version of gems. For font-awesome it is:

https://github.com/bokmann/font-awesome-rails
